#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/simplify-ubuntu
#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/simplify-ubuntu/completions
# Started On        - Fri 29 Jan 01:22:20 GMT 2021
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for Simplify Ubuntu.
#------------------------------------------------------------------------------

_simplifyubuntu() {
	local Option Arg Args

	while read; do
		[[ ${REPLY:0:2} == '  ' ]] || continue

		Option=${REPLY%% - *}
		for Arg in ${Option//,/}; {
			Args+="${Arg##[^-]*} "
		}
	done <<< "$(simplify-ubuntu -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	fi
}

complete -F _simplifyubuntu simplify-ubuntu
