#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/local/bin/simplify-ubuntu
#------------------------------------------------------------------------------
# Project Name      - Extra/source/simplify-ubuntu/simplify-ubuntu
# Started On        - Fri 12 Jan 04:52:52 GMT 2018
# Last Change       - Sat  3 Jun 13:38:10 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   apt (>= 1.2.32)
#   bash (>= 4.3-14)
#   coreutils (>= 8.25-2)
#------------------------------------------------------------------------------

CurVer='2023-06-03'
Progrm=${0##*/}

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -F, --ignore-fonts       - Don't ask font-specific questions.
		  -L, --ignore-lsb         - Don't check distribution via lsb_release.
		  -N, --no-ask-de          - Don't ask DE-specific questions.
		  -Y, --yes-apt            - Equivalent of the -qq flag for apt-get(8).
		  -p, --purge              - Also purge the chosen packages.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

FileOS='/etc/os-release'
FileLSB='/etc/lsb-release'
StatusFile='/var/lib/dpkg/status'

Args=()
while [[ -n $1 ]]; do
	case $1 in
		-[^-]*)
			Str=${1#-}
			Len=${#Str}
			for (( Index = 0; Index < Len; Index++ )); {
				Args+=(-"${Str:Index:1}")
			} ;;
		*)
			Args+=("$1") ;;
	esac
	shift
done

set -- "${Args[@]}"

while [[ -n $1 ]]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"
			exit 0 ;;
		--ignore-fonts|-F)
			IgnoreFonts='true' ;;
		--no-ask-de|-N)
			NoAskDE='true' ;;
		--ignore-lsb|-L)
			LSBCheck='false' ;;
		--purge|-p)
			DoPurge='--purge' ;;
		--yes-apt|-Y)
			YesAPT='-qq' ;;
		-*)
			Err 1 'Incorrect argument(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

for CurDep in rm apt-get; do
	if ! type -P "$CurDep" &> /dev/null; then
		Err 0 "Dependency '$CurDep' not met."
		(( DepCount++ ))
	fi
done

(( DepCount == 0 )) || exit 1

(( UID == 0 )) || SIM='-s'

#---------------------------------------------------------------Welcome Message

read -d '' <<-EOF

	What will follow is a series of prompts which will ascertain how you would
	like to tweak (lighten) your Ubuntu installation of Linux, based on your
	needs.

	NOTE: Each question, for troubleshooting reasons, is assigned a number; if
	      you run into any issues with a question, please feel free to
	      reference it.

	At any point during a question, the following can be entered, in upper- or
	lower-case, using either the single-character or word:

	  Y|YES     - You're answering "Yes" to the question.
	  N|NO      - You're answering "No" to the question.
	  I|INFO    - You're asking for additional information, if available.
	  W|WHAT    - You're asking for a description of the applicable package(s).
	  Q|QUIT    - You're opting to immediately quit the program.

	WARNING: Misused, this program could make a mess of your installation.

EOF

printf '%s' "$REPLY"

#------------------------------Generate Associative Array of Installed Packages

if [[ -f $StatusFile && -r $StatusFile ]]; then
	printf 'Generating list of installed packages...\n'

	declare -A Packages
	while IFS=':' read Key Value; do
		case $Key in
			Package)
				Name=${Value# } ;;
			Status)
				if [[ ${Value# } == install\ ok\ installed ]]; then
					Packages["$Name"]='True'
				fi ;;
		esac
	done < "$StatusFile"
else
	Err 1 "File '$StatusFile' missing or unreadable."
fi

#----------------------------------------------------------------Main Functions

DoSay() {
	printf '%s\n' "$1"
}

PathLook() {
	type -P "$@" &> /dev/null || return 1
}

Prompt() {
	while :; do
		read -ep "$1 "

		case $REPLY in
			[Yy]|[Yy][Ee][Ss])
				return 0; break ;;
			[Nn]|[Nn][Oo])
				return 1; break ;;
			[Ii]|[Ii][Nn][Ff][Oo])
				DoSay "INFO: ${2:-No additional information is available.}" ;;
			[Ww]|[Ww][Hh][Aa][Tt])
				DoSay "WHAT: ${3:-Description not available for this question.}" ;;
			[Qq]|[Qq][Uu][Ii][Tt])
				exit 2 ;;
			*)
				Err 0 "Unrecognised response. Enter 'Y' or 'N' to continue." ;;
		esac
	done
}

RemPKG() {
	apt-get ${YesAPT:--q} $SIM --show-progress remove $DoPurge --autoremove\
		-o Dpkg::Progress-Fancy=true -o Dpkg::Progress=true "$@"
}

FindPKG() {
	local Found=0
	for CurPKG in "$@"; {
		printf "Looking for '%s'\n" "$CurPKG"

		for FoundPKG in "${!Packages[@]}"; {
			if [[ $FoundPKG == $CurPKG ]]; then
				printf "Found '%s'\n" "$FoundPKG"
				(( Found++ ))
			fi
		}
	}

	unset CurPKG FoundPKG

	(( Found == $# )) || return 4
}

#------------------------------------------------------------------------------

if [[ ${LSBCheck:-true} == true ]]; then
	if [[ -f $FileOS && -r $FileOS ]]; then
		while IFS="=" read -a Line; do
			if [[ ${Line[0]} == ID ]]; then
				printf -v LSBRelease "%s" "${Line[1]}"
				break
			fi
		done < "$FileOS"
	elif [[ -f $FileLSB && -r $FileLSB ]]; then
		while IFS="=" read -a Line; do
			if [[ ${Line[0]} == DISTRIB_ID ]]; then
				printf -v LSBRelease "%s" "${Line[1],,}"
				break
			fi
		done < "$FileLSB"
	else
		Err 1 "Unable to determine the distribution ID."
	fi

	case $LSBRelease in
		linuxmint)
			IsMint='true'

			read -d '' <<-EOF
				WARNING: Simplify-ubuntu has detected an installation of Linux Mint. Although your
				         chosen distribution was not the initial target for $Progrm, there
				         is ample support given.

				         However, this could be considered 'experimental', so be sure to take even
				         greater care with your answers.

				CAUTION: The --no-ask-de|-N flags may be ignored if Mint is detected.

			EOF

			printf '%s' "$REPLY"

			if PathLook mintwelcome; then
				Prompt\
					"[5829]: Do you need the mintwelcome package?"\
					"If you enter 'N', packages mintwelcome and mint-meta-core will be removed."\
					"The Mint Welcome Screen you by default see at login."\
				|| {
					DoSay "Calling APT to remove mintwelcome and related packages."
					RemPKG mintwelcome
				}
			fi

			if PathLook mintupdate; then
				Prompt\
					"[5717]: Do you need the mintupdate package? (say yes if unsure)"\
					"If you enter 'N', mintupdate and associated packages will be removed."\
					"Mint's own GUI package Update Manager."\
				|| {
					DoSay "Calling APT to remove mintupdate and related packages."
					RemPKG mintupdate
				}
			fi

			if PathLook mintbackup; then
				Prompt\
					"[0032]: Will you be needing mintbackup (HOME backup tool)?"\
					"If you enter 'N', the mintbackup package will be removed."\
					"Mint's own lightweight data backup solution."\
				|| {
					DoSay "Calling APT to remove the mintbackup package."
					RemPKG mintbackup
				}
			fi

			if PathLook mintinstall; then
				Prompt\
					"[0887]: Will you be needing mintinstall (Enter 'Y' if unsure)?"\
					"If you enter 'N', mintinstall packages will be removed."\
					"Mint's own Software Center for getting new packages."\
				|| {
					DoSay "Calling APT to remove mintinstall packages."
					RemPKG mintinstall\*
				}
			fi

			if PathLook mintdrivers; then
				Prompt\
					"[5235]: Will you be needing mintdrivers (Enter 'Y' if unsure)?"\
					"If you enter 'N', the mintdriver package will be removed."\
					"Mint's own driver manager."\
				|| {
					DoSay "Calling APT to remove the mintdrivers package."
					RemPKG mintdrivers
				}
			fi

			if PathLook mintstick; then
				Prompt\
					"[9763]: Will you be needing mintstick (Enter 'Y' if unsure)?"\
					"If you enter 'N', the mintstick package will be removed."\
					"Write ISO or IMG files to a storage device, such as a USB pendrive."\
				|| {
					DoSay "Calling APT to remove the mintstick package."
					RemPKG mintstick
				}
			fi

			if PathLook mintlocale; then
				Prompt\
					"[4384]: Will you be needing mintlocale (locale settings GUI)?"\
					"If you enter 'N', the mintlocale package will be removed."\
					"A simple GUI for changing locale settings in Mint."\
				|| {
					DoSay "Calling APT to remove the mintlocale package."
					RemPKG mintlocale
				}
			fi

			if PathLook mintupload-manager; then
				Prompt\
					"[4843]: Will you be needing mintupload? (Upload Manager)"\
					"If you enter 'N', the mintupload package will be removed."\
					"Mint's own file GUI Upload Manager."\
				|| {
					DoSay "Calling APT to remove the mintupload package."
					RemPKG mintupload
				}
			fi

			Prompt\
				"[7021]: Will you be needing Mint-specific artwork? (Enter 'Y' if unsure)"\
				"If you enter 'N', packages related to Mint artwork will be removed."\
				"This can include packages you ordinarily don't want to remove!"\
			|| {
				Prompt\
					"[4117]: CAUTION! This will remove Mint icons, themes, wallpapers, etc. Are you sure?"\
					"If you enter 'Y', you agree to continue removing the Mint artwork."\
					"Note that various Mint-based packages mark some of these as dependencies."\
				&& {
					DoSay "Calling APT to remove the Mint artwork packages."
					RemPKG mint-{artwork-\*,backgrounds\*,{x,y}-icons,{y-theme,themes\*}}
				}
			}

			if PathLook mintreport; then
				Prompt\
					"[9742]: Will you be needing mintreport? (error reporting tool)"\
					"If you enter 'N', the mintreport package will be removed."\
					"If you need to submit bug reports, this Mint GUI tool does it."\
				|| {
					DoSay "Calling APT to remove the mintreport package."
					RemPKG mintreport
				}
			fi

			if PathLook xplayer; then
				Prompt\
					"[5775]: Will you be needing Xplayer? (media player)"\
					"If you enter 'N', the Xplayer packages will be removed."\
					"Mint's own simple and lightweight media player."\
				|| {
					DoSay "Calling APT to remove the Xplayer packages."
					RemPKG \*xplayer\*
				}
			fi

			if PathLook xreader; then
				Prompt\
					"[4855]: Will you be needing Xreader? (document viewer)"\
					"If you enter 'N', the Xreader packages will be removed."\
					"Mint's own document viewer for files like PDFs."\
				|| {
					DoSay "Calling APT to remove the Xreader packages."
					RemPKG xreader\*
				}
			fi

			if PathLook xviewer; then
				Prompt\
					"[9772]: Will you be needing Xviewer? (image viewer)"\
					"If you enter 'N', the Xviewer packages will be removed."\
					"Mint's own simple and lightweight image viewer."\
				|| {
					DoSay "Calling APT to remove the Xviewer packages."
					RemPKG xviewer\*
				}
			fi

			if PathLook xed; then
				Prompt\
					"[3867]: Will you be needing Xed? (text editor)"\
					"If you enter 'N', the Xed packages will be removed."\
					"Mint's own simple and lightweight GUI text editor."\
				|| {
					DoSay "Calling APT to remove the Xed packages."
					RemPKG xed\*
				}
			fi

			if PathLook pix; then
				Prompt\
					"[3323]: Will you be needing pix (image editor)?"\
					"If you enter 'N', pix packages will be removed."\
					"Mint's own advanced image viewer and browser."\
				|| {
					DoSay "Calling APT to remove pix packages."
					RemPKG pix\*
				}
			fi

			;;
		ubuntu)
			IsUbuntu='true' ;;
		zorin)
			IsZorin='true'

			read -d '' <<-EOF
				WARNING: Simplify-ubuntu has detected an installation of Zorin OS. Although your
				         chosen distribution was not the initial target for $Progrm, it's
				         still built on Ubuntu.

				         However, this should be considered 'experimental', so be sure to take even
				         greater care with your answers.

			EOF

			printf '%s' "$REPLY"

			if PathLook playonlinux; then
				Prompt\
					"[5542]: Will you be needing PlayOnLinux (via WINE)?"\
					"If you enter 'N', PlayOnLinux packages will be removed."\
					"PlayOnLinux makes use of WINE (is Not an Emulator)."\
				|| {
					DoSay "Calling APT to remove PlayOnLinux packages."
					RemPKG playonlinux
				}
			fi

			;;
		*)
			Err 1 "Unsupported distribution ID detected." ;;
	esac
fi

#TODO: This is a sloppy way to detect the distribution, and is only temporary!
PathLook lite-welcome && IsLinuxLite='true'

if [[ $IsLinuxLite == true ]]; then
	read -d '' <<-EOF
		WARNING: Simplify-ubuntu has detected an installation of Linux Lite.
		         Although your chosen distribution was not the initial target
		         for $Progrm, it's still built on Ubuntu.

		         However, this should be considered 'experimental', so be sure
		         to take even greater care with your answers.

	EOF

	printf '%s' "$REPLY"

	if PathLook lite-welcome; then
		Prompt\
			"[2245]: Will you need the Linux Lite welcome screen?"\
			"If you enter 'N', the lite-welcome package will be removed."\
			"The Linux Lite Welcome Screen."\
		|| {
			DoSay "Calling APT to remove the lite-welcome package."
			RemPKG lite-welcome
		}
	fi

	if PathLook lite-updatesnotify; then
		Prompt\
			"[8363]: Will you need the Linux Lite updates notifier? (Enter 'Y' if unsure)"\
			"If you enter 'N', the lite-updatesnotify package will be removed."\
			"The Linux Lite Update OSD notification."\
		|| {
			DoSay "Calling APT to remove the lite-updatesnotify package."
			RemPKG lite-updatesnotify
		}
	fi

	if PathLook lite-tweaks || PathLook lite-tweaks-super; then
		Prompt\
			"[1052]: Will you need the Lite Tweaks program?"\
			"If you enter 'N', lite-tweaks and related packages will be removed."\
			"A collection of tools to tweak and clean your Linux Lite system."\
		|| {
			DoSay "Calling APT to remove the lite-tweaks package."
			RemPKG lite-tweaks\*
		}
	fi

	if PathLook lite-info; then
		Prompt\
			"[7743]: Will you need the Lite Info program?"\
			"If you enter 'N', the lite-info package will be removed."\
			"Submit and view the Linux Lite hardware database."\
		|| {
			DoSay "Calling APT to remove the lite-info package."
			RemPKG lite-info
		}
	fi

	if PathLook lite-manual; then
		Prompt\
			"[5565]: Will you need the Lite Manual program?"\
			"If you enter 'N', the lite-manual package will be removed."\
			"The Help and Support Manual for Linux Lite."\
		|| {
			DoSay "Calling APT to remove the lite-manual package."
			RemPKG lite-manual
		}
	fi

	if PathLook lite-sources; then
		Prompt\
			"[4142]: Will you need the Lite Sources program? (Enter 'Y' if unsure)"\
			"If you enter 'N', the lite-sources package will be removed."\
			"A country repository source selector for Linux Lite."\
		|| {
			DoSay "Calling APT to remove the lite-sources package."
			RemPKG lite-sources
		}
	fi

	if FindPKG lite-themes; then
		Prompt\
			"[4539]: Do you want the included themes for Linux Lite? (Enter 'Y' if unsure)"\
			"If you enter 'N', the lite-themes package will be removed."\
			"Various themes for Linux Lite."\
		|| {
			DoSay "Calling APT to remove the lite-themes package."
			RemPKG lite-themes
		}
	fi
fi

if FindPKG user-setup; then
	Prompt\
		"[3568]: Will you need the user-setup package (Enter 'Y' if unsure)?"\
		"If you enter 'N', the user-setup package will be removed."\
		"The user-setup package creates an initial user and password."\
	|| {
		DoSay "Calling APT to remove the user-setup package."
		RemPKG user-setup
	}
fi

if FindPKG xserver-xorg-video-amdgpu\*; then
	Prompt\
		"[4181]: Will you be using AMD graphics? (Enter 'Y' if unsure)"\
		"If you enter 'N', xserver-xorg-video-amdgpu package(s) will be removed."\
		"The AMDGPU display driver."\
	|| {
		DoSay "Calling APT to remove various AMDGPU-related packages."
		RemPKG xserver-xorg-video-amdgpu\*
	}
fi

if FindPKG xserver-xorg-video-nouveau\*; then
	Prompt\
		"[1608]: Will you be using nVidia graphics? (Enter 'Y' if unsure)"\
		"If you enter 'N', xserver-xorg-video-nouveau package(s) will be removed."\
		"The Nouveau display driver."\
	|| {
		DoSay "Calling APT to remove various Nouveau-related packages."
		RemPKG xserver-xorg-video-nouveau\*
	}
fi

if FindPKG xserver-xorg-video-intel\*; then
	Prompt\
		"[4425]: Will you be using Intel graphics? (Enter 'Y' if unsure)"\
		"If you enter 'N', xserver-xorg-video-intel package(s) will be removed."\
		"The Intel i8xx and i9xx display driver."\
	|| {
		DoSay "Calling APT to remove various graphics Intel-related packages."
		RemPKG xserver-xorg-video-intel\*
	}
fi

Prompt\
	"[5644]: Is this installation of Linux running inside a virtual machine?"\
	"If you enter 'Y', questions related to such a scenario may be asked."\
	"If the term is unfamiliar, consider software like VirtualBox and VMWare."\
|| {
	if FindPKG virtualbox-guest\*; then
		DoSay "Calling APT to remove VirtualBox guest packages."
		RemPKG virtualbox-guest\*
	fi

	if FindPKG \*vmware\* \*-vmmouse\* python-libvmdk libvmdk\* open-vm-tools\*; then
		DoSay "Calling APT to remove VMWare packages."
		RemPKG \*vmware\* \*-vmmouse\* python-libvmdk libvmdk\* open-vm-tools\*
	fi

	if FindPKG xserver-xorg-video-qxl; then
		DoSay "Calling APT to remove the xserver-xorg-video-qxl package."
		RemPKG xserver-xorg-video-qxl
	fi
}

if FindPKG \*brltty\* \*brlapi\*; then
	Prompt\
		"[7544]: Do you need braille support?"\
		"If you enter 'N', various packages related to braille will be removed."\
		"Braille support is for those whom are blind or have limited vision."\
	|| {
		DoSay "Calling APT to remove braille packages."
		RemPKG \*brltty\* \*brlapi\*
	}
fi

if [[ $IsCinnamon == true ]]; then
	if PathLook file-roller; then
		Prompt\
			"[3065]: Will you need Archive Manager (file-roller)?"\
			"If you enter 'N', file-roller packages will be removed."\
			"If you manage archives elsewhere, then you won't need this."\
		|| {
			DoSay "Calling APT to remove yelp and related packages."
			RemPKG nemo-fileroller file-roller
		}
	fi
else
	if [[ ! $IsZorin == true ]] && PathLook yelp; then
		Prompt\
			"[5678]: Will you need yelp support (Enter 'Y' if unsure)?"\
			"If you enter 'N', yelp and related packages will be removed."\
			"Quite a lot of packages depend on yelp being available."\
		|| {
			DoSay "Calling APT to remove yelp and related packages."
			RemPKG yelp\*
		}
	fi
fi

if PathLook redshift; then
	Prompt\
		"[3610]: Will you ever need redshift (blue light filter)?"\
		"If you enter 'N', the redshift packages will be removed."\
		"Protect your eyes at the appropriate times of day."\
	|| {
		DoSay "Calling APT to remove the redshift packages."
		RemPKG \*redshift\*
	}
fi

if FindPKG xcursor-themes; then
	Prompt\
		"[0157]: Will you use the base X cursor themes? (Enter 'Y' if unsure)"\
		"If you enter 'N', the xcursor-themes package(s) will be removed."\
		"The non-essential, additional base X cursor themes."\
	|| {
		DoSay "Calling APT to remove the xcursor-themes package(s)."
		RemPKG xcursor-themes
	}
fi

if [[ ! $IsCinnamon == true ]] && PathLook inxi; then
	Prompt\
		"[9947]: Will you be needing inxi (CLI system information tool)?"\
		"If you enter 'N', the inxi package will be removed."\
	|| {
		Prompt\
			"[7117]: Inxi is useful on support forums. Are you sure?"\
			"If you enter 'Y', the inxi package will still be removed."\
		&& {
			DoSay "Calling APT to remove the inxi package."
			RemPKG inxi
		}
	}
fi

if PathLook libreoffice; then
	Prompt\
		"[6595]: Do you need the LibreOffice suite?"\
		"If you enter 'N', LibreOffice will be removed."\
		"LibreOffice is an office productivity suite."\
	|| {
		DoSay "Calling APT to remove all LibreOffice packages."
		RemPKG \*libreoffice\* ure mythes-\* libmythes\*
	}
fi

if PathLook nano; then
	Prompt\
		"[2633]: Do you need the terminal text editor, nano?"\
		"If you enter 'N', this text editor will be removed."\
	|| {
		DoSay "Calling APT to remove all nano packages."
		RemPKG nano
	}
fi

if PathLook xterm; then
	Prompt\
		"[0125]: Do you need the fallback xterm virtual terminal emulator?"\
		"If you enter 'N', xterm will be removed. Be sure to have another VTE!"\
		"This is usually not needed, but it can be handy to keep around."\
	|| {
		DoSay "Calling APT to remove all xterm packages."
		RemPKG xterm
	}
fi

if FindPKG friendly-recovery; then
	Prompt\
		"[2107]: Will you need a friendlier recovery mode? (Enter 'Y' if unsure)"\
		"If you enter 'N', friendly-recovery package(s) will be removed."\
		"Make the recovery mode (accessible via the bootloader) more user-friendly."\
	|| {
		DoSay "Calling APT to remove friendly-recovery package(s)."
		RemPKG friendly-recovery
	}
fi

if FindPKG dmraid; then
	Prompt\
		"[7814]: Do you need the dmraid package? (Enter 'Y' if unsure)"\
		"If you enter 'N', the dmraid package will be removed."\
		"Device-Mapper Software RAID support tool."\
	|| {
		DoSay "Calling APT to remove the dmraid package."
		RemPKG dmraid
	}
fi

if FindPKG ntp ntp-doc ntpdate ntpstat ; then
	Prompt\
		"[3357]: Will you need NTP support? (Enter 'Y' if unsure)"\
		"If you enter 'N', ntp and related packages will be removed."\
		"Network Time Protocol daemon and utility programs."\
	|| {
		DoSay "Calling APT to remove the ntp package."
		RemPKG ntp ntp-doc ntpdate ntpstat
	}
fi

if [[ $IsMint == true ]]; then
	if FindPKG cups cups-filters\* cups-server\* cups-core-drivers\
		printer-driver-\* system-config-printer\* libgutenprint2\
		foomatic-db-compressed-ppds; then
		Prompt\
			"[5130]: Will you be using a printer with this Linux installation?"\
			"If you enter 'N', printer drivers will be removed."\
			"Mint comes with a lot of printer packages; do you need them?"\
		|| {
			DoSay "Calling APT to remove all printer driver packages."
			RemPKG cups cups-filters\* cups-server\* cups-core-drivers\
				printer-driver-\* system-config-printer\*\
				libgutenprint2 foomatic-db-compressed-ppds
		}
	fi
elif [[ $IsZorin == true ]]; then
	if FindPKG cups; then
		Prompt\
			"[0919]: Will you be using a printer with this Linux installation?"\
			"If you enter 'N', CUPS and some dependencies will be removed."\
			"Removing printer-related packages on Zorin might not be desired."\
		|| {
			DoSay "Calling APT to remove various printer packages."
			RemPKG cups
		}
	fi
elif [[ $IsUbuntu == true ]]; then
	if FindPKG printer-driver-\* cups\* system-config-printer\*\
		ippusbxd libgutenprint2 foomatic-db-compressed-ppds\
		python3-cupshelpers openprinting-ppds; then
		Prompt\
			"[4994]: Will you be using a printer with this Linux installation?"\
			"If you enter 'N', CUPS and printer drivers will be removed."\
			"Ubuntu comes with a lot of printer packages; do you need them?"\
		|| {
			DoSay "Calling APT to remove all printer packages."
			RemPKG printer-driver-\* cups\* system-config-printer\*\
				ippusbxd libgutenprint2 python3-cupshelpers\
				foomatic-db-compressed-ppds openprinting-ppds
		}
	fi
fi

if FindPKG libfakeroot fakeroot; then
	Prompt\
		"[2041]: Will you need fakeroot (Enter 'Y' if unsure)?"\
		"If you enter 'N', fakeroot and related packages will be removed."\
		"Most will surely not need this."\
	|| {
		DoSay "Calling APT to remove the hdparm package."
		RemPKG {lib,}fakeroot
	}
fi

if [[ ! $IsZorin == true ]] && PathLook hdparm; then
	Prompt\
		"[5102]: Will you need hdparm (get/set SATA/IDE device parameters)?"\
		"If you enter 'N', the hdparm package will be removed."\
		"You likely won't need this. Watch for unexpected dependencies."\
	|| {
		DoSay "Calling APT to remove the hdparm package."
		RemPKG hdparm
	}
fi

if ! [[ $IsZorin == true ]]; then
	if FindPKG simple-scan libsane\* colord\*; then
		Prompt\
			"[2722]: Will you be using a scanner with this Linux installation?"\
			"If you enter 'N', simple-scan and colord will be removed."\
			"This still applies if you want to use a printer/scanner combo."\
		|| {
			DoSay "Calling APT to remove all scanner packages."
			RemPKG simple-scan libsane\* colord\*
		}
	fi
fi

if ! [[ $IgnoreFonts == true ]]; then
	if FindPKG xfonts-thai\* fonts{-tlwg\*,-thai\*}; then
		Prompt\
			"[5788]: Will you need any Thai fonts?"\
			"If you enter 'N', all Thai fonts will be removed."\
			"There may be many. Watch for dependencies."\
		|| {
			DoSay "Calling APT to remove all Thai fonts."
			RemPKG xfonts-thai\* fonts{-tlwg\*,-thai\*}
		}
	fi

	if FindPKG fonts-{arphic-\*,wqy-zenhei,cns11643\*,moe-standard-\*}\
		fonts-moe-standard-song xfonts-intl-chinese\*; then
		Prompt\
			"[5288]: Will you need any Chinese fonts?"\
			"If you enter 'N', all Chinese fonts will be removed."\
			"There may be many. Watch for dependencies."\
		|| {
			DoSay "Calling APT to remove all Chinese fonts."
			RemPKG fonts-{arphic-\*,wqy-zenhei,cns11643\*,moe-standard-\*}\
				fonts-moe-standard-song xfonts-intl-chinese\*
		}
	fi

	if FindPKG fonts-takao-\* fonts-{aoyagi-\*,dejima-mincho,hanazono,horai-umefont}\
		fonts-{ipafont\*,kiloji,kouzan-mouhitsu,migmix,misaki}\
		fonts-mona{,po} fonts-{motoya-l-\*,sawarabi-\*,takao}\
		fonts-{umeplus,yozvox-yozfont\*} latex-cjk-japanese-wadalab\
		xfonts-{ayu,intl-japanese\*,jisx0213,kaname,kappa20,mplus}\
		xfonts-shinonome fonts-{ipaexfont\*,ipafont-nonfree-\*}\
		xfonts-naga10 fonts-{mikachan,ipamj-mincho,seto,vlgothic}; then
		Prompt\
			"[1298]: Will you need any Japanese fonts?"\
			"If you enter 'N', all Japanese fonts will be removed."\
			"There may be many. Watch for dependencies."\
		|| {
			DoSay "Calling APT to remove all Japanese fonts."
			RemPKG fonts-takao-\*\
				fonts-{aoyagi-\*,dejima-mincho,hanazono,horai-umefont}\
				fonts-{ipafont\*,kiloji,kouzan-mouhitsu,migmix,misaki}\
				fonts-mona{,po} fonts-{motoya-l-\*,sawarabi-\*,takao}\
				fonts-{umeplus,yozvox-yozfont\*} latex-cjk-japanese-wadalab\
				xfonts-{ayu,intl-japanese\*,jisx0213,kaname,kappa20,mplus}\
				xfonts-shinonome fonts-{ipaexfont\*,ipafont-nonfree-\*}\
				xfonts-naga10 fonts-{mikachan,ipamj-mincho,seto,vlgothic}
		}
	fi

	if FindPKG ttf-mscorefonts-installer; then
		Prompt\
			"[4426]: Will you ever need Microsoft TrueType core fonts?"\
			"If you enter 'N', all Microsoft TrueType core fonts will be removed."\
			"These are non-free, and usually not pre-installed."\
		|| {
			DoSay "Calling APT to remove Kate packages."
			RemPKG ttf-mscorefonts-installer
		}
	fi

	if FindPKG \*-cyrillic fonts-sil\*; then
		Prompt\
			"[0770]: Will you ever need SIL font support for minority languages?"\
			"If you enter 'N', all SIL fonts will be removed."\
			"There may be many. Watch for dependencies."\
		|| {
			DoSay "Calling APT to remove SIL font packages."
			RemPKG \*-cyrillic fonts-sil\*
		}
	fi
fi

if PathLook gufw; then
	Prompt\
		"[4419]: Will you need the GUI fontend to the Uncomplicated Firewall?"\
		"If you enter 'N', you'll be left with CLI version of the UFW."\
		"The CLI version can suffice, depending on your needs."\
	|| {
		DoSay "Calling APT to remove gufw package(s)."
		RemPKG gufw
	}
fi

for BIN in transmission-{gtk,qt,cli}; {
	if PathLook "$BIN"; then
		Transmission='true'
		break
	fi
}

if [[ $Transmission == true ]]; then
	Prompt\
		"[5371]: Will you ever be using torrents with Transmission?"\
		"If you enter 'N', transmission packages will be removed."\
		"Transmission allows you to download files via torrents."\
	|| {
		DoSay "Calling APT to remove all Transmission packages."
		RemPKG transmission\*
	}
fi

if PathLook hexchat; then
	Prompt\
		"[0123]: Will you ever be using Hexchat (IRC client)?"\
		"If you enter 'N', Hexchat will be removed."\
		"With IRC, your Internet IP address will usually be public!"\
	|| {
		DoSay "Calling APT to remove all Transmission packages."
		RemPKG hexchat\*
	}
fi

if PathLook gimp; then
	Prompt\
		"[1808]: Will you ever use the GNU Image Manipulation Program?"\
		"If you enter 'N', GIMP packages will be removed."\
		"Think Photoshop, but it's FOSS."\
	|| {
		DoSay "Calling APT to remove all GIMP packages."
		RemPKG gimp\*
	}
fi

if PathLook pidgin; then
	Prompt\
		"[9373]: Will you ever use pidgin (IM client)?"\
		"If you enter 'N', pidgin packages will be removed."\
		"Graphical multi-protocol instant messaging client."\
	|| {
		DoSay "Calling APT to remove all pidgin packages."
		RemPKG indicator-status-provider-pidgin pidgin\*
	}
fi

if FindPKG samba{,-common} cifs-utils\* lupin-\* smbclient casper\*; then
	Prompt\
		"[8496]: Will you ever need Samba (Enter 'Y' if unsure)?"\
		"If you enter 'N', SMB packages will be removed, where possible."\
		"SMB/CIFS file, print, and login server for Linux."\
	|| {
		DoSay "Calling APT to remove Samba packages."
		RemPKG samba{,-common} cifs-utils\* lupin-\* smbclient casper\*

		NoSamba='true'
	}
fi

if FindPKG command-not-found; then
	Prompt\
		"[7890]: Will you need command-not-found (Enter 'Y' if unsure)?"\
		"If you enter 'N', command-not-found package(s) will be removed."\
		"A sometimes useful terminal feature, but arguable pointless."\
	|| {
		DoSay "Calling APT to remove the command-not-found package."
		RemPKG command-not-found

		if FindPKG python3-commandnotfound && ! [[ $IsMint == true ]]; then
			DoSay "Calling APT to remove the python3-commandnotfound package."
			RemPKG python3-commandnotfound
		fi
	}
fi

if PathLook flatpak; then
	Prompt\
		"[9989]: Will you need flatpak (Enter 'Y' if unsure)?"\
		"If you enter 'Y', flatpak packages will be removed."\
		"Flatpak is a new framework for applications on Linux."\
	|| {
		DoSay "Calling APT to remove flatpak packages."
		RemPKG \*flatpak\*
	}
fi

if [[ ! $IsMint == true ]] && PathLook synaptic; then
	Prompt\
		"[1768]: Will you only perform APT package changes via terminals?"\
		"If you enter 'Y', the Synaptic Package Manager will be removed."\
		"Suitable for more experienced users, but not at all necessary."\
	&& {
		DoSay "Calling APT to remove all synaptic packages."
		RemPKG synaptic
	}
fi

if ! [[ $IsZorin == true ]]; then
	if FindPKG broadcom-sta-\* atmel-firmware wireless-crda wmwave linssid\
		plasma-widget-wifi wavemon wpasupplicant rfkill; then
		Prompt\
			"[6441]: Will you ever need support for wireless networking?"\
			"If you enter 'N', various wireless packages will be removed."\
			"You likely won't need any of these, if you don't use wireless."\
		|| {
			DoSay "Calling APT to remove wireless packages."
			RemPKG broadcom-sta-\* atmel-firmware wireless-crda wmwave linssid\
				plasma-widget-wifi wavemon rfkill

			if ! [[ $IsCinnamon == true ]]; then
				RemPKG wpasupplicant
			fi
		}
	fi
fi

if FindPKG xboxdrv; then
	Prompt\
		"[6070]: Will you ever need support for an XBOX 360 controller?"\
		"If you enter 'N', the xboxdrv package will be removed."\
		"This driver enables the use of such a controller in Linux."\
	|| {
		DoSay "Calling APT to remove XBOX 360 controller packages."
		RemPKG xboxdrv
	}
fi

if FindPKG openvpn network-manager-{openvpn,openvpn-gnome}; then
	Prompt\
		"[2473]: Will you ever need OpenVPN (Enter 'N' if unsure?"\
		"If you enter 'N', openvpn and related packages will be removed."\
		"Virtual private network daemon."\
	|| {
		DoSay "Calling APT to remove openvpn and related packages."
		RemPKG openvpn
	}
fi

if FindPKG wmbattery whereami urfkill pommed hdapsd fnfxd xbattbar ibam\
	radeontool toshset armada-backlight i8kutils fdpowermon\
	bat{mon.app,tery-stats} claws-mail-acpi-notifier gkrellm\*\
	laptop-{detect,mode-tools} power{stat,top\*} xserver-xorg-input-wacom; then
	Prompt\
		"[9802]: Is this machine a laptop or similar portable device?"\
		"If you enter 'N', various packages for such devices will be removed."\
		"There are many packages here which may potentially be superfluous."\
	|| {
		DoSay "Calling APT to remove packages related to portable devices."
		RemPKG wmbattery whereami urfkill pommed hdapsd fnfxd xbattbar ibam\
			radeontool toshset armada-backlight i8kutils fdpowermon\
			bat{mon.app,tery-stats} claws-mail-acpi-notifier gkrellm\*\
			laptop-{detect,mode-tools} power{stat,top\*}\
			xserver-xorg-input-wacom

		NO_PORTABLE='true'
	}
fi

if FindPKG ubuntu-{touch\*,application-api3-touch} x11-touchscreen-calibrator\
	libfile-touch-perl autopilot-touch\*; then
	Prompt\
		"[2918]: Is this machine a touch device?"\
		"If you enter 'N', various packages for such devices will be removed."\
		"Unless your device is touch-capable, these packages aren't needed."\
	|| {
		DoSay "Calling APT to remove touch-related packages."
		RemPKG ubuntu-{touch\*,application-api3-touch} x11-touchscreen-calibrator\
			libfile-touch-perl autopilot-touch\*
	}
fi

if FindPKG xserver-xorg-input-synaptics\*; then
	Prompt\
		"[3242]: Do you need support for devices with a touchpad?"\
		"If you enter 'N', various packages for such devices will be removed."\
		"Applies whether on a laptop or integrated into a regular keyboard."\
	|| {
		DoSay "Calling APT to remove touchpad-related packages."
		RemPKG xserver-xorg-input-synaptics\*

		NoTouchpad='true'
	}
fi

if ! [[ $NoAskDE == true ]]; then
	Prompt\
		"[0204]: Are you using the KDE desktop environment?"\
		"If you enter 'Y', you'll be asked KDE-specific questions."\
	&& {
		if FindPKG kubuntu-driver-manager\*; then
			Prompt\
				"[7976]: Will you ever need the KDE driver manager (GUI)?"\
				"If you enter 'N', the KDE driver manager will be removed."\
			|| {
				DoSay "Calling APT to remove the KDE driver manager."
				RemPKG kubuntu-driver-manager\*
			}
		fi

		if PathLook kate; then
			Prompt\
				"[8952]: Will you ever need KDE's Kate (powerful text editor)?"\
				"If you enter 'N', the KDE Advanced Text Editor will be removed."\
			|| {
				DoSay "Calling APT to remove Kate packages."
				RemPKG kate\* libkate\*
			}
		fi

		if PathLook partitionmanager; then
			Prompt\
				"[1223]: Will you ever need KDE's Partition Manager?"\
				"If you enter 'N', the partitionmanager package will be removed."\
			|| {
				DoSay "Calling APT to remove partitionmanager packages."
				RemPKG partitionmanager
			}
		fi

		if [[ $NoSamba == true ]]; then
			DoSay "Calling APT to remove smb4k package (Samba-related)."
			RemPKG smb4k
		fi

		if [[ $NoTouchpad == true ]]; then
			DoSay "Calling APT to remove KDE packages related to touchpads."
			RemPKG kde-{config-touchpad,touchpad}
		fi

		if PathLook kgrab; then
			Prompt "[0136]: Will you ever use kgrab (screenshot utility)?" || {
				DoSay "Calling APT to remove the kgrab package."
				RemPKG kgrab
			}
		fi
	}

	Prompt\
		"[2816]: Are you using the XFCE desktop environment?"\
		"If you enter 'Y', you'll be asked XFCE-specific questions."\
	&& {
		if PathLook xfdesktop4\*; then
			Prompt\
				"[1273]: Will you be needing xfdesktop4 (XFCE desktop manager)?"\
				"This is responsible for things like your desktop icons and background."\
			|| {
				DoSay "Calling APT to remove xfdesktop packages."
				RemPKG xfdesktop\*
			}
		fi

		if PathLook xfburn; then
			Prompt\
				"[8300]: Will you need to burn CDs or DVDs? (Enter 'N' if unsure)"\
				"If you enter 'N', xfburn and related packages will be removed."\
				"CD-burner application for the XFCE Desktop Environment."\
			|| {
				DoSay "Calling APT to remove xfburn and related packages."
				RemPKG xfburn
			}
		fi

		if PathLook thunar; then
			Prompt\
				"[3903]: Will you be needing Thunar (XFCE file manager)?"\
				"If you enter 'N', Thunar and related packages will be removed."\
			|| {
				DoSay "Calling APT to remove Thunar packages."
				RemPKG thunar\*
			}
		fi

		if PathLook xfce4-screenshooter; then
			Prompt "[0200]: Will you need xfce4-screenshooter (screenshot utility)?" || {
				DoSay "Calling APT to remove the xfce4-screenshooter package."
				RemPKG xfce4-screenshooter\*
			}
		fi
	}

	Prompt\
		"[5392]: Are you using the Mate desktop environment?"\
		"If you enter 'Y', you'll be asked Mate-specific questions."\
	&& {
		IsMate='true'

		if PathLook pluma; then
			Prompt "[6967]: Will you ever use Pluma (text editor)?" || {
				DoSay "Calling APT to remove Pluma packages."
				RemPKG pluma\*
			}
		fi
	}

	Prompt\
		"[5766]: Are you using the GNOME desktop environment?"\
		"If you enter 'Y', you'll be asked Gnome-specific questions."\
	&& {
		IsGNOME='true'

		if PathLook clementine; then
			Prompt "[0595]: Will you ever use Clementine (GUI music player)?" || {
				DoSay "Calling APT to remove Clementine packages."
				RemPKG clementine unity-scope-clementine
			}
		fi

		if FindPKG mouse-tweaks; then
			Prompt "[6403]: Will you ever use mouse-tweaks package (Enter 'Y' if unsure)?" || {
				DoSay "Calling APT to remove the mouse-tweaks package."
				RemPKG mouse-tweaks
			}
		fi
	}
fi

Prompt "[1883]: Will you ever need any penetration testing tools?" || {
	if PathLook nmap; then
		Prompt "[2558]: Will you ever use nmap (The Network Mapper)?" || {
			DoSay "Calling APT to remove nmap package."
			RemPKG nmap\* zenmap umit python{3-nmap,-nmap}\
				libnmap-parser-perl
		}
	fi
}

if PathLook testdisk || PathLook photorec; then
	Prompt "[1386]: Will you ever need TestDisk and/or PhotoRec (data recovery)?" || {
		DoSay "Calling APT to remove XBOX 360 controller packages."
		RemPKG testdisk\*
	}
fi

if FindPKG nvidia\*; then
	Prompt "[1564]: Will you need any nVidia packages (excluding nouveau)?" || {
		DoSay "Calling APT to remove any nVidia packages."
		RemPKG nvidia\*
	}
fi

if FindPKG xserver-xorg-video-radeon\* radeon\*; then
	Prompt "[6338]: Will you need any AMD Radeon packages (excluding amdgpu)?" || {
		DoSay "Calling APT to remove any AMD Radeon packages."
		RemPKG xserver-xorg-video-radeon\* radeon\*
	}
fi

if PathLook curl; then
	Prompt "[7315]: Will you ever need cURL (CLI downloader)?" || {
		DoSay "Calling APT to remove cURL packages."
		RemPKG curl
	}
fi

if PathLook sudo; then
	Prompt "[3703]: Will you be needing sudo? (Enter 'Y' if unsure)" || {
		Prompt "[7417]: Are you sure? Only experienced users should say yes." && {
			DoSay "Calling APT to remove sudo."
			RemPKG sudo
		}
	}
fi

if ! [[ $IsZorin == true ]]; then
	if FindPKG ssh-askpass-gnome openssh-server ssh python-paramiko; then
		Prompt\
			"[9627]: Is this installation an SSH server (Enter 'Y' if unsure)?"\
			"If you enter 'Y', non-required SSH packages will be removed."\
		|| {
			DoSay "Calling APT to remove non-required SSH packages."
			RemPKG ssh-askpass-gnome openssh-server ssh python-paramiko
		}
	fi
fi

if PathLook rhythmbox; then
	Prompt "[1893]: Will you ever use RhythmBox (GUI music player)?" || {
		DoSay "Calling APT to remove RhythmBox packages."
		RemPKG rhythmbox\*
	}
fi

if PathLook gparted; then
	Prompt "[8257]: Will you be needing gparted (partition manager)?" || {
		DoSay "Calling APT to remove gparted packages."
		RemPKG gparted
	}
fi

if PathLook thunderbird; then
	Prompt\
		"[1034]: Will you be needing Thunderbird (E-Mail client)?"\
		"If you enter 'N', Thunderbird packages will be removed."\
	|| {
		DoSay "Calling APT to remove Thunderbird packages."
		RemPKG thunderbird\*
	}
fi

if PathLook tomboy; then
	Prompt\
		"[0455]: Will you be needing Tomboy (note taking)?"\
		"If you enter 'N', Tomboy packages will be removed."\
	|| {
		DoSay "Calling APT to remove Tomboy packages."
		RemPKG tomboy\* unity-scope-tomboy
	}
fi

if [[ $IsMint == true ]]; then
	if PathLook timeshift; then
		Prompt\
			"[6069]: Will you be needing timeshift (backup utility)?"\
			"If you enter 'N', timeshift will be removed."\
		|| {
			DoSay "Calling APT to remove the timeshift package."
			RemPKG timeshift
		}
	fi
fi

if FindPKG xscreensaver\* gnome-{screensaver,screensaver}; then
	Prompt\
		"[6639]: Will you be needing support for screensavers?"\
		"If you enter 'N', screensaver packages will be removed."\
	|| {
		DoSay "Calling APT to remove packages related to screensavers."

		if [[ $IsGNOME == true ]]; then
			RemPKG gnome-screensaver
		elif [[ $IsMate == true ]]; then
			RemPKG mate-screensaver\*
		fi

		RemPKG xscreensaver\*
	}
fi

if PathLook udisksctl; then
	Prompt\
		"[0445]: Will you be needing udisks2 (Enter 'Y' if unsure)?"\
		"If you enter 'N', udisks2 and related packages will be removed."\
	|| {
		DoSay "Calling APT to remove udisks2 and related packages."
		RemPKG udisks2\* libudisks2-\* gir1.2-udisks-2.0
	}
fi

if PathLook duplicity; then
	Prompt\
		"[8690]: Will you be needing Duplicity (backup utility)?"\
		"If you enter 'N', the Duplicity package will be removed."\
	|| {
		DoSay "Calling APT to remove the Duplicity package."
		RemPKG duplicity
	}
fi

if PathLook gdebi; then
	Prompt\
		"[6274]: Will you be needing gdebi (GUI deb installer)?"\
		"If you enter 'N', gdebi and related packages will be removed."\
	|| {
		DoSay "Calling APT to remove gdebi and related packages."
		RemPKG gdebi\*
	}
fi

if FindPKG mobile-broadband-provider-info; then
	Prompt\
		"[2773]: Will you be needing support for mobile broadband?"\
		"If you enter 'N', the mobile-broadband-provider-info package will be removed."\
	|| {
		DoSay "Calling APT to remove the mobile-broadband-provider-info package."
		RemPKG mobile-broadband-provider-info
	}
fi

if ! [[ $IsZorin == true ]]; then
	if FindPKG \*bluetooth\* \*bluez\* ubertooth libubertooth\*; then
		Prompt\
			"[5628]: Do you need bluetooth support?"\
			"If you enter 'N', various bluetooth packages will be removed."\
			"Either via external or internal bluetooth receivers."\
		|| {
			if [[ $IsMint == true ]]; then
				Prompt\
					"[6689]: Are you using the Cinnamon desktop environment?"\
					"If you enter 'Y', fewer bluetooth packages will be removed."\
					"This question may affect later questions."\
				&& {
					IsCinnamon='true'

					DoSay "Calling APT to remove some bluetooth packages."
					RemPKG blue{tooth,z\*,berry} {gnome,pulseaudio-module}-bluetooth
				}
			else
				DoSay "Calling APT to remove bluetooth packages."
				RemPKG \*bluetooth\* \*bluez\* ubertooth libubertooth\*
			fi
		}
	fi

	if PathLook gnome-disks; then
		Prompt\
			"[4037]: Will you ever use gnome-disk-utility (AKA: Disks)?"\
			"If you enter 'N', gnome-disk-utility package(s) will be removed."\
			"Manage and configure disk drives and media via GUI."\
		|| {
			DoSay "Calling APT to remove gnome-disk-utility packages."
			RemPKG gnome-disk-utility
		}
	fi

	if PathLook evince; then
		Prompt\
			"[2489]: Will you be needing Evince (document viewer)?"\
			"If you enter 'N', Evince packages will be removed."\
			"Simple, multi-page document (PostScript, PDF) viewer."\
		|| {
			DoSay "Calling APT to remove Evince packages."
			RemPKG evince\*
		}
	fi

	if PathLook lshw; then
		Prompt\
			"[5430]: Will you be needing lshw (CLI system information tool)?"\
			"If you enter 'N', the lshw package will be removed."\
		|| {
			DoSay "Calling APT to remove the lshw package."
			RemPKG lshw
		}
	fi

	if FindPKG libdiscover2 discover; then
		Prompt\
			"[3155]: Will you be using discover? (Enter 'Y' if unsure)"\
			"If you enter 'N', discover packages will be removed."\
			"Hardware identification system based on the libdiscover2 library."\
		|| {
			DoSay "Calling APT to remove aptitude and related packages."
			RemPKG libdiscover2 discover
		}
	fi

	if PathLook rsync; then
		Prompt\
			"[6398]: Will you be needing rsync (file transfer)?"\
			"If you enter 'N', the rsync package will be removed."\
			"Fast, versatile, remote (and local) CLI file-copying tool."\
		|| {
			DoSay "Calling APT to remove the rsync package."
			RemPKG rsync
		}
	fi

	if FindPKG memtest86\*; then
		Prompt\
			"[6678]: Will you be needing memtest86+ (Enter 'Y' if unsure)?"\
			"If you enter 'N', the memtest86+ package will be removed."\
			"OS-independent, thorough real-mode memory (RAM) tester."\
		|| {
			DoSay "Calling APT to remove the memtest86+ package."
			RemPKG memtest86\*
		}
	fi

	if PathLook vino-preferences; then
		NoVino='true'

		Prompt\
			"[1424]: Will you be needing VINO (remote desktop client)?"\
			"If you enter 'N', the VINO package will be removed."\
		|| {
			DoSay "Calling APT to remove the VINO package."
			RemPKG vino
		}
	fi

	if FindPKG gvfs\*; then
		Prompt "[4890]: Will you be needing gvfs (Enter 'Y' if unsure)?" || {
			NoGVFS='true'

			DoSay "Calling APT to remove gvfs packages."
			RemPKG gvfs\*
		}
	fi

	if FindPKG dvd\+rw-tools libcdparanoia0 cd-discid libcdio\* wodim libdvd\* libcdr\*; then
		Prompt\
			"[9968]: Will you need support for optical media (such as CDs and DVDs)?"\
			"If you enter 'N', packages related to optical media will be removed."\
		|| {
			DoSay "Calling APT to remove packages related to optical media."
			RemPKG wodim libdvd\* libcdr\* cd-discid
		}

		if [[ $NoGVFS == true ]]; then
			RemPKG libcdio\*
		fi

		PathLook nemo && RemPKG libcdparanoia0

		if FindPKG dvd\+rw-tools; then
			Prompt\
				"[6854]: Will you need the dvd+rw-tools package (Enter 'Y' if unsure)?"\
				"If you enter 'N', the dvd+rw-tools package will be removed."\
			|| {
				NoDVDRWTools='true'

				DoSay "Calling APT to remove the dvd+rw-tools package."
				RemPKG dvd\+rw-tools
			}
		fi
	fi

	if [[ ! $NoDVDRWTools == true ]] && PathLook genisoimage; then
		Prompt\
			"[0323]: Will you be needing genisoimage (ISO file creator)?"\
			"If you enter 'N', the genisoimage package will be removed."\
		|| {
			DoSay "Calling APT to remove the genisoimage package."
			RemPKG genisoimage
		}
	fi

	if PathLook brasero; then
		DoSay "Calling APT to remove Brasero packages."
		RemPKG brasero
	fi

	if ! [[ $IsCinnamon == true ]]; then
		if PathLook gksu gksudo; then
			Prompt\
				"[1001]: Will you need gksu and/or gksudo (Enter 'Y' if unsure)?"\
				"If you enter 'N', the gksu package will be removed."\
			|| {
				DoSay "Calling APT to remove the gksu package."
				RemPKG gksu
			}
		fi
	fi
fi

if PathLook baobab; then
	Prompt\
		"[9826]: Will you need to use baobab? (GNOME Disk Usage Analyzer)"\
		"If you enter 'N', the baobab package will be removed."\
	|| {
		DoSay "Calling APT to remove the baobab package."
		RemPKG caribou

		if ! [[ $IsCinnamon == true ]]; then
			RemPKG baobab
		fi
	}
fi

if FindPKG fwupd; then
	Prompt\
		"[8156]: Will you need to update device firmware (Enter 'Y' if unsure)?"\
		"If you enter 'N', the fwupd and related packages will be removed."\
	|| {
		DoSay "Calling APT to remove the fwupd and related packages."
		RemPKG \*fwupd\*
	}
fi

if FindPKG freerdp\* libfreerdp\* dosfstools ntfs-3g libgcab-\*\
	libxfreerdp\* mtools mscompress syslinux\*; then
	Prompt\
		"[7602]: Will you need Windows-related support? (Enter 'Y' if unsure)"\
		"If you enter 'N', additional related questions will be asked."\
	|| NO_MS_TOOLS='true'

	if [[ $NO_MS_TOOLS == true ]]; then
		DoSay "Calling APT to remove the mtools package."
		RemPKG mtools

		DoSay "Calling APT to remove package(s) for CAB archive support."
		RemPKG libgcab-\*

		if FindPKG ntfs-3g; then
			Prompt "[8335]: Will you be needing NTFS support (Enter 'Y' if unsure)?" || {
				DoSay "Calling APT to remove the ntfs-3g package."
				RemPKG ntfs-3g
			}
		fi

		if FindPKG dosfstools; then
			DoSay "Calling APT to remove the dosfstools package."
			RemPKG dosfstools
		fi

		if PathLook xfreerdp; then
			NO_FREERDP='true'

			DoSay "Calling APT to remove the FreeRDP packages."
			RemPKG freerdp\* libfreerdp\* libxfreerdp\*
		fi

		if PathLook mscompress; then
			DoSay "Calling APT to remove the mscompress package."
			RemPKG mscompress
		fi

		if PathLook syslinux; then
			DoSay "Calling APT to remove the syslinux packages."
			RemPKG syslinux\*
		fi
	fi
fi

if [[ $NO_FREERDP == true && $NoVino == true ]]; then
	DoSay "Calling APT to remove the thin-client-config-agent package."
	RemPKG thin-client-config-agent
fi

if FindPKG netpbm; then
	Prompt\
		"[0258]: Will you be needing netpbm (image file converter)?"\
		"If you enter 'N', the netpbm package will be removed."\
		"Toolkit for the manipulation of graphical images."\
	|| {
		DoSay "Calling APT to remove the netpbm package."
		RemPKG netpbm
	}
fi

if PathLook telnet; then
	Prompt\
		"[8328]: Will you be needing telnet (basic telnet client)?"\
		"If you enter 'N', the telnet package will be removed."\
		"Remote communications tool using the TELNET protocol."\
	|| {
		DoSay "Calling APT to remove the telnet package."
		RemPKG telnet
	}
fi

if PathLook rename; then
	Prompt\
		"[6454]: Will you be needing rename (CLI file renamer)?"\
		"If you enter 'N', the rename package will be removed."\
		"Perl extension for renaming multiple files."\
	|| {
		DoSay "Calling APT to remove the rename package."
		RemPKG rename

		# Seems to be a bug in that the executable doesn't get deleted
		# properly. Added a check to give an error, should this be beyond
		# just my case.
		if PathLook rename; then
			Err 0 "The '/usr/bin/rename' executable still exists."
		fi
	}
fi

if PathLook lintian; then
	Prompt\
		"[7782]: Will you be needing lintian (deb package checker)?"\
		"If you enter 'N', the lintian package will be removed."\
		"Dissects DEB packages and reports bugs and policy violations."\
	|| {
		DoSay "Calling APT to remove the lintian package."
		RemPKG lintian
	}
fi

if FindPKG libapt-pkg-perl; then
	Prompt\
		"[8334]: Will you need libapt-pkg-perl (Enter 'Y' if unsure)?"\
		"If you enter 'N', the libapt-pkg-perl package will be removed."\
		"Perl interface to libapt-pkg."\
	|| {
		DoSay "Calling APT to remove the libapt-pkg-perl package."
		RemPKG libapt-pkg-perl
	}
fi

if PathLook i3; then
	if FindPKG libanyevent-i3-perl; then
		Prompt\
			"[6758]: Will you need libanyevent-i3-perl (Enter 'Y' if unsure)?"\
			"If you enter 'N', the libanyevent-i3-perl package will be removed."\
			"Perl module to communicate with the i3 window manager."\
		|| {
			DoSay "Calling APT to remove the libanyevent-i3-perl package."
			RemPKG libanyevent-i3-perl
		}
	fi
fi

if FindPKG libabw-\*; then
	Prompt\
		"[5057]: Will you need to read and/or write AbiWord documents?"\
		"If you enter 'N', the libabw-* packages will be removed."\
		"Library for reading and writing AbiWord(tm) documents."\
	|| {
		DoSay "Calling APT to remove the libabw-* packages."
		RemPKG libabw-\*
	}
fi

if FindPKG libaacs0; then
	Prompt\
		"[6857]: Will you need to read and/or write AACS files?"\
		"If you enter 'N', the libaacs0 package will be removed."\
		"Provides a way to understand how the AACS works."\
	|| {
		DoSay "Calling APT to remove the libaacs0 packages."
		RemPKG libaacs0
	}
fi

if FindPKG pm-utils powermgmt-base; then
	Prompt\
		"[3676]: Will you need extra power management support? (Enter 'Y' if unsure)"\
		"If you enter 'N', the pm-utils and powermgmt-base package will be removed."\
		"Configs, utilities, and scripts for power management, common and otherwise."\
	|| {
		DoSay "Calling APT to remove the pm-utils and powermgmt-base packages."
		RemPKG pm-utils powermgmt-base
	}
fi

if FindPKG lvm2 liblvm\*; then
	Prompt\
		"[2600]: Will you be or are you using LVM? (Enter 'Y' if unsure)"\
		"If you enter 'N', packages related to LVM will be removed."\
		"This is LVM2, the rewrite of The Linux Logical Volume Manager."\
	|| NoLVM='true'

	if [[ $NoLVM == true ]]; then
		Prompt\
			"[7958]: WARNING! May be problematic if you're wrong. Are you sure?"\
			"If you enter 'Y', LVM-related packages will still be removed."\
		&& {
			DoSay "Calling APT to remove the LVM-related packages."
			RemPKG lvm2 liblvm\*
		}
	fi
fi

if FindPKG xul-ext-ubufox; then
	if ! PathLook firefox; then
		DoSay "NOTE: Package xul-ext-ubufox found, but Firefox executable wasn't."
	fi

	Prompt\
		"[1771]: Will you need the xul-ext-ubufox package (Enter 'Y' if unsure)?"\
		"If you enter 'N', the Ubuntu modifications for Firefox will be removed."\
		"Adds Ubuntu-specific modifications to Firefox."\
	|| {
		DoSay "Calling APT to remove the xul-ext-ubufox package."
		RemPKG xul-ext-ubufox
	}
fi

if PathLook zip || PathLook unzip; then
	Prompt\
		"[9529]: Do you need support for zip archives (Enter 'Y' if unsure)?"\
		"If you enter 'N', the zip package will be removed."\
		"Create and extract ZIP files."\
	|| {
		DoSay "Calling APT to remove the zip package."
		RemPKG zip unzip
	}
fi

if PathLook rar; then
	Prompt\
		"[7826]: Do you need support for rar archives (Enter 'Y' if unsure)?"\
		"If you enter 'N', the rar package will be removed."\
		"Create and extract rar files."\
	|| {
		DoSay "Calling APT to remove the rar package."
		RemPKG rar
	}
fi

if PathLook 7zr; then
	Prompt\
		"[2693]: Do you need support for 7zip archives (Enter 'Y' if unsure)?"\
		"If you enter 'N', the p7zip package will be removed."\
		"7z file archiver with a high compression ratio."\
	|| {
		DoSay "Calling APT to remove the p7zip package."
		RemPKG p7zip
	}
fi

if PathLook arj; then
	Prompt\
		"[0572]: Do you need support for arj archives (Enter 'Y' if unsure)?"\
		"If you enter 'N', the arj package will be removed."\
		"This package is an open-source version of the arj archiver."\
	|| {
		DoSay "Calling APT to remove the arj package."
		RemPKG arj
	}
fi

if PathLook xclip; then
	Prompt\
		"[5670]: Do you need xclip (CLI clipboard utility)?"\
		"If you enter 'N', the xclip package will be removed."\
		"Provides an interface to X selections (clipboard)."\
	|| {
		DoSay "Calling APT to remove the xclip package."
		RemPKG xclip
	}
fi

if PathLook apt-offline; then
	Prompt\
		"[9953]: Do you need apt-offline (Enter 'Y' if unsure)?"\
		"If you enter 'N', the apt-offline package will be removed."\
		"Offline APT Package Manager."\
	|| {
		DoSay "Calling APT to remove the apt-offline package."
		RemPKG apt-offline
	}
fi

if PathLook dc; then
	Prompt\
		"[3665]: Do you need dc (Enter 'Y' if unsure)?"\
		"If you enter 'N', the dc package will be removed."\
		"GNU dc arbitrary precision reverse-polish calculator."\
	|| {
		DoSay "Calling APT to remove the dc package."
		RemPKG dc
	}
fi

if PathLook dmidecode; then
	Prompt\
		"[0268]: Do you need dmidecode (Enter 'Y' if unsure)?"\
		"If you enter 'N', the dmidecode package will be removed."\
		"Reports information about hardware, according to the BIOS."\
	|| {
		DoSay "Calling APT to remove the dmidecode package."
		RemPKG dmidecode
	}
fi

if FindPKG evolution-data-server\*; then
	Prompt\
		"[2743]: Do you need any Evolution packages (Enter 'Y' if unsure)?"\
		"If you enter 'N', packages related to Evolution will be removed."\
		"Evolution is an all-purpose suite for mail, memos, to-dos, etc."\
	|| {
		DoSay "Calling APT to remove any packages related to Evolution."
		RemPKG evolution-data-server\*
	}
fi

if FindPKG manpages-dev; then
	Prompt\
		"[0437]: Will you need development manual pages? (Enter 'N' if unsure)"\
		"If you enter 'N', the manpages-dev package will be removed."\
		"This is useful for programmers -- regular users don't need it."\
	|| {
		DoSay "Calling APT to remove the manpages-dev package."
		RemPKG manpages-dev
	}
fi

if FindPKG netcat netcat-openbsd netcat-traditional; then
	Prompt\
		"[1999]: Will you need to use netcat? (Enter 'N' if unsure)"\
		"If you enter 'N', the netcat package(s) will be removed."\
		"The TCP/IP Swiss Army knife, but most likely won't need it."\
	|| {
		DoSay "Calling APT to remove the netcat package(s)."
		RemPKG netcat netcat-openbsd netcat-traditional
	}
fi

if FindPKG caribou; then
	Prompt\
		"[3992]: Will you need to use caribou? (Enter 'Y' if unsure)"\
		"If you enter 'N', the caribou package(s) will be removed."\
		"This is a configurable on-screen keyboard with scanning mode."\
	|| {
		DoSay "Calling APT to remove the caribou package(s)."
		RemPKG caribou

		if ! [[ $IsCinnamon == true ]]; then
			RemPKG \*caribou\*
		fi
	}
fi

if FindPKG ed; then
	Prompt\
		"[8769]: Will you need the ed package? (Enter 'Y' if unsure)"\
		"If you enter 'N', the ed package will be removed."\
		"Classic UNIX line-orientated text editor."\
	|| {
		DoSay "Calling APT to remove the ed package."
		RemPKG ed
	}
fi

if FindPKG fortunes fortunes-\*; then
	Prompt\
		"[1409]: Will you need the fortunes package(s)?"\
		"If you enter 'N', the fortunes package(s) will be removed."\
		"Data files containing (many) fortune cookies."\
	|| {
		DoSay "Calling APT to remove the fortunes package(s)."
		RemPKG fortunes fortunes-\*
	}
fi

if FindPKG ftp; then
	Prompt\
		"[2080]: Will you need the ftp package? (Enter 'Y' if unsure)"\
		"If you enter 'N', the ftp package will be removed."\
		"User interface to the ARPANET standard File Transfer Protocol."\
	|| {
		DoSay "Calling APT to remove the ftp package."
		RemPKG ftp
	}
fi

if ! [[ $IsCinnamon == true ]]; then
	if FindPKG dpkg-dev; then
		Prompt\
			"[7031]: Will you need tools to build DEB packages from source?"\
			"If you enter 'N', dpkg-dev and related packages will be removed."\
			"Debian package development tools."\
		|| {
			DoSay "Calling APT to remove dpkg-dev and related packages."
			RemPKG dpkg-dev
		}
	fi

	if FindPKG gettext; then
		Prompt\
			"[0809]: Will you need the gettext packages (Enter 'Y' if unsure)?"\
			"If you enter 'N', gettext and related packages will be removed."\
		|| {
			DoSay "Calling APT to remove gettext and related packages."
			RemPKG gettext
		}
	fi

	if FindPKG gdb gdbserver; then
		Prompt\
			"[3509]: Will you be needing gdb and related packages?"\
			"If you enter 'N', the gdb package(s) will be removed."\
			"GNU Debugger. A must-have for any serious programmer."\
		|| {
			DoSay "Calling APT to remove the gdb package(s)."
			RemPKG gdb gdbserver
		}
	fi
fi

if FindPKG friendly-recovery; then
	Prompt\
		"[4653]: Will you need friendly-recovery? (Enter 'Y' if unsure)"\
		"If you enter 'N', friendly-recovery will be removed."\
		"Makes the recovery mode (accessed via the bootloader) friendlier."\
	|| {
		DoSay "Calling APT to remove the friendly-recovery package."
		RemPKG friendly-recovery
	}
fi

if FindPKG reiserfsprogs; then
	Prompt\
		"[1957]: Will you need reiserfsprogs? (Enter 'Y' if unsure)"\
		"If you enter 'N', the reiserfsprogs package will be removed."\
		"User-level tools for ReiserFS filesystems."\
	|| {
		DoSay "Calling APT to remove the reiserfsprogs package."
		RemPKG reiserfsprogs
	}
fi

if FindPKG x11-session-utils; then
	Prompt\
		"[0541]: Will you need x11-session-utils? (Enter 'Y' if unsure)"\
		"If you enter 'N', the x11-session-utils package will be removed."\
		"This package provides the X session manager and related tools."\
	|| {
		DoSay "Calling APT to remove the x11-session-utils package."
		RemPKG x11-session-utils
	}
fi

if FindPKG apport apport-\* python-apport python3-apport; then
	Prompt\
		"[7030]: Will you ever need automated crash reports?"\
		"If you enter 'N', apport and related packages will be removed."\
		"Automatically generate crash reports for debugging."\
	|| {
		DoSay "Calling APT to remove the apport and related packages."
		RemPKG apport apport-\* python-apport python3-apport
	}
fi

if FindPKG \*popularity-contest \*-popcon; then
	Prompt\
		"[8745]: Do you want to send Canonical your usage data?"\
		"If you enter 'N', popcon and related packages will be removed."\
		"Allows the user to \"vote\" for their favorite packages, automatically."\
	|| {
		DoSay "Calling APT to remove popcon and related packages packages."
		RemPKG \*popularity-contest \*-popcon
	}
fi

if FindPKG pcmciautils; then
	Prompt\
		"[6308]: Do you need support for PCMCIA devices? (Enter 'Y' if unsure)"\
		"If you enter 'N', the pcmciautils package will be removed."\
		"PCMCIA utilities for Linux 2.6.13-rc1 or later."\
	|| {
		DoSay "Calling APT to remove the pcmciautils package."
		RemPKG pcmciautils
	}
fi

if PathLook time; then
	Prompt\
		"[0022]: Will you need the time package? (Enter 'Y' if unsure)"\
		"If you enter 'N', the time package will be removed."\
		"The GNU alternative to the time bash builtin."\
	|| {
		DoSay "Calling APT to remove the time package."
		RemPKG time
	}
fi

if FindPKG xinit; then
	Prompt\
		"[3662]: Will you need the xinit package? (Enter 'Y' if unsure)"\
		"If you enter 'N', the xinit package will be removed."\
		"Facilitates starting an X server and base X session."\
	|| {
		DoSay "Calling APT to remove the xinit package."
		RemPKG xinit
	}
fi

if FindPKG cryptsetup{,bin} libcrypt-passwdmd5-perl; then
	Prompt\
		"[0778]: Will you need disk encryption support? (Enter 'Y' if unsure)"\
		"If you enter 'N', various crypt-related packages will be removed."\
		"Tool for simulating superuser privileges."\
	|| {
		DoSay "Calling APT to remove various crypt-related packages."
		RemPKG cryptsetup{,bin} libcrypt-passwdmd5-perl
	}
fi

if FindPKG gstreamer1.0-fluendo-mp3; then
	Prompt\
		"[9507]: Do you want the Fluendo MP3 decoder? (Enter 'Y' if unsure)"\
		"If you enter 'N', the gstreamer1.0-fluendo-mp3 package will be removed."\
		"A GStreamer 1.0 plugin allowing decoding of MPEG 1 audio layer III streams."\
	|| {
		DoSay "Calling APT to remove the gstreamer1.0-fluendo-mp3 package."
		RemPKG gstreamer1.0-fluendo-mp3
	}
fi

if FindPKG aptitude\*; then
	Prompt\
		"[1047]: Will you be using aptitude? (Enter 'Y' if unsure)"\
		"If you enter 'N', aptitude and related packages will be removed."\
		"Lightweight package manager with a terminal-based UI."\
	|| {
		DoSay "Calling APT to remove aptitude and related packages."
		RemPKG aptitude\*
	}
fi

if FindPKG whiptail; then
	Prompt\
		"[0601]: Will you be using whiptail? (Enter 'Y' if unsure)"\
		"If you enter 'N', whiptail and related packages will be removed."\
		"Displays user-friendly dialog boxes from shell scripts."\
	|| {
		DoSay "Calling APT to remove whiptail and related packages."
		RemPKG whiptail
	}
fi

if FindPKG ureadahead; then
	Prompt\
		"[9838]: Will you be using ureadahead? (Enter 'Y' if unsure)"\
		"If you enter 'N', ureadahead and related packages will be removed."\
		"Read required files in advance, improving boot performance."\
	|| {
		DoSay "Calling APT to remove ureadahead and related packages."
		RemPKG ureadahead
	}
fi

if FindPKG python3-cairo python3-gi-cairo; then
	Prompt\
		"[0296]: Will you need Python Cairo packages? (Enter 'Y' if unsure)"\
		"If you enter 'N', Python 3 Cairo packages will be removed."\
		"Read required files in advance, improving boot performance."\
	|| {
		DoSay "Provides Cairo modules for use in Python 3 programs."
		RemPKG python3-cairo python3-gi-cairo
	}
fi

Prompt\
	"[1017]: Remove any and all leftover cached DEB packages?"\
	"If you do this, these packages would have to be re-downloaded."\
&& {
	DoSay "Removing leftover cached DEB packages."
	rm -vf 2> /dev/null\
		/var/cache/apt/archives/*\
		/var/cache/apt/archives/partial/*\
		/var/lib/apt/lists/partial/*\
		/var/cache/apt/pkgcache.bin\
		/var/cache/apt/srcpkgcache.bin
}

DoSay 'Synchronizing cached writes to persistent storage.'
sync

printf '\nDONE! -- Please reboot the machine.\n\n'
