#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/backmeup
#------------------------------------------------------------------------------
# Project Name      - Extra/source/backmeup/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Fri 21 Jan 23:48:10 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for BackMeUp.
#------------------------------------------------------------------------------

_backmeup() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(backmeup -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	else
		case $3 in
			-s|--set-store|-E|--exclude)
				COMPREPLY=(`compgen -o default -- "$2"`) ;;
		esac
	fi
}

complete -F _backmeup backmeup
