#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/backmeup
#------------------------------------------------------------------------------
# Project Name      - Extra/source/backmeup/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Wed 12 Feb 18:58:18 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `backmeup`.
#------------------------------------------------------------------------------

_backmeup(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(backmeup -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _backmeup backmeup
