#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/.config/herbstluftwm/autostart
# Started On        - Sat 30 Mar 21:41:21 GMT 2019
# Last Change       - Wed 27 Nov 15:53:50 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# These are my HLWM settings, which closely mimic my i3-wm setup, for familiarity.
#
# NOTE: You'll need some files from my i3config repository. These will be added to
#       insit seperately, eventually, but for now, you'll need to do this manually
#       if you want to use them, or just install i3config via insit.
#---------------------------------------------------------------------------INITIAL

/bin/bash $HOME/.i3a/initialize

hc(){ herbstclient $@; }

#---------------------------------------------------------------------------CLEANUP

hc emit_hook reload # <-- Must be first!
hc keyunbind --all
hc mouseunbind --all
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc unrule -F

#--------------------------------------------------------------------------BINDINGS

#hc keybind Mod1-Shift-q<F2> quit
hc keybind Mod1-Shift-r reload
#hc keybind Mod1-Shift-q close_and_remove
hc keybind Mod1-Shift-q close

hc keybind Mod1-j focus left
hc keybind Mod1-k focus down
hc keybind Mod1-l focus up
hc keybind Mod1-semicolon focus right

hc keybind Mod1-Shift-j shift left
hc keybind Mod1-Shift-k shift down
hc keybind Mod1-Shift-l shift up
hc keybind Mod1-Shift-semicolon shift right

hc keybind Mod1-Control-j resize left +0.5
hc keybind Mod1-Control-k resize down +0.5
hc keybind Mod1-Control-l resize up +0.5
hc keybind Mod1-Control-semicolon resize right +0.5

hc keybind Mod1-space floating toggle
hc keybind Mod1-f fullscreen toggle

hc keybind Mod4+0 spawn /usr/bin/redshifter -i 100
hc keybind Mod4+9 spawn /usr/bin/redshifter -d 100
hc keybind Mod4+8 spawn /usr/bin/redshifter -r

hc keybind Mod1+h split right
hc keybind Mod1+v split below
hc keybind Mod1+q remove

hc keybind Mod4+Shift+j resize left +0.01
hc keybind Mod4+Shift+semicolon resize left -0.01
hc keybind Mod4+Shift+k resize down +0.01
hc keybind Mod4+Shift+l resize up +0.01

hc keybind Mod4+Shift+Left resize left +0.001
hc keybind Mod4+Shift+Right resize right -0.001
hc keybind Mod4+Shift+Down resize down +0.001
hc keybind Mod4+Shift+Up resize up +0.001

hc keybind Mod1+Return spawn /bin/bash $HOME/.i3a/terminal
hc keybind Shift+Control+Up spawn /bin/bash $HOME/.i3a/term_font_size -r 1
hc keybind Shift+Control+Down spawn /bin/bash $HOME/.i3a/term_font_size -l 1
hc keybind Shift+Control+Left spawn /bin/bash $HOME/.i3a/term_font_size -s 11
hc keybind Shift+Control+Right spawn /bin/bash $HOME/.i3a/term_font_size -s 21
hc keybind Mod1+Tab spawn /bin/bash $HOME/.i3a/drop_terminal
hc keybind Mod4+w spawn /usr/bin/mpv tv://
hc keybind Mod4+Shift+0 spawn /usr/bin/transset -a 1
hc keybind Mod4+Shift+9 spawn /usr/bin/transset -a 0.2
hc keybind Mod4+l spawn /bin/bash $HOME/.i3a/lockscreen

hc keybind Mod4+p spawn /bin/bash $HOME/.i3a/track_notify
hc keybind Mod4+XF86AudioNext spawn /usr/bin/mocp --seek +3
hc keybind Mod4+XF86AudioPrev spawn /usr/bin/mocp --seek -3
hc keybind XF86AudioPlay spawn /usr/bin/mocp -G
hc keybind XF86AudioNext spawn /usr/bin/mocp --next
hc keybind XF86AudioPrev spawn /usr/bin/mocp --previous

hc keybind XF86AudioRaiseVolume spawn /bin/bash $HOME/.i3a/sink_raise
hc keybind XF86AudioLowerVolume spawn /bin/bash $HOME/.i3a/sink_lower
hc keybind XF86AudioMute spawn /bin/bash $HOME/.i3a/sink_mute
hc keybind Shift+XF86AudioRaiseVolume spawn /bin/bash $HOME/.i3a/source_raise
hc keybind Shift+XF86AudioLowerVolume spawn /bin/bash $HOME/.i3a/source_lower
hc keybind Shift+XF86AudioMute spawn /bin/bash $HOME/.i3a/source_mute
hc keybind Shift+Mod1+XF86AudioLowerVolume spawn /bin/bash $HOME/.i3a/hush_the_mic
hc keybind XF86Calculator spawn /usr/bin/xcalc
hc keybind Print spawn /bin/bash $HOME/.i3a/scrot_take
hc keybind Shift+Print spawn /bin/bash $HOME/.i3a/scrot_sel_take
hc keybind Mod4+Print spawn /bin/bash $HOME/.i3a/scrot_sel_take --lite
hc keybind Control+Shift+Print spawn /bin/bash $HOME/.i3a/scrot_win_take
hc keybind Mod1+d spawn /bin/bash $HOME/.i3a/use_dmenu
hc keybind Mod1+Shift+num spawn /bin/bash $HOME/bin/telldate

hc keybind Shift+Mod4+1 spawn /bin/bash $HOME/.i3a/partmount -L "Main Data"
hc keybind Shift+Mod4+2 spawn /bin/bash $HOME/.i3a/partmount -L "Media 1"
hc keybind Shift+Mod4+3 spawn /bin/bash $HOME/.i3a/partmount -L "Media 2"
hc keybind Shift+Mod4+4 spawn /bin/bash $HOME/.i3a/partmount -L "Media 3"
hc keybind Shift+Mod4+5 spawn /bin/bash $HOME/.i3a/partmount -L "CloneZilla"

hc mousebind Mod1-Button1 move
hc mousebind Mod1-Button3 resize

#-------------------------------------------------------------------------TAG SETUP

hc rename default 1
for TAG in {1..9} 0; {
	if hc add $TAG; then
		hc keybind Mod1+$TAG use $TAG
		hc keybind Mod1+Shift+$TAG move $TAG
	fi
}

#------------------------------------------------------------------------------SETS

hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#000000'

hc set default_frame_layout 0
hc set always_show_frame 2
hc set frame_border_width 4
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 10
hc set frame_normal_opacity 20
hc set frame_active_opacity 60

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_stealing_prevention 1
hc set update_dragged_clients 1

#-----------------------------------------------------------------------------RULES

hc rule focus=on

hc rule class="Firefox" tag=4
hc rule class="Thunderbird" tag=8
hc rule class="Xmessage" pseudotile=on
hc rule class="Pavucontrol" pseudotile=on
hc rule class="Openshot-qt" tag=2 fullscreen=on
hc rule class="Audacity" tag=2 fullscreen=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#---------------------------------------------------------------------MISCELLANEOUS

hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

#-----------------------------------------------------------------------------PANEL

hc pad 0 0
#hc pad 0 20
#/bin/bash $HOME/.config/herbstluftwm/panel.sh &

