#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/autowall
# Started On        - Tue 10 Oct 23:26:39 BST 2017
# Last Change       - Wed 11 Oct 00:00:28 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# Probably isn't usable just yet, but it might be.
#
# This is from a shell script I wrote quite some time ago now. Not a bad feature
# to introduct to something like the i3-wm, which I did and still do often use.
# I'm currently in the process of updating it; will probably add features, too.
#
# The idea behind this was to load it up in the background, when you log in. It
# would then cycle through your wallpapers using Nitrogen. I'll eventually
# incorporate feh for those who use that, though.

#----------------------------------------------------------------------------------

#TODO - Set a feature in this script which changes wallpaper based on the time of
#       day. Another for a playlist for the time.
#TODO - Set another feature for just the one fixed wallpaper.
#TODO - Another feature which could go with the above, is to have a keybind change
#       to a different (random?) wallpaper in the playlist.

XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/{lsof,xargs,nitrogen,awk} /bin/{sed,grep,sleep}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

shopt -s extglob

USAGE(){
	while read -r; do
		echo "$REPLY"
	done <<-EOF
		            AUTOWALL (10th October 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            View wallpapers in a slideshow. Ideal for lightweight setups.

		SYNTAX:     autowall [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug                 - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --method [P|F]          - Display in a [P]laylist or by [F]folder.
		            --interval N            - Change wallpapers every N seconds.

		NOTE:       The default behavior is: --method P --interval 10
	EOF
}

METHOD="P"
INTERVAL=10

while [ -n "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--method)
			shift; METHOD="$1" ;;
		--interval)
			shift; INTERVAL="$1" ;;
		*)
			break ;;
	esac

	shift
done

[ -n "$*" ] && XERR "$LINENO" "Incorrect argument(s) specified."
[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

#TODO - Rewrite this to avoid awk and xargs. (lsof and kill can do it alone)
/usr/bin/lsof\
	| /usr/bin/awk "/\/wallpaperchange.sh$/{sub(/^$$\s.*\$/,\"\"); print \$1}"\
	| /usr/bin/xargs -i{} kill {}

#TODO - Add feh support.
if [ "$METHOD" = "F" ]; then
	while :; do
		for FWALL in $HOME/Pictures/**/**/*; {
			/usr/bin/nitrogen --set-centered "$FWALL" 2> /dev/null
			#TODO - Replace wasteful awk with a read array.
			echo "$FWALL" | awk -F"/" '{print $NF}'
			/bin/sleep "${INTERVAL}"s
		}
	done
elif [ "$METHOD" = "P" ]; then
	#TODO - Incoporate this list into a user file, ... and/or via STDIN?
	BG[1]="PATH"

	while :; do
		for PWALL in ${BG[@]}; {
			/usr/bin/nitrogen --set-centered "$PWALL" 2> /dev/null
			echo "$PWALL"
			/bin/sleep "${INTERVAL}"s
		}
	done
fi

[ "$DEBUGME" == "true" ] && set +xeu || exit 0
