#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/autoscrot
# Started On        - Sun 17 Sep 05:06:50 BST 2017
# Last Change       - Wed 27 Nov 15:53:47 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-11-27"
_PROJECT_=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Tool to take full screenshots at user-specified intervals using scrot.

		SYNTAX:     $_PROJECT_ [OPTS] [SCROT_ARGS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.
		            --interval|-I N         - Where N is the seconds of interval.

		NOTE:       If no interval is provided, a default of 3 will be used.

		            The scrot arguments (via SCROT_ARGS) are completely optional. Due to
		            the nature of $_PROJECT_, obviously some argument will make no sense to
		            pass over to scrot to process, such as the -h and probably -s flags.

		            Images are saved at the default quality for JPG images.

		FILE:       Screenshots saved in: \$HOME/Pictures/AutoScrot/
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET='true' ;;
		--debug|-D)
			DEBUGME='true' ;;
		--interval|-I)
			shift; INTERVAL=$1
			if ! [[ ${INTERVAL} =~ ^[0-9]+$ ]]\
			|| [ $INTERVAL -lt 1 ]; then
				Err 1 $LINENO "Invalid interval selected."
			fi ;;
		-*)
			Err 1 $LINENO "Incorrect argument specified." ;;
		*)
			break ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in scrot mkdir sleep; {
	if ! type -fP "$DEP" > /dev/null 2>&1; then
		Err 0 $LINENO "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -gt 0 ] && exit 1

[ "$BEQUIET" == 'true' ] && exec > /dev/null
[ "$DEBUGME" == 'true' ] && set -x

printf "Press Ctrl + C to cancel and exit $_PROJECT_.\n"

declare -i NUM=0
while :; do
	sleep ${INTERVAL:-3}s

	MAIN_DIR="$HOME/Pictures/AutoScrot"
	[ -d "$MAIN_DIR" ] || mkdir -p "$MAIN_DIR"
	printf -v FILENAME "%s/Screenshot_%(%F_%X)T.jpg" $MAIN_DIR -1

	if scrot $@ "$FILENAME"; then
		NUM+=1
		printf "\rScreenshots taken:   %'d" "$NUM"
	else
		Err 0 $LINENO "Non-zero exit status for screenshot #${NUM}."
	fi
done
printf "\n"

