#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/backmeup
# Started On        - Tue  7 Nov 21:50:05 GMT 2017
# Last Change       - Sun 19 Nov 16:38:41 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /bin/{gzip,tar,mv,sync}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not required."
[ $# -eq 0 ] || XERR "$LINENO" "No arguments are required."
[ -e /proc/mounts ] || XERR "$LINENO" "Unable to find file: /proc/mounts"

printf -v LABEL "1TB Internal HDD"
printf -v ARCHIVE "BMU_%(%F_%H%M)T" "-1"
printf -v STORE "/media/%s/%s" "$USER" "$LABEL"

while read -a X; do
	if [[ "${X[1]}" =~ "${LABEL// /040}" ]]; then
		/bin/tar\
			--exclude="${HOME/\/}/.cache/*"\
			--exclude="${HOME/\/}/.thumbnails/*"\
			-cvpf --xattrs "$STORE/$ARCHIVE" "$HOME"

		/bin/gzip -v --best --suffix ".tgz" "$STORE/$ARCHIVE"
		/bin/sync "$STORE/$ARCHIVE.tgz"
		exit 0
	fi
done < /proc/mounts

XERR "$LINENO" "The backup target is not available."
