#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/ShellPlugins/Clean_Unused_Locales
# Started On        - Wed  1 Nov 11:29:18 GMT 2017
# Last Change       - Wed 10 Jan 20:54:41 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            CLEAN-LOCALES (10st January 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Remove some unnecessary non-English localizations.

		SYNTAX:     clean-locales [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		FILES:      Files in /usr/share/locale will be deleted, except:

		            en_GB
		            en_US
		            locale.alias
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

if [ -x /bin/rm ]; then
	[ -d /usr/share/locale ] || {
		XERR "$LINENO" "Directory missing: /usr/share/locale"
	}

	for DIR in /usr/share/locale/*; {
		if ! [[ "$DIR" =~ (en_GB|en_US|locale\.alias) ]]; then
			printf "DELETING: $DIR "

			if [ -e /dev/null ]; then
				/bin/rm -rf "$DIR" &> /dev/null && {
					printf "[OK]\n"
				} || printf "[ERROR]\n"
			else
				XERR "$LINENO" "Unable to find: /dev/null"
			fi
		else
			printf "SKIPPING: %s\n" "$DIR"
		fi
	}
else
	XERR "$LINENO" "Dependency '/bin/rm' not met."
fi
