#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/clean-locales
# Started On        - Wed  1 Nov 11:29:18 GMT 2017
# Last Change       - Thu  9 May 21:21:55 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            CLEAN-LOCALES ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Remove some unnecessary non-English localizations.

		SYNTAX:     clean-locales [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		FILES:      Files in /usr/share/locale will be deleted, except:

		            en_GB
		            en_US
		            locale.alias
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ "$BEQUIET" == "true" ] && exec > /dev/null
[ "$DEBUGME" == "true" ] && set -x

if [ -x /bin/rm ]; then
	if ! [ -d /usr/share/locale ]; then
		XERR "$LINENO" "Directory missing: /usr/share/locale"
	fi

	for DIR in /usr/share/locale/*; {
		if ! [[ "$DIR" =~ (en_GB|en_US|locale\.alias) ]]; then
			printf "DELETING: $DIR "

			if /bin/rm -rf "$DIR" >&- 2>&-; then
				printf "[OK]\n"
			else
				printf "[ERROR]\n"
			fi
		else
			printf "SKIPPING: %s\n" "$DIR"
		fi
	}
else
	XERR "$LINENO" "Dependency '/bin/rm' not met."
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
