#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/disk-watcher
# Started On        - Sun 28 Jan 00:56:24 GMT 2018
# Last Change       - Thu  9 May 00:53:57 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Placeholder for a handy-dandy project idea.
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

#TODO - Use pure shell only! Parse /sys, /proc, and/or /dev.

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DISK-WATCHER ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Background utility which watches for low storage space.

		SYNTAX:     disk-watcher [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

[ "$BEQUIET" == "true" ] && exec >&-
[ "$DEBUGME" == "true" ] && set -x



# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
