#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - dl-ubuntu-podcasts
# Started On        - Sat  7 Oct 19:08:59 BST 2017
# Last Change       - Tue 19 Dec 12:28:53 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /bin/grep /usr/bin/wget; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

#TODO - Currently won't download S01E01.
#TODO - IMPORTANT: Fix filenames; they're a mess. :(

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DL-UBUNTU-PODCASTS (19th December 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Simple program to download all of the old Ubuntu Podcast episodes.

		SYNTAX:     dl-ubuntu-podcasts [OPTS] PAGE PAGE PAGE . . .
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug                 - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --dest|-d PATH          - Where PATH is an alternative destination.
		            --get-season-eight      - Grab the newer episodes from season eight.
		            --get-season-nine       - Grab the newer episodes from season nine.
		            --get-season-ten        - Grab the newer episodes from season ten.

		NOTE:       Files will by default be saved in OGG to the current directory.

		            Using one of the extra season flags will download all of the available
		            podcasts in that given season.

		SITES:      Seasons 1-7:     http://podcast.ubuntu-uk.org
		            Seasons 8-10:    http://static.ubuntupodcast.org
	EOF
}

ALTDEST=""

EXTRA_SEASON(){
	URL="http://static.ubuntupodcast.org/ubuntupodcast"

	for E in /usr/bin/seq $2 $3; {
		/usr/bin/wget -qc --show-progress\
			"$URL/s${1}/e${E}/ubuntupodcast_s${1}e${E}.mp3"
	}
}

while [ -n "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--dest|-s)
			shift

			ALTDEST="$1"
			[ -d "$ALTDEST" ] || {
				XERR "Destination directory not found."
			} ;;
		--get-season-eight)
			EXTRA_SEASON 08 01 42 ;;
		--get-season-nine)
			EXTRA_SEASON 09 01 44 ;;
		--get-season-ten)
			EXTRA_SEASON 10 01 38 ;;
		*)
			break ;;
	esac

	shift
done

if [ -n "$*" ]; then
	USERPAGE="true"

	while [ -n "$1" ]; do
		if ! [[ "$1" =~ [0-9]+ ]]; then
			XERR "$LINENO" "Incorrect page number specified."
		else
			[ $1 -eq 2 ] || NUM+=" $1"
		fi

		shift
	done
else
	NUM=193
fi

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

while :; do
	if ! [ "$USERPAGE" == "true" ]; then
		[ $NUM -le 2 ] && break || let NUM--
	else
		NUM="${NUM%% *}"
	fi

	#TODO - Fix custom pages not working.

	PAGE=`/usr/bin/wget -q "http://podcast.ubuntu-uk.org/page/$NUM" -O -`
	DL_LINK=`printf "%s\n" "$PAGE" | /bin/grep -m 1 -o "http://podcast\.ubuntu-uk\.org/download/.*\.ogg"`
	OUTNAME=`printf "%s\n" "$PAGE" | /bin/grep -m 1 -o "[Ss][0-9]\+[Ee][0-9]\+\s\+–\s\+[[:space:][:alnum:]]\+"`

	if [ -z "$ALTDEST" ]; then
		printf "NUM:         %s\n" "$NUM"
		printf "OUTNAME:     %s\n" "$OUTNAME"
		[ -z "$OUTNAME" ] && break
		/usr/bin/wget -cq --show-progress\
			"$DL_LINK" -O "./${OUTNAME}.ogg"
	else
		[ -z "$OUTNAME" ] && break
		/usr/bin/wget -cq --show-progress\
			"$DL_LINK" -O "${ALTDEST%\/}/${OUTNAME}.ogg"
	fi

	[ "$USERPAGE" == "true" ] || NUM="${NUM/* }"
	[ -z "$NUM" ] && break
done
