#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/dlfallwalls
# Started On        - Sun 15 Oct 20:48:22 BST 2017
# Last Change       - Thu  9 May 00:54:23 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

[ -x /usr/bin/wget ] || ERR "$LINENO" "Dependency '/usr/bin/wget' not met."

DOM="https://wallpapercave.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DLFALLWALLS (3rd March 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download a collection of Autumn/Fall wallpapers.

		SYNTAX:     dlfallwalls [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		NOTE:       Files will be download to the current directory, as JPGs.

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
[ 0${WGET_VER_LINE[2]//[!0-9]} -ge 01192 ] && NOWARC="--no-warc-compression"

[ "$BEQUIET" == "true" ] && exec >&-
[ "$DEBUGME" == "true" ] && set -xeu

URL="$DOM/download/fall-wallpapers"
HTML=`/usr/bin/wget $NOWARC -q "${URL%/down*}/fall-wallpapers" -O -`

declare -a GETID=()
while read -a Y; do
	for FIELD in ${Y[@]/src=\"\/wp}; {
		[ "$FIELD" == "$OLD" ] && continue
		[[ "$FIELD" == /* ]] && {
			[[ "$FIELD" =~ [0-9A-Za-z]+.jpg ]] && {
				GETID+=("${FIELD%.jpg\"}")
			}
		} || continue
		OLD="$FIELD"
	}
done <<< "$HTML"

declare -i N=1
for ID in ${GETID[@]//\/}; {
	printf "%s\n" "DOWNLOADING: fall-wallpapers-${ID}.jpg"
	printf -v FNAME "./fall-wallpapers-%0.2d.jpg" "${N}"
	/usr/bin/wget $NOWARC -qc "${URL}-1920x1080-${ID}" -O "$FNAME"
	N+=1
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
