#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/dlfcmags
# Started On        - Tue 28 Nov 00:02:33 GMT 2017
# Last Change       - Sun 12 May 15:35:40 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Download the entire collection of the Full Circle magazine for Ubuntu Linux.
#----------------------------------------------------------------------------------

_VERSION_="2019-05-12"
_PROJECT_="${0##*/}"

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

DOMAIN="https://dl.fullcirclemagazine.org"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download issues of the Full Circle magazine PDFs.

		SYNTAX:     $_PROJECT_ [OPTS] ISSUE1 ISSUE2 ISSUE3 . . .

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		EXAMPLE:    $_PROJECT_ 7
		            $_PROJECT_ -q {20..76}
		            $_PROJECT_ 1 8 9 22 {24..27}

		SITE:       ${DOMAIN/\/dl.//}

		NOTE:       There are currently versions 1-127 available.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		-*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

if ! type -fP wget > /dev/null 2>&1; then
	FAIL 1 "$LINENO" "Dependency '/usr/bin/wget' not met."
fi

if ! [ "$*" ]; then
	printf -v ISSUE_LIST " %d" {1..127}
else
	ISSUE_LIST="$@"
fi

[ "$BEQUIET" == "true" ] && exec > /dev/null

DL="/issue127_en.pdf"

for ISSUE in $ISSUE_LIST; {
	printf -v PRETTY_ISSUE "%0.3d" "$ISSUE"
	/usr/bin/wget -qc --show-progress "$DOMAIN/issue${ISSUE}_en.pdf"\
		-O "$PRETTY_ISSUE - Full Circle.pdf"
}
