#!/bin/bash

set -- "3D / Abstract" 1

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/dlhdw
# Started On        - Sat  9 Jun 11:40:57 BST 2018
# Last Change       - Fri 26 Apr 14:43:32 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# WORK IN PROGRESS!!!
#----------------------------------------------------------------------------------

_VERSION_="2019-04-26"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

DOM="https://www.hdwallpapers.in"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DLHDW - DOWNLOAD HD WALLPAPERS ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download images, in bulk, from the HD Wallpapers website.

		SYNTAX:     dlhdw [OPTS] CATEGORY RESOLUTION PAGE

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		EXAMPLE:    dlhdw -q "3D / Abstract" 1

		NOTE:       Some categories will need to be protected within quotes, to avoid the
		            shell interpretating each space-delimetered field as an argument.

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

#----------------------------------------------------------------PROCESS CATEGORIES

CATEGORIES=(
	"3D / Abstract"
)

CATEGORY="$1"

declare -i ERR_COUNT=0
for CAT in ${CATEGORIES[@]}; {
	[ "$CAT" == "$CATEGORY" ] || ERR_COUNT+=1
}

declare -i CAT_ERRCOUNT=0
if ! [ "$CATEGORY" ]; then
	CATPAGE_ERRCOUNT+=1
	ERR "$LINENO" "No CATEGORY provided."
elif [ $ERR_COUNT -gt 0 ]; then
	CATPAGE_ERRCOUNT+=1
	ERR "$LINENO" "Incorrect category '$CATEGORY' selected."
fi

#---------------------------------------------------------------PROCESS RESOLUTIONS

RESOLUTIONS=(
	"1920x1080"
)

RESOLUTION="$2"

declare -i ERR_COUNT=0
for CAT in ${CATEGORIES[@]}; {
	[ "$CAT" == "$CATEGORY" ] || ERR_COUNT+=1
}

declare -i RES_ERRCOUNT=0
if ! [ "$PAGE" ]; then
	PAGE_ERRCOUNT+=1
	ERR "$LINENO" "No PAGE provided."
elif ! [[ "$PAGE" =~ ^[0-9]+$ ]]; then
	PAGE_ERRCOUNT+=1
	ERR "$LINENO" "Invalid page '$PAGE' selected."
fi

#---------------------------------------------------------------------PROCESS PAGES

PAGE="$3"

declare -i PAGE_ERRCOUNT=0
if ! [ "$PAGE" ]; then
	PAGE_ERRCOUNT+=1
	ERR "$LINENO" "No PAGE provided."
elif ! [[ "$PAGE" =~ ^[0-9]+$ ]]; then
	PAGE_ERRCOUNT+=1
	ERR "$LINENO" "Invalid page '$PAGE' selected."
fi

[ $PAGE_ERRCOUNT -gt 0 -o $CAT_ERRCOUNT -gt 0 ] && exit 1

#--------------------------------------------------------------------------CONTINUE

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
	NOWARC="--no-warc-compression"
fi

[ "$BEQUIET" == "true" ] && exec >&-
[ "$DEBUGME" == "true" ] && set -x

RES_SUFFIX="/1920x1080_hd-wallpapers-r.html"
PAGE_DATA="$DOM/$CATEGORY"

while read; do
	printf "%s\n" "$REPLY"
done < $HOME/Desktop/1 # <<< "$PAGE_DATA"
