#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/dlspwalls
# Started On        - Sun 15 Oct 20:48:22 BST 2017
# Last Change       - Wed 10 Jan 14:09:48 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

[ -x /usr/bin/wget ] || ERR "$LINENO" "Dependency '/usr/bin/wget' not met."

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            DLSPWALLS (10th January 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Download a collection of steampunk wallpapers.

		SYNTAX:     dlspwalls [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		NOTE:       Files will be download to the current directory, as JPGs.

		SITE:       https://wallpapercave.com
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

URL="https://wallpapercave.com/download/steampunk-wallpaper"
HTML=`/usr/bin/wget -q "${URL%/down*}/steampunk-wallpaper-1920x1080" -O -`

declare -a GETID=()
while read -a Y; do
	for FIELD in ${Y[@]/src=\"\/wp}; {
		[ "$FIELD" == "$OLD" ] && continue

		[[ "$FIELD" == /* ]] && {
			[[ "$FIELD" =~ [0-9A-Za-z]+.jpg ]] && {
				GETID+=("${FIELD%.jpg\"}")
			}
		} || continue

		OLD="$FIELD"
	}
done <<< "$HTML"

declare -i N=0
for ID in ${GETID[@]//\/}; {
	N+=1

	printf "%s\n" "DOWNLOADING: steampunk-wallpaper-1920x1080-${ID}.jpg"
	printf -v FNAME "./steampunk-wallpaper-1920x1080-%0.2d.jpg" "${N}"
	/usr/bin/wget -qc "${URL}-1920x1080-${ID}" -O "$FNAME"
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
