#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/feh-slides
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Thu  9 May 17:10:28 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            FEH-SLIDES ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            A super-simple desktop wallpaper slideshow.

		SYNTAX:     feh-slides [OPTS] [PATH]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
		            --interval|-i N         - Change wallpaper every N seconds.
		            --trap|-T               - Trap SIGUSR1 for a cleaner exit. This is more
		                                      of a placeholder for future expansion.

		NOTE:       Where PATH is the directory in which your chosen wallpapers are stored.

		            If no interval is specified, the default of 5 seconds is chosen.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--interval|-i)
			shift; INTERVAL="$1" ;;
		--trap|-T)
			TRAP="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in /bin/sleep /usr/bin/feh; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

if [ $# -gt 1 ]; then
	XERR "$LINENO" "Only one wallpaper directory may be specified."
elif [ $# -eq 0 ]; then
	XERR "$LINENO" "A wallpaper directory must be specified."
fi

[ "$DEBUGME" == "true" ] && set -x

# Room for easy expansion.
EXIT(){
	kill $$
	exit 0
}

if [ -d "$1" ]; then
	if [ "$TRAP" == "true" ]; then
		trap 'EXIT' 10 # SIGUSR1
	fi

	while :; do
		for FILE in "${1%\/}"/*; {
			if [ -f "$FILE" ]; then
				if ! /usr/bin/feh --no-fehbg --bg-center "$FILE"; then
					XERR "$LINENO" "One or more errors detected while setting wallpaper with feh."
				elif ! /bin/sleep ${INTERVAL:-5}s >&- 2>&-; then
					XERR "$LINENO" "Invalid interval time specified."
				fi
			fi
		}
	done
else
	XERR "$LINENO" "Directory '$1' not found."
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
