#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/freelfm
# Started On        - Fri 15 Sep 21:19:42 BST 2017
# Last Change       - Thu  9 May 00:57:07 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/{tee,wget} /bin/{sync,sleep,sed,grep,mkdir}; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -gt 0 ] && exit 1

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            FREELFM ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download last.fm's free music into the current working directory.

		SYNTAX:     freelfm [OPTS] <page#> <page#> <page#> . . .

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
		            --links-only            - Don't download, just save the true, direct
		                                      download links to a file. See FILES.
		            --suspend|-s            - Suspend the system after freelfm finishes.
		            --shutdown|-S           - Shut the system down after freelfm finishes.

		NOTE:       The current max page is 12. The total number is 220+ MP3 tracks.

		FILES:      The freelfm files (except tracks) are saved in /tmp, for example:

		            STDOUT and STDERR are logged into this file.

		              freelfm_2017-09-01_21:25:47.log

		            Each page is downloaded and then parsed for download links.

		              freelfm_p2_2017-09-01_21:25:47.htm

		            If you choose the --links-only flag, they will be saved here.

		              freelfm_links_2017-09-01_21:25:47.txt

		SITE:       https://www.last.fm
	EOF
}

LINKSONLY="false"
PAGENUM=""

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--suspend|-s)
			SUSPEND="true" ;;
		--shutdown|-S)
			SHUTDOWN="true" ;;
		--links-only)
			LINKSONLY="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

if ! [ "$*" ]; then
	XERR "$LINENO" "One or more page numbers missing."
else
	PAGENUM="$@"
	for NUM in $PAGENUM; {
		if ! [[ "$NUM" == [0-9] ]]; then
			XERR "$LINENO" "Invalid page number at: $NUM"
		fi
	}
fi

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
[ 0${WGET_VER_LINE[2]//[!0-9]} -ge 01192 ] && NOWARC="--no-warc-compression"

[ "$DEBUGME" == "true" ] && set -x

DLDIR="./"
printf -v CURDATE "%(%F_%X)T" -1
SITEURL="https://www.last.fm/music/+free-music-downloads?page="
LINKSONLY_FILE="/tmp/freelfm_links_${CURDATE}.txt"
LOGFILE="/tmp/freelfm_${CURDATE}.log"

for PAGE in $PAGENUM; {
	SITETMP="/tmp/freelfm_${PAGE}_${CURDATE}.htm"

	printf "%s\n" "PAGE: $PAGE"
	/usr/bin/wget $NOWARC -q "${SITEURL}${PAGE}" -O "$SITETMP"

	TITLELINK=$(
		/bin/grep -e "title=\".* — .*\"" -oe "https://.*\.mp3" "$SITETMP"\
			| /bin/sed 's/\s/_/g; s/&amp\;/\&/g; s/—/-/g'
	)

	for LINK in $TITLELINK; {
		if [[ "$LINK" == title=* ]]; then
			TITLE=$(
				printf "%s\n" "${LINK//_/ }"\
					| /bin/sed -e s/\&amp\;/\&/ -e s/^title=//\
						   -e s/\"//g -e s/\&\#39\;/\'/g
			)
		else
			if ! [ "$LINKSONLY" == "true" ]; then
				printf "%s\n" "FILE: ${TITLE}.mp3"
				/usr/bin/wget -qc --no-cookies $NOWARC \
					"$LINK" -O "$DLDIR/${TITLE//\"}.mp3" || {
					ERR "$LINENO" "Track '${TITLE}.mp3' failed."
				}
			else
				printf "%s\n" "LINK: ${TITLE}.mp3"
				printf "%s\n" "$LINK" >> "$LINKSONLY_FILE"
			fi
		fi
	}
} |& /usr/bin/tee "$LOGFILE"

if [ "$SHUTDOWN" == "true" ]; then
	/sbin/shutdown +3 &> /dev/null
	printf "%s\n" "Shutting down in 3 minutes..."
	MSG="Type 'C' to cancel, or 'N' to shutdown now: "
	read -n 1 -e -p "$MSG" SHUTDOWN_PROMPT
	case "${SHUTDOWN_PROMPT:-EMPTY}" in
		[Cc])
			/sbin/shutdown --no-wall -c
			exit 0 ;;
		[Nn])
			/sbin/shutdown --no-wall now ;;
		EMPTY|*)
			printf "%s\n" "Incorrect response. Quitting." 1>&2
			exit 1 ;;
	esac
fi

if [ "$SUSPEND" == "true" ]; then
	/bin/sync
	printf "%s\n" "System will suspend in 3s; type Ctrl+C to cancel."
	/bin/sleep 3

	if [ -x /bin/systemctl ]; then
		/bin/systemctl suspend
	elif [ -x /usr/sbin/pm-suspend ]; then
		/usr/sbin/pm-suspend
	else
		XERR "$LINENO" "Unable to find a supported suspend method."
	fi
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
