#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/get-all-locales
# Started On        - Wed 22 Nov 16:23:38 GMT 2017
# Last Change       - Wed 10 Jan 21:00:25 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Simple little script to install all language packs on Ubuntu-based systems, -
# but omit conflicts. Came about because of this thread:
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=256699
#----------------------------------------------------------------------------------

PKGS=$(
	while read -a X; do
		for C in\
		\
			ast b{g,s} c{a,s} d{a,e} e{l,n,s,u} f{i,r} g{d,l} h{e,r,u}\
			i{d,t} ja ko\h l{t,v} ms n{b,l} oc p{a,l,t} r{o,u}\
			s{k,l,r,v} tr u{g,k}
		{
			[ "${X[0]}" == "language-pack-$C" ] && printf "${X[0]} "
		}
	done <<< "$(/usr/bin/apt-cache search "^language-pack")"
)

/usr/bin/apt-get install -qq --show-progress $PKGS

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
