#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/getcfc
# Started On        - Thu 23 Nov 14:44:50 GMT 2017
# Last Change       - Sun 12 May 22:17:53 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-12"
_PROJECT_="${0##*/}"

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

DOM="https://archive.org/"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Download many classic ISO images contained a bundle of PC games.

		SYNTAX:     $_PROJECT_ [OPTS] DISC_NUMBER

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       Where DISC_NUMBER is a zero-padded number between 01 and 60. Sadly, -
		            discs 17 and 47 are missing.

		SITE:       ${DOM%\/}
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		-*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

[ -x /usr/bin/wget ] || FAIL 1 "$LINENO" "Dependency '/usr/bin/wget' not met."

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VER_LINE <<< "$(wget --version)"
[ 0${WGET_VER_LINE[2]//[!0-9]} -ge 01192 ] && NOWARC="--no-warc-compression"

[ "$*" ] || FAIL 1 "$LINENO" "Specifiy at least one CD to download."

[ "$BEQUIET" == "true" ] && exec > /dev/null
[ "$DEBUGME" == "true" ] && set -x

URL="download/cdrom-classic-fond"

for SEL in $@; {
	if ! [[ "$SEL" == [0-9][0-9] ]]; then
		FAIL 0 "$LINENO" "Specified ISO '$SEL' is invalid."
		continue
	fi

	wget -qc --show-progress $NOWARC "$DOM${URL}-${SEL}/ClassicFond${SEL}.iso"
}

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
