#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/ghipc (GitHub IP Check)
# Started On        - Wed 14 Feb 18:30:38 GMT 2018
# Last Change       - Wed 14 Feb 21:11:52 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }

[ -x /usr/bin/wget ] || XERR "$LINENO" "Dependency '/usr/bin/wget' not met."

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            GHIPC - GitHub IP Check (14th February 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Check the validity of IP addresses of GitHub servers.

		SYNTAX:     ghipc [OPT] IP1 IP2 IP3 ...
		
		OPT:        --help|-h|-?            - Displays this help information.

		SITE:       https://api.github.com/meta
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac

	shift
done

IP_LIST="$@"

[ "$IP_LIST" ] || XERR "$LINENO" "No IP addresses were provided."

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VERSION_LINE <<< "$(/usr/bin/wget --version)"
if [ 0${WGET_VERSION_LINE[2]//[!0-9]} -ge 01192 ]; then
	XERR "$LINENO" "Your version of wget is currently unsupported."
fi

URL='https://api.github.com/meta'

while read LINE; do
	BUFFER="${LINE//[!0-9.\/]}"

	for IP in $IP_LIST; {
		if [ "${BUFFER%\/*}" == "$IP" ]; then
			printf "MATCH: %s\n" "${BUFFER%\/*}"
		fi
	}
done <<< "$(/usr/bin/wget -q "$URL" -O -)"

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
