#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/ghipc (GitHub IP Check)
# Started On        - Wed 14 Feb 18:30:38 GMT 2018
# Last Change       - Sun 12 May 23:48:59 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-12"
_PROJECT_="${0##*/}"

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

URL='https://api.github.com/meta'

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} - GitHub IP Check ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Check the validity of IP addresses of GitHub servers.

		SYNTAX:     $_PROJECT_ [OPT] IP1 IP2 IP3 ...

		OPT:        --help|-h|-?            - Displays this help information.
		            --version|-v            - Output o ly the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.

		SITE:       $URL
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		-*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

IP_LIST="$@"

if ! type -fP wget > /dev/null 2>&1; then
	FAIL 1 "$LINENO" "Dependency 'wget' not met."
fi

read -a WGET_VER_LINE <<< "$(wget --version)"
WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
	NOWARC="--no-warc-compression"
fi

[ "$IP_LIST" ] || FAIL 1 "$LINENO" "No IP addresses were provided."

[ "$DEBUGME" == "true" ] && set -x

while read LINE; do
	BUFFER="${LINE//[!0-9.\/]}"
	for IP in $IP_LIST; {
		if [ "${BUFFER%\/*}" == "$IP" ]; then
			printf "MATCH: %s\n" "${BUFFER%\/*}"
		fi
	}
done <<< "$(wget $NOWARC -q "$URL" -O -)"

