#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/isbatlow
# Started On        - Sun  8 Apr 20:47:08 BST 2018
# Last Change       - Sun 12 May 22:51:50 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-12"
_PROJECT_="${0##*/}"

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

DOM="https://github.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Simple utility for laptops, to check if the battery is low.

		SYNTAX:     $_PROJECT_ [OPTS] [CMD]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
		            --interval|-I N         - Set the check interval,in seconds, to N.
		            --limit|-L N            - Set the battery percentile limit to N.
		            --battery|-B BAT        - Where BAT is the battery to watch.

		NOTE:       Where CMD is one or more commands to run upon the battery limit being
		            detected, which is by default 15%, remaining.

		SITE:       $DOM/terminalforlife/Extra
	EOF
}

BATTERY="battery_BAT0"
declare -i INTERVAL=30
declare -i LIMIT=15

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--interval|-I)
			shift
			if [[ "$1" =~ ^[0-9]+$ ]] && [ $1 -gt 0 ]; then
				LIMIT=$1
			else
				FAIL 1 "$LINENO" "Invalid interval specified."
			fi ;;
		--limit|-L)
			shift
			if [[ "$1" =~ ^[0-9]+$ ]]\
			&& [ $1 -gt 0 -a $1 -lt 100 ]; then
				LIMIT=$1
			else
				FAIL 1 "$LINENO" "Invalid limit specified."
			fi ;;
		--battery|-B)
			shift
			if ! [ "$1" ]; then
				FAIL 1 "$LINENO" "Missing battery specification."
			else
				BATTERY="$1"
			fi ;;
		-*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

CMD="$@"

declare -i DEPCOUNT=0
for DEP in notify-send on_ac_power wget sleep; {
	if ! type -fP "$DEP" > /dev/null 2>&1; then
		FAIL 0 "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ "$DEBUGME" == "true" ] && set -x

if ! on_ac_power; then
	while IFS=":" read -a X; do
		if [ "${X[0]// }" == "percentage" ]; then
			if ! [[ "${X[1]// }" =~ ^[0-9]+%$ ]]; then
				notify-send --urgency=critical\
					"Unable to get valid battery value."
				FAIL 0 "$LINENO" "Unable to get valid percentile."
			else
				if [ ${X[1]%\%} -le $LIMIT ]; then
					notify-send --urgency=critical\
						"Battery is critically low!"

					($CMD)
				fi
			fi

			break
		fi
	done <<< "$(upower -i /org/freedesktop/UPower/devices/$BATTERY)"
	sleep ${INTERVAL}s
fi

