#!/bin/bash
clear

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/jotd (Joke of the Day)
# Started On        - Fri  2 Mar 13:27:44 GMT 2018
# Last Change       - Fri  2 Mar 13:52:02 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

[ -x /usr/bin/wget ] || XERR "$LINENO" "Dependency '/usr/bin/wget' not met."

DOM="http://jokes.cc.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            JOTD - JOKE OF THE DAY (2nd March 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Display a Joke of the Day on your terminal.

		SYNTAX:     jotd [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
[ 0${WGET_VER_LINE[2]//[!0-9]} -ge 01192 ] && NOWARC="--no-warc-compression"

[ "$DEBUGME" == "true" ] && set -xeu

while IFS=">" read -a X; do
	if [ "${X[1]}" == '<div class="module_content"' ]; then
		printf "%s\n" ${X[@]}
	fi
done < $HOME/Desktop/testdata #<<< "$(/usr/bin/wget -q $NOWARC -t 1 $DOM -O -)"

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
