#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/jotd (Joke of the Day)
# Started On        - Fri  2 Mar 13:27:44 GMT 2018
# Last Change       - Sun  4 Mar 20:40:25 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2018-03-04"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

DOM="http://jokes.cc.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            JOTD - JOKE OF THE DAY ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Display a Joke of the Day on your terminal.

		SYNTAX:     jotd [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       These jokes may or may not be tasteful!

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in /usr/bin/{wget,fold,tput}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

# Newer versions of wget by default request unwanted server-side compression.
read -a WGET_VER_LINE <<< "$(/usr/bin/wget --version)"
[ 0${WGET_VER_LINE[2]//[!0-9]} -ge 01192 ] && NOWARC="--no-warc-compression"

[ "$DEBUGME" == "true" ] && set -xeu

while read X; do
	#TODO - Fix possible issue with joke containing a '>' character.
	if [[ "$X" =~ ^\<div\ class\=\"module_content\"\> ]]; then
		B="${X%</span>*}"
		B="${B/*>}"
		COLS=`/usr/bin/tput cols`
		/usr/bin/fold -sw ${COLS} <<< "$(printf "%s\n" "$B")"
		break
	fi
done <<< "$(/usr/bin/wget -q $NOWARC -t 1 $DOM -O -)"
#TODO - If it's already known what today's joke is, why contact the servers to
#       check for a new one? Fix this using a /tmp file, at the very least.

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
