#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/jotd (Joke of the Day)
# Started On        - Fri  2 Mar 13:27:44 GMT 2018
# Last Change       - Fri  2 Mar 13:29:31 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in PATH; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            JOTD - JOKE OF THE DAY (2nd March 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Display a Joke of the Day on your terminal.

		SYNTAX:     example [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.

		SITE:       http://jokes.cc.com
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$DEBUGME" == "true" ] && set -xeu



# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
