#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/lnldl
# Started On        - Fri  6 Oct 00:23:23 BST 2017
# Last Change       - Fri  6 Oct 00:23:37 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# Quickly and easily download Late Night Linux podcasts.

XERR(){ echo "[L${1}] ERROR: $2" 1>&2; exit 1; }
ERR(){ echo "[L${1}] ERROR: $2" 1>&2; }

DEPCOUNT=0
for DEP in /usr/bin/id /usr/bin/seq /usr/bin/wget; {
	[ -x "$DEP" ] || {
		ERR "Dependency '$DEP' not met."
		DEPCOUNT=$(( DEPCOUNT + 1 ))
	}
}

[ `/usr/bin/id -u` -eq 0 ] && { XERR "Don't run as root."; }

LINK="http://podtrac.com/pts/redirect.mp3/latenightlinux.com/media"

for OGG in `/usr/bin/seq -w 1 21`; {
	/usr/bin/wget --continue --quiet --show-progress\
		"$LINK/LNL${OGG}.ogg" -O ./Episode_${OGG}.ogg || {
		XERR "Non-zero exit status: $OGG"
	}
}
