#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - lsbins
# Started On        - Sat 16 Sep 21:34:24 BST 2017
# Last Change       - Fri 26 Apr 14:41:14 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-04-26"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
        while read; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            LSBINS ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Simple shell program to list and describe the PATH executables.

		SYNTAX:     lsbins [OPT]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --force-all             - Disregard whether man can be descriptive.

		NOTE:       Parses man(1) for the descriptions.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--force-all)
			DEVNULL="false" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in /usr/bin/{man,sort,uniq,find} /bin/sed; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

MAIN(){
	BUFFER=$(
		/usr/bin/find ${PATH//:/ } -maxdepth 1 -type f -executable\
			-exec /usr/bin/man -f "{}" \+\
	)

	printf "%s\n" "$BUFFER"\
		| /bin/sed 's/^\(.*\)\s([1-8])\s\+-\s\+\(.*\)$/\1 - \2/'\
		| /usr/bin/uniq -f 2\
		| /usr/bin/sort -k 1
}

case "$DEVNULL" in
	false)
		MAIN ;;
	*)
		MAIN 2>&-; exit 0 ;;
esac

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
