#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - medlog
# Started On        - Fri 18 Nov ??:??:?? BST 2016
# Last Change       - Mon 18 Sep 14:42:51 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ echo "ERROR: $1" 1>&2; exit 1; }
ERR(){ echo "ERROR: $1" 1>&2; }

DEPCOUNT=0
for DEP in /usr/bin/{xmessage,paplay,cut,tr,tail,notify-send} /bin/{date,mkdir}
{
	if ! type -P "$DEP" &> /dev/null
	then
		ERR "Dependency '$DEP' not met."
		let DEPCOUNT++
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $UID -eq 0 ] && XERR "Root access not required."

MAINDIR="$HOME/.medlog"
[ -d "$MAINDIR" ] || /bin/mkdir --parents "$MAINDIR"
LOGFILE="$MAINDIR/medlog.log"
[ -f "$LOGFILE" ] || > "$LOGFILE"
[ -w "$LOGFILE" ] || XERR "File '${LOGFILE//*\/}' has no write access."
NOTIFILE="$MAINDIR/notify.ogg"

LAST_LOG=$(
	/usr/bin/tail -n 1 "$LOGFILE"\
		| /usr/bin/tr -s " "\
		| /usr/bin/cut -d " " -f 1-3
)

TODAY_DATE=`/bin/date +%a\ %d\ %b`
MSG="Medication taken today, $USER?"
MSG_NO="Take medication, then reload medlog."

if [ "${TODAY_DATE// /}" == "${LAST_LOG// /}" ]
then
	/usr/bin/notify-send "Medication already taken today."
else
	/usr/bin/paplay "$NOTIFILE"
	
	ANSWER=$(/usr/bin/xmessage -buttons yes,no -center "$MSG" -print)
	
	case "$ANSWER"
	in
		no)
			/usr/bin/notify-send "$MSG_NO"
			exit 1 ;;
		yes)
			/bin/date "+%a %d %b %X %Z %Y" >> "$LOGFILE" ;;
	esac
fi
