#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/medlog
# Started On        - Fri 18 Nov ??:??:?? BST 2016
# Last Change       - Thu 21 Dec 10:13:44 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Need help taking and logging when you've had your medication? Me too. That's why
# I wrote this ages ago. It was my first "big" project; quite proud of it, even if
# it's quite simple and I could certainly do a better job of it now. Hope it helps.
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/{xmessage,paplay,notify-send} /bin/mkdir; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $UID -eq 0 ] && XERR "$LINENO" "Root access not required."

MAINDIR="$HOME/.medlog"
[ -d "$MAINDIR" ] || /bin/mkdir --parents "$MAINDIR"
LOGFILE="$MAINDIR/medlog.log"
[ -f "$LOGFILE" ] || > "$LOGFILE"
[ -w "$LOGFILE" ] || XERR "$LINENO" "File '${LOGFILE//*\/}' has no write access."
NOTIFILE="$MAINDIR/notify.ogg"

#TODO - Is there a more efficient way to do this? (pure-shell)
while read -a X; do
	printf -v LAST_LOG "%s\n" "${X[0]}"
done < "$LOGFILE"

printf -v TODAY_DATE "%(%F (%X))T" "-1"
MSG="Medication taken today, $USER?"
MSG_NO="Take medication, then reload medlog."

if [ "${TODAY_DATE%/*}" == "${LAST_LOG%/*}" ]; then
	/usr/bin/notify-send "Medication already taken today."
else
	/usr/bin/paplay "$NOTIFILE"
	
	ANSWER=$(/usr/bin/xmessage -buttons yes,no -center "$MSG" -print)
	
	case "$ANSWER" in
		no)
			/usr/bin/notify-send "$MSG_NO"
			exit 1 ;;
		yes)
			printf "%(%F (%X))T\n" "-1" >> "$LOGFILE" ;;
	esac
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
