#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/mfw (Mint Forum Watch)
# Started On        - Sun 21 Jan 14:15:13 GMT 2018
# Last Change       - Sun 21 Jan 16:24:37 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# As I frequent the Mint forums so often, in an effort to help people, it'd be
# helpful to me if I can be apprised of no-reply thread posts in the Newbie
# Questions forums. This small program does just that; designed to run in the
# background.
#
# Run with "mfw N", where N is the number of minutes in which to check.
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/{notify-send,wget}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $# -ne 1 ] && XERR "$LINENO" "Only one argument is valid."
[ "$1" ] || XERR "$LINENO" "No interval time was given."

URL='https://forums.linuxmint.com/viewforum.php?f=90'
REGEX='\?f=90\&amp\;t=[0-9]+\&amp;sid=[0-9a-z]+\"\sclass=\"topictitle\">.*<'
FILTER=(83444 83314 81997 97158 245700 230142 219089 224270)

while :; do
	PARSE(){
		while IFS=">" read -a X; do
			if [[ "${X[*]}" =~ class=\"posts\"\ [0-9]+\ \< ]]; then
				T_REP="${X[1]//[!0-9]}"
				[ $T_REP -eq 0 ] || continue
			elif [[ "${X[*]}" =~ class=\"topictitle\" ]]; then
				IFS=";" read -a Y <<< "${X[0]/*<a href=}"
				T_ID="${Y[1]//[!0-9]}"
				T_STR="${X[1]%</a}"
	
				for Z in ${FILTER[@]}; {
					[ "$Z" == "$T_ID" ] && continue 2
				}
	
				printf "%6d[%0.2d]: %s\n" "$T_ID" "$T_REP" "$T_STR"
			fi
		done <<< "$(/usr/bin/wget -q "$URL" -O -)"
	}

	while read -a R; do
		BUF="${R/???????}"

		if [ "${BUF:0:2}" == 00 ]; then
			/usr/bin/notify-send "${R[*]}"
		fi
	done <<< "$(PARSE)"

	/bin/sleep ${1}m
done
