#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/mif-completion
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat  7 Apr 18:56:08 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for mif.
#----------------------------------------------------------------------------------

_arg_list_mif(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case "${X[0]}" in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD="${X[0]/OPTS:}"
	done <<< "$(/usr/bin/mif -h)"
}

_option_mif(){
	COMPREPLY=($(compgen -W "$(_arg_list_mif)" -- "$2"))
}

complete -F _option_mif mif
