#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/mountwatch
# Started On        - Thu  9 Nov 14:33:34 GMT 2017
# Last Change       - Thu  9 Nov 15:25:56 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# This is a somewhat rudimentary script to watch for and notify when a device is
# connected, disconnected, or mounted. Sadly no unmount notifications, yet. Run
# this at startup. It works a bit like a daemon.
#
# Wrote this specifically for use with dunst.

#----------------------------------------------------------------------------------

#trap "" HUP TERM INT

#TODO - Ignore the entries already there on log-in.
while :; do
	[ -x /usr/bin/notify-send -a -x /bin/dmesg ] || exit 1

	while read X; do
		[[ "$X" =~ (mount|unmount|disconnect|detected) ]] && LAST="$X"
	done <<< "$(/bin/dmesg -tl 6)"

	if ! [ "$LAST" == "$LAST_BUFFER" ]; then
		printf -v NS "[%(%F_%X)T]: %s" "-1" "$LAST"

		if ! [ "$BUF" == "$NS" ]; then
			/usr/bin/notify-send --urgency=critical "$NS"
		fi
	fi

	LAST_BUFFER="$LAST"
done
