#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/mplay
# Started On        - Sat 16 Sep 19:42:57 BST 2017
# Last Change       - Thu  9 May 20:59:47 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

THEMEDIR="/usr/share/moc/themes"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            MPLAY ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            MOC Wrapper for a clean layout with a subtle transparent theme.

		SYNTAX:     mplay [OPTS] PATH

		OPTS:       --help|-h|-?            - Displays this help information.
		            --run-once|-o           - Exit the MOC server when closed.

		NOTE:       Where PATH is the location in which music is found.

		            The following directory is expected by default:

		              $THEMEDIR

		            The default theme used is the tfl_moc_theme, found at the above GitHub
		            address, in the Extra repository.

		            The latest version of mplay includes this theme, however.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--once|-o)
			ONCE="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

[ "$1" -a ! -d "$1" ] && XERR "$LINENO" "Unable to find the given music directory."

[ -d $THEMEDIR ] || XERR "$LINENO" "Theme directory not found."
[ -f "$THEMEDIR/tfl_moc_theme" ] || XERR "$LINENO" "Theme file not found."

[ -x '/usr/bin/mocp' ] || XERR "$LINENO" "Dependency '/usr/bin/mocp' not met."

/usr/bin/mocp -n -T "$THEMEDIR/tfl_moc_theme"     \
	-O ShowFormat=yes                         \
	-O ShowTime=no                            \
	-O Shuffle=no                             \
	-O HideFileExtension=yes                  \
	-O SavePlaylist=no                        \
	-O TagsCacheSize=3000                     \
	-O PlaylistNumbering=yes                  \
	-O Layout1="playlist(50%,50%,50%,50%)"    \
	-O FollowPlayedFile=yes                   \
	-O ModPlug_NoiseReduction=yes             \
	-O ModPlug_ResamplingMode=FIR             \
	-O CanStartInPlaylist=yes                 \
	-O ResampleMethod=SincMediumQuality       \
	-O UseMimeMagic=no                        \
	-O ShowHiddenFiles=no                     \
	-O InputBuffer=512                        \
	-O OutputBuffer=512                       \
	-O Prebuffering=256                       \
	-m "${1:-$HOME/Music}"                    \
|| XERR "$LINENO" "Unable to start the MOC player."

if [ "$ONCE" == "true" ]; then
	wait; /usr/bin/mocp -x
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
