#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/mplay
# Started On        - Sat 16 Sep 19:42:57 BST 2017
# Last Change       - Fri 19 Apr 15:18:42 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-04-19"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

THEMEDIR="/usr/share/moc/themes"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            MPLAY ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Simple script to allow me to quickly load MOC how I like.

		SYNTAX:     mplay [OPTS] PATH

		OPTS:       --help|-h|-?            - Displays this help information.
		            --theme-path|-T         - Set a custom theme directory path.
		            --notify|-N             - Send track info notifications.
		            --run-once|-o           - Exit the MOC server when closed.

		NOTE:       Where PATH is the location in which music is found.

		            The following directory is expected by default:

		              $THEMEDIR

		            The default theme used is the tfl_moc_theme, found at the above GitHub
		            address. You can install it with insit, if not already done so:

		              sudo insit tfl_moc_theme

		            The latest version of mplay includes this theme, however.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--theme-path|-T)
			shift
			THEMEDIR="$1"

			if ! [ -d "$THEMEDIR" ]; then
				XERR "$LINENO" "Unable to find the theme directory."
			fi ;;
		--notify|-N)
			NOTIFY="true" ;;
		--once|-o)
			ONCE="true" ;;
		-*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not required."

if [ -n "$1" ]; then
	[ -d "$1" ] || XERR "$LINENO" "Unable to find the given music directory."
fi

if [ "$NOTIFY" == "true" ]; then
	# This uses a small script from my i3config repository; you can use that
	# even if you don't use i3-wm! Just point this path to the script, -
	# wherever you want it.
	COMMAND="/bin/bash $HOME/.i3a/track_notify"
else
	COMMAND=":"
fi

[ -d $THEMEDIR ] || XERR "$LINENO" "Theme directory not found."
[ -f "$THEMEDIR/${THEME:-tfl_moc_theme}" ] || XERR "$LINENO" "Theme file not found."

if [ -x /usr/bin/mocp ]; then
	/usr/bin/mocp -n -T $THEMEDIR/${THEME:-red_theme} \
		-O ShowFormat=yes                         \
		-O ShowTime=no                            \
		-O Shuffle=yes                            \
		-O HideFileExtension=yes                  \
		-O SavePlaylist=no                        \
		-O TagsCacheSize=3000                     \
		-O PlaylistNumbering=yes                  \
		-O Layout1="playlist(50%,50%,50%,50%)"    \
		-O FollowPlayedFile=yes                   \
		-O ModPlug_NoiseReduction=yes             \
		-O ModPlug_ResamplingMode=FIR             \
		-O OnSongChange="$COMMAND"                \
		-O CanStartInPlaylist=yes                 \
		-O ResampleMethod=SincMediumQuality       \
		-O UseMimeMagic=no                        \
		-O ShowHiddenFiles=no                     \
		-O InputBuffer=512                        \
		-O OutputBuffer=512                       \
		-O Prebuffering=256                       \
		-m "${1:-$HOME/Music}"                    \
	|| XERR "$LINENO" "Unable to start the MOC player."

	if [ "$ONCE" == "true" ]; then
		wait; /usr/bin/mocp -x
	fi
else
	XERR "$LINENO" "Dependency '/usr/bin/mocp' and/or '/sbin/alsa' not met."
fi

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
