#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/noprtscr (No Print Screen)
# Started On        - Sun 21 Jan 18:30:36 GMT 2018
# Last Change       - Sun 21 Jan 18:30:51 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A small script to hopefully remedy this issue:
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=152887
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
[ -x /usr/bin/gsettings ] || XERR "$LINENO" "Dependency '/usr/bin/gsettings' not met."

SCHEMA="org.gnome.settings-daemon.plugins.media-keys"
for KEY in {{window,area}-screenshot,screenshot}{,-clip}; {
	if ! /usr/bin/gsettings "$SCHEMA" "$KEY" Null; then
		XERR "$LINENO" "Unable to clear: $KEY"
	fi
}
