#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/noprtscr (No Print Screen)
# Started On        - Sun 21 Jan 18:30:36 GMT 2018
# Last Change       - Tue  5 Nov 15:00:05 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A small script to remedy this issue in Linux Mint 18.3 with Cinnamon:
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=152887
#
# Also enable the exra feature (launch the Menu with PrtSc) with:
#
# OPTS:       --version|-v            - Output only the version datestamp.
#             --prtsc-is-menu         - Use PrtSC to launch the Mint Menu.
#----------------------------------------------------------------------------------

_VERSION_="2019-11-05"
_PROJECT_="${0##*/}"

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

if ! type -fP gsettings > /dev/null 2>&1; then
	FAIL 1 "$LINENO" "Dependency 'gsettings' not met."
fi

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			printf "USAGE: %s [[--help|-h|-?] | [--version|-v]] | [--prtsc-is-menu]\n" "$_PROJECT_" ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--prtsc-is-menu)
			# Feature the OP in the thread requested.
			SCHEMA="com.linuxmint.mintmenu"
			if ! gsettings set "$SCHEMA" hot-key "Print" 2> /dev/null; then
				FAIL 1 "$LINENO" "Unable to set 'hot-key' to 'Print' in: $SCHEMA"
			fi ;;
		*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

SCHEMA="org.cinnamon.desktop.keybindings.media-keys"
for KEY in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
	if ! gsettings set "$SCHEMA" "$KEY" "[]" 2> /dev/null; then
		FAIL 1 "$LINENO" "Unable to clear: $KEY"
	fi
}

