#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/noprtscr (No Print Screen)
# Started On        - Sun 21 Jan 18:30:36 GMT 2018
# Last Change       - Sun 21 Jan 21:44:32 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A small script to remedy this issue:
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=152887
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
[ -x /usr/bin/gsettings ] || XERR "$LINENO" "Dependency '/usr/bin/gsettings' not met."

SCHEMA="org.cinnamon.desktop.keybindings.media-keys"

for KEY in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
	if ! /usr/bin/gsettings set "$SCHEMA" "$KEY" "[]"; then
		XERR "$LINENO" "Unable to clear: $KEY"
	fi
}

# Added feature the OP in the aforementioned thread requested.
if [ "$1" == "--prtsc-is-menu" ]; then
	/usr/bin/gsettings set org.linuxmint.mintmenu hot-key "Super_L"
fi
