#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/pagewatch
# Started On        - Wed 18 Oct 19:27:40 BST 2017
# Last Change       - Thu 19 Oct 13:24:06 BST 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

# This came to be because I got excited and impatient waiting for Ubuntu 17.10 to
# be released and therefor available on the Ubuntu website.
#
# I devised a simple way to quickly and automatically check for changes on a given
# webpage, which for me was the download page, where I had hoped to see the new
# 17.10 download link.

#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /bin/sleep /usr/bin/{md5sum,wget}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

shopt -s extglob

USAGE(){
	while read -r; do
		echo "$REPLY"
	done <<-EOF
		            PAGEWATCH (19th October 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Watch a webpage for signs of change by checkings its md5sum.

		SYNTAX:     pagewatch [OPTS] URL COMMANDS
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --interval|-i N         - Check for changes every N seconds. The
		                                      default is to check every 60 seconds.

		NOTE:       Where COMMANDS would be your command(s) to execute upon detection of
		            any changes to the specified webpage. See below for examples.

		EXAMPLE:
		            pagewatch --interval 10m "https://www.ubuntu.com" notify-send "Ready!"

		CAVEAT:     Some webpages update so frequently that pagewatch would for them be
		            no use. Such pages tend to have content like counters or timers.
	EOF
}

while [ -n "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--interval|-i)
			shift; INTERVAL="$1" ;;
		-*|--*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac

	shift
done

URL="$1"

shift

COMMANDS="$@"

[ -z "$URL" ] && XERR "$LINENO" "A webpage address (URL) is required."

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

BUFFER="/tmp/pagewatch_`printf '%(%F_%X)T'`.md5"
[ -d /tmp ] || XERR "$LINENO" "Directory /tmp is missing or inaccessible."

/usr/bin/wget -q "$URL" -O - | /usr/bin/md5sum > "$BUFFER" 2> /dev/null

declare -i COUNT=0
while :; do
	/usr/bin/wget -q "$URL" -O -\
		| /usr/bin/md5sum -c "$BUFFER" &> /dev/null || ($COMMANDS)

	COUNT+=1

	printf "CHECK[#%0.4d]: %(%F_%X)T\n" "$COUNT"

	/bin/sleep "${INTERVAL:-1m}"
done

[ "$DEBUGME" == "true" ] && set +xeu || exit 0
