#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/recmymood
# Started On        - Thu 28 Dec 12:20:40 GMT 2017
# Last Change       - Sun 12 May 23:40:17 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Incomplete. The general idea is to record your mood and manipulate the results.
#----------------------------------------------------------------------------------

FAIL(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			FAIL 1 "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

if ! type -fP mkdir > /dev/null 2>&1; then
	FAIL 1 "$LINENO" "Dependency '/bin/mkdir' not met."
fi

[ "$DEBUGME" == "true" ] && set -x

while read -r; do
	printf "%s\n" "$REPLY"
done <<-EOF
	How are you feeling today, $USER?

	10 + really good    :D
	 9 |
	 8 |
	 7 |
	 6 |
	 5 + okay           :|
	 4 |
	 3 |
	 2 |
	 1 |
	 0 + really bad     :(

	Enter a number which fits your mood for today. You can use a decimal point.
	If you use a decimal point, be sure to go up to .9 and no higher. For
	example, you could enter 7.8 or just 4 as a mood rating.

EOF

MAIN_DIR="$HOME/.config"
[ -d "$MAIN_DIR" ] || /bin/mkdir "$MAIN_DIR"
LOG="$MAIN_DIR/$_PROJECT_.log"

read -e -p "MOOD: " GETMOOD
if [[ "$GETMOOD" =~ ^([0-9]+|[0-9]+\.[0-9]+)$ ]]; then
	printf "%(%F_%X)T %s\n" -1 "$GETMOOD" >> "$LOG"
fi

#TODO - Add feature to average out the day's total entries, ignoring duplicates.

# vim: noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
