#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/rmne
# Started On        - Fri  6 Apr 21:27:34 BST 2018
# Last Change       - Sat  7 Apr 00:20:05 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2018-04-07"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
INFO(){ printf "INFO: %s\n" "$1"; }

[ $# -gt 0 ] && XERR "$LINENO" "This program takes no arguments."

while read -r; do
	printf "%s\n" "$REPLY"
done <<-EOF

	!! WARNING !!  +------------------------------------------------+   !! WARNING !!

	This is a small and dangerous program for the sole purpose of tearing down the
	non-essential packages, for educational, fun, or other purposes, such as setting up
	a specific type of installation.

	This program is ONLY for Debian and Ubuntu, or distributions based thereon. You'll
	likely be left with just the Debian essentials, unless your distribution has set
	some odd packages as essential, such as in Linux Lite.

	There is no 'undo' for this action. You may only be left with ONLY the dpkg
	executable, meaning you will not be able to download packages with apt-get, which
	is the very least of your problems, if you reboot.

	Specifically, packages to be removed fall under the following criteria:

	  1. They must not have the priority of standard, important, or required.
	  2. They must not be part of the KEEP variable array.
	  3. They must be part of the minimal task.

	!! WARNING !!  +------------------------------------------------+   !! WARNING !!

EOF

read -n 1 -e -p "[C]ontinue, despite the impending doom, or [q]uit? "
printf "\n"

# Packages specified in this variable array will be kept, regardless of priority.
KEEP=(
	cron systemd apparmor bash dash apt dpkg pam
	e2fsprogs util-linux libc6 mount login iptables
)

case "$REPLY" in
	[Cc])
		;;
	[Qq])
		printf "No action taken -- quitting.\n"
		exit 0 ;;
	"")
		printf "No response -- quitting.\n"
		exit 1 ;;
	*)
		printf "Unrecognised response -- quitting.\n"
		exit 1 ;;
esac

if ! [ $UID -eq 0 ]; then
	XERR "$LINENO" "Root access is required."
fi

if [ -x /usr/bin/dpkg-query ]; then
	if [ -x /usr/bin/apt-get ]; then
		INFO "Fetching list of non-essential packages."
		FORMAT='${db:Status-Abbrev} ${Priority} ${Binary:Package}\n'
		while read STATUS PRIORITY PKG; do
			MATCH='^(important|standard|required)$'
			if [ "$STATUS" == "ii" ] && ! [[ "$PRIORITY" =~ $MATCH ]]; then
				for I in ${KEEP[@]}; {
					if [ "$I" == "$PKG" ]; then
						INFO "Ignoring '$PKG' package to be kept."
						continue 2
					fi
				}

				INFO "Package '$PKG' set for initial list."
				LIST+=("$PKG")
			fi
		done <<< "$(/usr/bin/dpkg-query -Wf "$FORMAT" \*)"

		FILTERED(){
			while read -a X; do
				if [ "${X[0]}" == "Task:" ]; then
					for F in "${X[@]//,}"; {
						if ! [ "$F" == "Task:" ]; then
							printf "%s " "${F}"
						fi
					}
				fi
			done <<< "$(/usr/bin/apt-cache show $1)"
		}

		for PKG in ${LIST[@]}; {
			INFO "Checking task of '$PKG' package."
			for TASK in `FILTERED $PKG`; {
				if [ "$TASK" == "minimal" ]; then
					MINIMAL="true"
					continue 2
				fi
			}

			END_LIST+=("$PKG")
		}

		INFO "Initiating removal of final package list."
		/usr/bin/apt-get remove --purge --autoremove ${END_LIST[@]}
	else
		XERR "$LINENO" "Dependency '/usr/bin/apt-get' not met."
	fi
else
	XERR "$LINENO" "Dependency '/usr/bin/dpkg-query' not met."
fi
