#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/rssg (RSS Guardian)
# Started On        - Sun 22 Oct 23:18:41 BST 2017
# Last Change       - Tue  9 Jan 18:57:34 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is a work in progress. Not ready to be used!
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget /bin/sed; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            RSSG - RSS Guardian (9nd January 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Read RSS titles and follow their links from The Guardian.

		SYNTAX:     rssg [OPTS]
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --debug|-D              - Enables the built-in bash debugging.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		SITE:       https://www.theguardian.com
	EOF
}

while [ -n "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME="true" ;;
		--quiet|-q)
			BEQUIET="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac

	shift
done

[ $UID -eq 0 ] && XERR "$LINENO" "Root access isn't required."

[ "$BEQUIET" == "true" ] && exec 1> /dev/null
[ "$DEBUGME" == "true" ] && set -xeu

TL_LIST=$(
	local RSS_URL="https://www.theguardian.com/uk/rss"
	/usr/bin/wget -q "$RSS_URL" -O -\
		| /bin/sed '/\(<title>.*<\/title>\|<link>.*<\/link>\)/!d;
			    s/\(^\s\+\|\s\+$\)//; s/\(<\/\|<\)title>//g;
			    s/\(<\/\|<\)link>//g'
)

for ITEM in `printf "%q\n" "${TL_LIST// /%20}"`; {
	:
}
