#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - $HOME/bin/seewttr
# Started On        - Thu 21 Sep 18:53:42 BST 2017
# Last Change       - Sun 19 Nov 13:39:09 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget /bin/{sed,grep}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

USAGE(){
	while IFS= read X; do
		printf "%s\n" "$X"
	done <<-EOF
		            SEEWTTR - WTTR Look (19th November 2017)
		            Written by terminalforlife (terminalforlife@yahoo.com)
		
		            Super-simple wrapper-like script to get your weather. Thanks entirely
		            to igor_chubin for this script even being possible.

		SYNTAX:     seewttr [OPTS] LOCATION
		
		OPTS:       --help|-h|-?            - Displays this help information.
		            --current|-c            - Show only the current weather.
		
		SITE:       From whence thine weather cometh...

		              http://wttr.in

		            Source files found here...

		              https://github.com/chubin/wttr.in

		NOTE:       Format for LOCATION is, for example: town,country
	EOF
}

LOCATION=""

while [ -n "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--current|-c)
			CURRENT="true" ;;
		*)
			break ;;
	esac

	shift
done

[ -n "$*" ] && LOCATION="$*" || XERR "$LINENO" "Incorrect argument(s) specified."
[ $UID -eq 0 ] && XERR "$LINENO" "Root access is not recommended!"

declare -i LINECOUNT=0
while IFS="" read -r X; do
	[ $LINECOUNT -le 6 ] && LINECOUNT+=1 || { echo; break; }
	[[ "$X" =~ ^(Weather|New|Follow) ]] || printf "%s\n" "$X"
done <<< "$(/usr/bin/wget -q http://wttr.in/"${LOCATION}" -O -)"
