#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/swap-file
# Started On        - Sat 27 Jan 11:49:19 GMT 2018
# Last Change       - Sat 27 Jan 13:23:07 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is an early work in progress; don't yet run on your production machines!
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

declare -i DEPCOUNT=0
for DEP in /bin/{sync,grep,cp,chown,chmod,sed,dd} /sbin/{swap{on,off},mkswap}; {
	[ -x "$DEP" ] || {
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	}
}

[ $DEPCOUNT -eq 0 ] || exit 1

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            SWAP-FILE (27th January 2018)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            A simple, small tool to easily create and set up a swap file.

		SYNTAX:     swap-file [--help|-h|-?] [NAME] [SIZE]

		NOTE:       Where NAME is the swap file name to be created in /; the file name must
		            be alphanumeric and without any spaces.

		            Where SIZE is the size of the swap file to create, in MB.

		FILE:       The '/etc/fstab' file is by default edited.
	EOF
}

for ARG in $@; {
	if [[ "$ARG" =~ ^(--help|-h|-?)$ ]]; then
		USAGE; exit 0
	fi
}

FST="/etc/fstab"
NAME="/${1//[![:alnum:]]}"
SIZE="${2//[!0-9]}"

[ $# -eq 2 ] || XERR "$LINENO" "Incorrect argument(s) specified."
[[ "$SIZE" =~ [0-9]+ ]] || XERR "$LINENO" "Incorrect swap file size specified."

[ $UID -eq 0 ] || XERR "$LINENO" "Setting up a swap file requires root access."

if [ -f "$NAME" ]; then
	while read -e -p "File '$NAME' already exists -- replace? "; do
		case "$REPLY" in
			[Yy])
				break ;;
			[Nn])
				printf "No action taken -- quitting.\n"; exit 1 ;;
			*)
				XERR "$LINENO" "Invalid response. Enter 'Y' or 'N' to continue." ;;
		esac
	done
fi

printf "Creating %dMB swap file: %s\n" "$SIZE" "$NAME"
/bin/dd if=/dev/zero of="$NAME" bs=1024K count="$SIZE"
/bin/sync "$NAME"

/bin/chown -v 0:0 "$NAME"
/bin/chmod -v 600 "$NAME"
LIBBLKID_DEBUG=all /sbin/mkswap -v "$NAME"
#TODO - Why does mkswap fail here, saying it can't read the swap header? Yet when
#       I run the command separately on the terminal, all is fine.

/bin/cp -iv "$FST"{,.bak}

printf "Updating the file system table: %s\n" "$FST"
/bin/sed -i '/^UUID=.*\s.*\sswap/s/^/#/' "$FST"

if [ -f "$FST" ]; then
	if ! /bin/grep -q "/$NAME none swap sw 0 0" "$FST"; then
		printf "/%s none swap sw 0 0\n" "$NAME" >> "$FST" 1> /dev/null
	else
		XERR "$LINENO" "Current entry already present in: $FST"
	fi
else
	XERR "$LINENO" "Unable to find or access: $FST"
fi

LIBBLKID_DEBUG=all /sbin/swapoff -va
LIBBLKID_DEBUG=all /sbin/swapon -v "$NAME"
