#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/swap-file
# Started On        - Sat 27 Jan 11:49:19 GMT 2018
# Last Change       - Fri 26 Apr 14:35:54 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is an early work in progress; don't yet run on your production machines!
#----------------------------------------------------------------------------------

_VERSION_="2019-04-26"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            SWAP-FILE ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            A simple, small tool to easily create and set up a swap file.

		SYNTAX:     swap-file [OPTS] [NAME] [SIZE]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       Where NAME is the swap file name to be created in /; the file name must
		            be alphanumeric and without any spaces.

		            Where SIZE is the size of the swap file to create, in MB.

		FILE:       The '/etc/fstab' file is by default edited.
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET="true" ;;
		--debug|-D)
			DEBUGME="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

FST="/etc/fstab"
NAME="/${1//[![:alnum:]]}"
SIZE="${2//[!0-9]}"

declare -i DEPCOUNT=0
for DEP in /bin/{sync,grep,cp,chown,chmod,sed,dd} /sbin/{swap{on,off},mkswap}; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ $# -eq 2 ] || XERR "$LINENO" "Incorrect argument(s) specified."
[[ "$SIZE" =~ [0-9]+ ]] || XERR "$LINENO" "Incorrect swap file size specified."

[ $UID -eq 0 ] || XERR "$LINENO" "Setting up a swap file requires root access."

[ "$BEQUIET" == "true" ] && exec 1>&-
[ "$DEBUGME" == "true" ] && set -x

if [ -f "$NAME" ]; then
	while read -e -p "File '$NAME' already exists -- replace? "; do
		case "$REPLY" in
			[Yy])
				break ;;
			[Nn])
				printf "No action taken -- quitting.\n"; exit 1 ;;
			*)
				XERR "$LINENO" "Invalid response. Enter 'Y' or 'N' to continue." ;;
		esac
	done
fi

printf "Creating %dMB swap file: %s\n" "$SIZE" "$NAME"
/bin/dd if=/dev/zero of="$NAME" bs=1024K count="$SIZE"
/bin/sync "$NAME"

/bin/chown -v 0:0 "$NAME"
/bin/chmod -v 600 "$NAME"
LIBBLKID_DEBUG=all /sbin/mkswap -v "$NAME"
#TODO - Why does mkswap fail here, saying it can't read the swap header? Yet when
#       I run the command separately on the terminal, all is fine.

/bin/cp -iv "$FST"{,.bak}

printf "Updating the file system table: %s\n" "$FST"
/bin/sed -i '/^UUID=.*\s.*\sswap/s/^/#/' "$FST"

if [ -f "$FST" ]; then
	if ! /bin/grep -q "/$NAME none swap sw 0 0" "$FST"; then
		printf "/%s none swap sw 0 0\n" "$NAME" >> "$FST" >&-
	else
		XERR "$LINENO" "Current entry already present in: $FST"
	fi
else
	XERR "$LINENO" "Unable to find or access: $FST"
fi

LIBBLKID_DEBUG=all /sbin/swapoff -va
LIBBLKID_DEBUG=all /sbin/swapon -v "$NAME"

# vim: ft=sh noexpandtab colorcolumn=84 tabstop=8 noswapfile nobackup
