#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/tlptog
# Started On        - Fri 18 May 14:19:48 BST 2018
# Last Change       - Thu  9 May 00:59:21 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Quick shell program to toggle TLP to improve power management on portable setups.
#----------------------------------------------------------------------------------

_VERSION_="2019-05-09"

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

DOM="https://github.com"
WORK_FILE="/etc/default/tlp"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            TLPTOG ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Simple command to quickly toggle the 'TLP_ENABLE' parameter.

		SYNTAX:     tlptog [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --update|-U             - Check for updates to simplify-ubuntu.
		            --version|-v            - Output only the version datestamp.

		FILE:       $WORK_FILE

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case "$1" in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--update|-U)
			UPDATE="true" ;;
		*)
			XERR "$LINENO" "Incorrect argument(s) specified." ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in /usr/bin/wget /bin/sed; {
	if ! [ -x "$DEP" ]; then
		ERR "$LINENO" "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

if [ "$UPDATE" == "true" ]; then
	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/tlptog-version"
	LATEST=`/usr/bin/wget $NOWARC -q "$VERSION_URL" -O -`
	if [[ "${LATEST//-}" =~ ^[0-9]{8}$ ]]; then
		if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
			while read -r; do
				printf "%s\n" "$REPLY"
			done <<-EOF
				New version available:    $LATEST
				Current version:          $_VERSION_
			EOF
		fi
	else
		XERR "$LINENO" "Failed to check for available updates."
	fi

	exit 0
fi

[ $UID -eq 0 ] || XERR "$LINENO" "Root access is required for system-wide configuration."

if [ -f "$WORK_FILE" ]; then
	while IFS="=" read -a X; do
		[[ "${X[0]}" =~ ^# ]] && continue
		if [ "${X[0]}" == "TLP_ENABLE" ]; then
			if [ ${X[1]} -eq 1 ]; then
				if ! /bin/sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WORK_FILE"; then
					XERR "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
				fi
			elif [ ${X[1]} -eq 0 ]; then
				if ! /bin/sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WORK_FILE"; then
					XERR "$LINENO" "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
				fi
			else
				XERR "$LINENO" "Invalid 'TLP_ENABLE' parameter assignment."
			fi

			break
		fi
	done < "$WORK_FILE"
else
	XERR "$LINENO" "Unable to find the '$WORK_FILE' file."
fi
