#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/todo
# Started On        - Mon  2 Apr 02:04:43 BST 2018
# Last Change       - Mon  2 Apr 02:43:03 BST 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Work in progress. The idea is to write a pure-shell approach to the todo alias in
# bashconfig/.bash_aliases which displays a list of TODOs found in various files.
#
# This is for educational (fun) purposes, portability (sort of), and preference.
#----------------------------------------------------------------------------------

# Where your git repositories (directories thereof) are stored.
HUB="$HOME/GitHub/terminalforlife/Personal"

# Here, you can exclude specified repositories (directories) found in HUB. This is
# an array, so be sure to correctly quote names with spaces and special characters.
EXCLUDE=(
	swap-alert pymisc learnlinux get-uuid medlog-in-c
)

#---------------------------------------------------FETCH AND CHECK REPOSITORY LIST

REPOS=()
if [ -d "$HUB" ]; then
	declare -i NUM=0
	for DIR in $HUB/*; {
		if [ -d "$DIR" -a -d "$DIR/.git" ]; then
			REPOS+=("$DIR")
			NUM+=1
		fi
	}
fi

[ ${#REPOS[@]} -gt 0 ] && T="ies were" || T="y was"
printf "%d repositor%s found.\n" "${#REPOS[@]}" "$T"

#-----------------------------------------------------------PROCESS EACH REPOSITORY

for I in ${!REPOS[@]}; {
	for OMIT in ${EXCLUDE[@]}; {
		[ "$OMIT" == "${REPOS[I]//*\/}" ] && continue 2
	}

	printf "Checking: %s\n" "${REPOS[I]//*\/}"
}
