#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/unpack
# Started On        - Wed  8 Nov 15:41:30 GMT 2017
# Last Change       - Wed  8 Nov 17:51:26 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

XERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; exit 1; }
ERR(){ printf "[L%0.4d] ERROR: %s\n" "$1" "$2" 1>&2; }

[ -x /usr/bin/mimetype ] || XERR "$LINENO" "Dependency '/usr/bin/mimetype' not met."
[ $# -eq 0 ] && XERR "$LINENO" "Specify at least one archive."

CMD(){
	if [ -x "${1%% *}" ]; then
		$1 "$2"
		break
	fi
}

SPACE="${RANDOM}${RANDOM}"
for FILE in ${@// /$SPACE}; {
	FILE="${FILE//$SPACE/ }"

	while read -a X; do
		case "${X[@]}" in
			Tar\ archive)
				CMD "/bin/tar -xvf" "$FILE" ;;
			Tar\ archive\ \(gzip-compressed\))
				CMD "/bin/tar -xzvf" "$FILE" ;;
			Zip\ archive)
				#TODO - Fix or work around EOF error which seems to
				#       happen because of the overwrite prompt gets
				#       ignored. Could overwrite by default?
				CMD "/usr/bin/unzip" "$FILE" ;;
			RAR\ archive)
				CMD "/usr/bin/rar xv" "$FILE" ;;
			Bzip\ archive)
				CMD "/bin/bunzip2" "$FILE" ;;
			XZ\ archive)
				CMD "/bin/tar -xJvf" "$FILE" ;;
			Debian\ package)
				CMD "/usr/bin/dpkg-deb -xv" "$FILE" ;;
			7-zip\ archive)
				CMD "/usr/bin/7zr x" "$FILE" ;;
		esac
	done <<< "$(/usr/bin/mimetype -db "$FILE")"
}
