#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/csi3
#------------------------------------------------------------------------------
# Project Name      - Extra/source/csi3/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Sat 11 Sep 12:27:28 BST 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `csi3`.
#------------------------------------------------------------------------------

_csi3(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(csi3 -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	fi

	unset Option Arg Args
}

complete -F _csi3 -o default csi3
