#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - miscellaneous/001_Learn_Linux
# Started On        - Sun 19 Nov 18:31:09 GMT 2017
# Last Change       - Sun 19 Nov 19:00:19 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This file was used in one of my YouTube videos to demonstrate a pure shell and a
# couple of regular approaches to a common shell task. Here you can see how the
# performance differs, while considering things like ease-of-use and portability.
#
# SUGGESTION: Run this script with watch -n 0.1 to get an idea for its performance.
#             The watch command runs a command repeatedly, and in-place.
#
# EDIT: This never made it to YouTube, but it might do in future.
#----------------------------------------------------------------------------------

echo
time (
#            Awk can do this!     
#                   |
#              +----+-----+
#              ↓          ↓
	free | grep "^Mem:" | awk '{print $3}'
#                             ↑              ↑
#                             +------+-------+
#                                    |
#                             Cut can do this!
)

#----------------------------------------------------------------------------------

echo
time (
#       Process and parse data
#            line-by-line.
#                 |
#             +---+---+
#             ↓       ↓      
	while read -a X; do
#
#                 This replaces grep.
#                         |
#               +---------+-----------+
#               ↓                     ↓
		[ "${X[0]}" == "Mem:" ] && echo "${X[2]}"
	done <<< "$(free)" #               ↑            ↑
)                          #               +-----+------+
                           #                     |
                           #            Replaces awk or cut.

#----------------------------------------------------------------------------------

echo
time (
#                  Better use of awk
#                than the first example.
#                         |
#              +----------+-----------+
#              ↓                      ↓
	free | awk '/^Mem:/ {print $3}'
)

#----------------------------------------------------------------------------------

echo
