#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/autoexec
#------------------------------------------------------------------------------
# Project Name      - Extra/source/autoexec/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Fri 26 May 17:38:26 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for AutoExec (AE).
#------------------------------------------------------------------------------

_autoexec() {
	local Option Arg Args

	while read; do
		[[ ${REPLY:0:2} == '  ' ]] || continue

		Option=${REPLY%% - *}
		for Arg in ${Option//,/}; {
			Args+="${Arg##[^-]*} "
		}
	done <<< "$(autoexec -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	elif [[ $3 == -e || $3 == --exec ]]; then
		COMPREPLY=(`compgen -A command -- "$2"`)
	fi
}

complete -F _autoexec -o default autoexec ae
