#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - autoscrot/completion
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Wed  7 Mar 22:35:06 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for autoscrot.
#----------------------------------------------------------------------------------

_arg_list_autoscrot(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case ${X[0]} in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD=${X[0]/OPTS:}
	done <<< "$(/usr/bin/autoscrot -h)"
}

_option_autoscrot(){
	COMPREPLY=($(compgen -W "$(_arg_list_autoscrot)" -- "$2"))
}

complete -F _option_autoscrot -o default autoscrot
