#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/completions/mkpass
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 20 Apr 12:33:07 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for mkpass.
#----------------------------------------------------------------------------------

_arg_list_mkpass(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case ${X[0]} in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD=${X[0]/OPTS:}
	done <<< "$(/usr/bin/mkpass -h)"
}

_types_mkpass(){
	while read -a X; do
		if [ "${X[0]}" == "|" ]; then
			printf "%s\n" "${X[1]/VALID}"
		fi
	done <<< "$(/usr/bin/mkpass -h)"
}

_option_mkpass(){
	if [[ "$3" =~ ^(--type|-t)$ ]]; then
		COMPREPLY=($(compgen -W "$(_types_mkpass)" -- "$2"))
	else
		COMPREPLY=($(compgen -W "$(_arg_list_mkpass)" -- "$2"))
	fi
}

complete -F _option_mkpass mkpass
