#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/completions/tozero
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat 20 Apr 12:33:48 BST 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for mif.
#----------------------------------------------------------------------------------

_arg_list_tozero(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case ${X[0]} in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD=${X[0]/OPTS:}
	done <<< "$(/usr/bin/tozero -h)"
}

_option_tozero(){
	COMPREPLY=($(compgen -W "$(_arg_list_tozero)" -- "$2"))
}

complete -F _option_tozero tozero
