#!/usr/bin/env bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/completions/ubuntu-syschk
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Wed 31 Jan 12:58:24 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for ubuntu-syschk.
#----------------------------------------------------------------------------------

_arg_list_ubuntu-syschk(){
	local X

	case $1 in
		""|-*)
			while read -a X; do
				if [ "$IS_OPTS_LINE" == "true" ]\
				&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
					break
				fi

				case ${X[0]} in
					OPTS:)
						IS_OPTS_LINE="true"
						printf "%s " "${X[1]//|/ }" ;;
					-*)
						printf "%s " "${X[0]//|/ }" ;;
				esac

				local OLD=${X[0]/OPTS:}
			done <<< "$(/usr/bin/ubuntu-syschk -h)" ;;
		[a-z]*)
			while read -a X; do
				if [ "$IS_CHECKS_LINE" == "true" ]\
				&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
					break
				fi

				case ${X[0]} in
					CHECKS:)
						IS_CHECKS_LINE="true"
						printf "%s %s " "${X[1]%0|1}"{0,1} ;;
					[a-z]*)
						printf "%s %s " "${X[0]%0|1}"{0,1} ;;
				esac

				local OLD=${X[0]/CHECKS:}
			done <<< "$(/usr/bin/ubuntu-syschk -h)" ;;
	esac
}

_option_ubuntu-syschk(){
	COMPREPLY=($(compgen -W "$(_arg_list_ubuntu-syschk "$2")" -- "$2"))
}

complete -F _option_ubuntu-syschk ubuntu-syschk
