#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/ludl
#------------------------------------------------------------------------------
# Project Name      - Extra/source/ludl/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 21 Jan 23:55:30 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for LUDL.
#------------------------------------------------------------------------------

_ludl() {
	local Option Args Arg

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(ludl -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	fi
}

complete -F _ludl -o default ludl
