#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/gocheat
#------------------------------------------------------------------------------
# Project Name      - Extra/source/gocheat/completions
# Started On        - Mon  2 Mar 03:36:39 GMT 2020
# Last Change       - Thu  5 Mar 22:30:50 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `gocheat`.
#------------------------------------------------------------------------------

_gocheat(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(gocheat -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _gocheat gocheat
