#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/gocheat
#------------------------------------------------------------------------------
# Project Name      - Extra/source/gocheat/gocheat
# Started On        - Mon  2 Mar 02:11:39 GMT 2020
# Last Change       - Thu  5 Mar 22:30:59 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# WIP, but currently functional, albeit skeletal.
#
# I really love the `cheat.sh` and `cheat.sheets` repositories and so I often
# contribute a bunch of stuff, but what I sometimes find is missing, is a tool
# like `gocheat` which can parse the site and all that lovely stuff. Initially
# I began this project within Perl, but went for Shell in the end.
#
# I'd like to expand this very simple tool, so that may well happen eventually.
#
# I personally try to maintain an 80 column limit, so that we can comfortably
# view the "cheat sheets" on almost all of our terminals, sizes be damned.
# Unfortunately, however, not all comments are within bounds.
#
# Related Links:
#
# https://github.com/chubin/cheat.sh
# https://github.com/chubin/cheat.sheets
#
# Features:
#
#TODO: Add option to display a random user's contribution.
#TODO: Add option to list via commands available on site based on `PATH`.
#TODO: Add text wrapping, but only for the comments.
#TODO: Parse the 'sheets' directory through GitHub; avoids color issues.
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   libtflbp-sh (>= 2019-12-10)
#   wget (>= 1.17.1-1) | curl (>= 7.47.0-1)
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-03-05'
Progrm=${0##*/}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\rUsage: $Progrm [OPTS] [CMD]

		\r  -h, --help               - Display this help information.
		\r  -v, --version            - Output the version datestamp.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		-*)
			Err 1 'Incorrect option(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

[ $# -gt 1 ] && Err 1 'One CMD argument is valid.'
[ $# -eq 0 ] && Err 1 'Missing CMD argument.'

if command -v wget 1> /dev/null 2>&1; then
	DLoader='wget -qO - -t 3 -T 3 --max-redirect=0'
elif command -v curl 1> /dev/null 2>&1; then
	DLoader='curl -s'
else
	Err 1 "Neither 'curl' nor 'wget' were found."
fi

URL="cheat.sh/$1"

$DLoader "$URL" | while read Line; do
	case ${Line:-NULL} in
		' '*) printf '%s\n' "${Line# }" ;;
		NULL) printf '\n' ;;
		   *) printf '%s\n' "${Line# }" ;;
	esac
done
