#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/fetcher
#------------------------------------------------------------------------------
# Project Name      - Extra/source/fetcher/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 26 May 17:59:41 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for Fetcher.
#------------------------------------------------------------------------------

_fetcher() {
	local Option Arg Args ActionsFound Field Acts

	while read; do
		[[ $REPLY == \ \ [!\ ]* ]] || continue

		Option=${REPLY%% - *}
		for Arg in ${Option//,/}; {
			Args+="${Arg##[^-]*} "
		}

		if [[ $REPLY == *\ ACTIONs: ]]; then
			ActionsFound='True'
		elif [ "$ActionsFound" == 'True' ]; then
			for Field in ${REPLY%% - *}; {
				[[ "$Field" == \[*\] ]] || Acts+="$Field "
			}
		fi
	done <<< "$(fetcher -h)"

	case $2 in
		-*)
			COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
		*)
			COMPREPLY=(`compgen -W "$Acts" -- "$2"`) ;;
	esac
}

complete -F _fetcher fetcher
