#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/fetcher
#------------------------------------------------------------------------------
# Project Name      - Extra/source/fetcher/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sun 21 Feb 00:30:28 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `fetcher`.
#------------------------------------------------------------------------------

_fetcher(){
	while read; do
		if [[ $REPLY == \ \ [!\ ]* ]]; then
			local Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				local Args+="${Arg##[^-]*} "
			}

			if [[ $REPLY == *\ ACTIONs: ]]; then
				local ActionsFound='True'
			elif [ "$ActionsFound" == 'True' ]; then
				for Field in ${REPLY%% - *}; {
					[[ "$Field" == \[*\] ]] || local Acts+="$Field "
				}
			fi
		fi
	done <<< "$(fetcher -h)"
	unset Arg

	case $2 in
		-*)
			COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
		*)
			COMPREPLY=(`compgen -W "$Acts" -- "$2"`) ;;
	esac
}

complete -F _fetcher fetcher
