#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/cito
#------------------------------------------------------------------------------
# Project Name      - Extra/source/cito/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Mon 11 Jan 23:59:53 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `cito`.
#------------------------------------------------------------------------------

_cito(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(cito -h)"

	if [[ $2 == '-'* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	else
		COMPREPLY=(`compgen -o default -- "$2"`)
	fi

	unset Option Arg Args
}

complete -F _cito cito
