#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/lspkg
#------------------------------------------------------------------------------
# Project Name      - Extra/source/lspkg/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 21 Jan 23:53:07 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for LSPKG, including lspkg-set(1).
#------------------------------------------------------------------------------

_lspkg() {
	local Option Arg Args

	_pkgs() {
		if . /usr/share/bash-completion/completions/dpkg; then
			_xfunc /usr/bin/dpkg _comp_dpkg_installed_packages "$1"
		fi
	}

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$($1 -h)"

	case $1 in
		lspkg)
			case $2 in
				-*)
					COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
				*)
					COMPREPLY=(`compgen -W "$(_pkgs "$2")" -- "$2"`) ;;
			esac ;;
		lspkg-set)
			COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
	esac
}

complete -F _lspkg lspkg lspkg-set
