#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/lspkg
#------------------------------------------------------------------------------
# Project Name      - Extra/source/completions/lspkg
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Wed 12 Feb 00:11:30 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `lspkg` and `lspkg-set`.
#------------------------------------------------------------------------------

_lspkg(){
	_pkgs(){
		if . /usr/share/bash-completion/completions/dpkg; then
			_xfunc /usr/bin/dpkg _comp_dpkg_installed_packages "$1"
		fi
	}

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(${1##*/} -h)"

		case $2 in
			-*)
				COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
			*)
				if [ ${1##*/} == 'lspkg' ]; then
					COMPREPLY=(`compgen -W "$(_pkgs "$2")" -- "$2"`)
				fi ;;
		esac

	unset Option Arg Args
}

complete -F _lspkg lspkg lspkg-set
