.TH "LSPKG-SET" "8" "2020-02-11" "LSPKG-Set 2020-02-11" "LSPKG-SET"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ad l
.nh
.SH "NAME"
lspkg-set \- 
.SH "SYNOPSIS"
lspkg-set [OPTS]
.SH "DESCRIPTION"
.PP
To be written...
.SH "OPTIONS"
-h, --help
.RS 4
Display some helpful information.
.RE
.PP
-v, --version
.RS 4
Output the version datestamp.
.SH "FILES"
/var/lib/dpkg/status
.RS 4
Parsed to generate the final list of packages to remove.
.RE
.PP
/var/lib/dpkg/available
.RS 4
Parsed to ensure non-minimal packages are selected.
.RE
.PP
.SH "AUTHOR"
.PP
terminalforlife <terminalforlife@yahoo.com>
.RE
(also known as Learn Linux, over at YouTube)
.PP
.SH "BUGS"
For bug reports and other issues with LSPKG-SET, including suggestions, please report to the below GitHub link, through which the project is developed.
.PP
.RS 2
https://github.com/terminalforlife/Extra
.RE
.PP
You may also E-Mail the author of this project, but it's rarely checked.
.RE
.PP
As a last resort, however, one might simply leave a comment over at the below YouTube channel, 'Learn Linux'.
.PP
.RS 2
https://www.youtube.com/c/LearnLinux
