#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/lspkg-set
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/lspkg/lspkg-set
# Started On        - Wed 24 Jan 17:31:41 GMT 2018
# Last Change       - Tue 11 Feb 23:47:34 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-02-11'
Progrm=${0##*/}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\rUsage: $Progrm [OPTS] [PKG_1 [PKG_2] ...]

		\r  -h, --help               - Display this help information.
		\r  -v, --version            - Output the version datestamp.
		\r  -E, --essential          - Display the essential packages.
		\r  -e, --extra              - Display the extra packages.
		\r  -I, --important          - Display the important packages.
		\r  -o, --optional           - Display the optional packages.
		\r  -R, --required           - Display the required packages.
	EOF
}

[ $# -eq 0 ] && Err 1 "One argument is required -- see: $Progrm -h"

case $* in
	--help|-h|-\?)
		Usage; exit 0 ;;
	--version|-v)
		printf '%s\n' "$CurVer"; exit 0 ;;
	--essential|-E)
		Type='Essential:yes' ;;
	--extra|-e)
		Type='Priority:extra' ;;
	--required|-R)
		Type='Priority:required' ;;
	--optional|-o)
		Type='Priority:optional' ;;
	--important|-I)
		Type='Priority:important' ;;
	*)
		Err 1 'Incorrect argument(s) specified.' ;;
esac

ChkDep dpkg-query

Format="\${db:Status-Abbrev} \${${Type%:*}} \${Package}\n"

dpkg-query -Wf "$Format" \* | while read F1 F2 F3 _; do
	if [ "$F1" = 'ii' -a "$F2" = "${Type#*:}" ]; then
		New=$F3

		[ "$New" = "$Old" ] && continue
		printf '%s\n' "$New"

		Old=$New
	fi
done
