.TH "LSPKG" "1" "2020-02-11" "LSPKG 2020-02-11" "LSPKG"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ad l
.nh
.SH "NAME"
lspkg \- 
.SH "SYNOPSIS"
lspkg [OPTS] [PKG_1 [PKG_2] ...]
.SH "DESCRIPTION"
.PP
To be written...
.SH "OPTIONS"
-h, --help
.RS 4
Display some helpful information.
.RE
.PP
-v, --version
.RS 4
Output the version datestamp.
.SH "AUTHOR"
.PP
terminalforlife <terminalforlife@yahoo.com>
.RE
(also known as Learn Linux, over at YouTube)
.PP
.SH "BUGS"
For bug reports and other issues with LSPKG, including suggestions, please report to the below GitHub link, through which the project is developed.
.PP
.RS 2
https://github.com/terminalforlife/Extra
.RE
.PP
You may also E-Mail the author of this project, but it's rarely checked.
.RE
.PP
As a last resort, however, one might simply leave a comment over at the below YouTube channel, 'Learn Linux'.
.PP
.RS 2
https://www.youtube.com/c/LearnLinux
