#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - /etc/cron.hourly/APT_Update_Cron
# Started On        - Thu 19 Oct 19:02:44 BST 2017
# Last Change       - Sun 29 Oct 23:08:49 GMT 2017
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

/usr/bin/apt-get update 2>&1 > /var/log/APT_Update_Cron.log

exit 0
