#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - /etc/cron.hourly/APT_Update_Cron
# Started On        - Thu 19 Oct 19:02:44 BST 2017
# Last Change       - Wed  7 Feb 01:29:52 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

/usr/bin/apt-get update 2>&1 > /var/log/APT_Update_Cron.log

if [ -x /usr/bin/notify-send ]; then
	MESSAGE="APT package database has been updated."
	DISPLAY=:0 /usr/bin/notify-send --urgency=low "$MESSAGE"
fi

exit 0
