#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/lmc-darklight
#------------------------------------------------------------------------------
# Project Name      - Extra/source/lmc-darklight/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Fri 26 May 18:00:34 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for LMC-DarkLight.
#------------------------------------------------------------------------------

_lmc_darklight() {
	local Option Arg Args

	while read; do
		[[ ${REPLY:0:2} == '  ' ]] || continue

		Option=${REPLY%% - *}
		for Arg in ${Option//,/}; {
			Args+="${Arg##[^-]*} "
		}
	done <<< "$(lmc-darklight -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)
}

complete -F _lmc_darklight lmc-darklight
