#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/local/bin/lmc-darklight
#------------------------------------------------------------------------------
# Project Name      - Extra/source/lmc-darklight
# Started On        - Wed 23 Feb 21:40:31 GMT 2022
# Last Change       - Fri 19 May 18:01:10 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This seems to be an oft-requested feature in Linux Mint, so I thought I'd
# have a bash (pun intended) at writing something which will effectively work
# as a daemon to auto-set values based on the time of day.
#
# This is strictly for Linux Mint Cinnamon.
#
# Features:
#
#TODO: Add flag to change only backgrounds.
#TODO: Add original values to a file. Currently, it's output only.
#TODO: If configuration key is equal to null, ignore it.
#TODO: Incorporate notify-send(1).
#TODO: Incorporate Redshift, with flag/key only.
#TODO: Possibly incorproate Firefox theme changing.
#
# Bugs:
#
#TODO: Defaults themes not valid for LMDE 4.
#
# Dependencies:
#
#   bash (>= 4.4.20)
#   coreutils (>= 8.28-1ubuntu1)
#   libglib2.0-bin (>= 2.56.4-0ubuntu0.18.04.9)
#------------------------------------------------------------------------------

CurVer='2023-05-19'
Progrm='lmc-darklight'
ProgrmFancy='LMC-DarkLight'

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
		  --genconfig              - Generate new configuration file.
		  -B, --nobg               - Ignore desktop backgrounds.
		  -c, --config FILE        - Use configuration FILE instead.
		  -f, --force              - Bypass LSB and DE detection.
		  -o, --once               - Only run $ProgrmFancy once.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

MainDir="$HOME/.config/$Progrm"
Config="$MainDir/config"
OldValues="$MainDir/old_values"
Current="$MainDir/current"

ValidKeys=(
		LightCursor LightDesktop DarkBorders DarkIcons DarkControls\
		Interval LightTime DarkTime LightBorders LightIcons LightControls\
		DarkCursor DarkDesktop LightBG DarkBG
)

while [[ -n $1 ]]; do
	case $1 in
		--help|-h)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--genconfig)
			NewConfig='True' ;;
		--nobg|-B)
			NoBG='True' ;;
		--config|-c)
			if [[ -z $2 ]]; then
				Err 1 "Option '$1' requires an argument."
			else
				Config='True'
				shift
			fi ;;
		--force|-f)
			Force='True' ;;
		--once|-o)
			Once='True' ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

(( UID == 0 )) && Err 1 "Do not run as 'root' user."

DepCount=0
for Dep in mkdir gsettings sleep; do
	if ! type -P "$Dep" &> /dev/null; then
		Err 0 "Dependency '$Dep' not met."
		(( DepCount++ ))
	fi
done

(( DepCount > 0 )) && exit 1

[[ -d $MainDir ]] || mkdir -p "$MainDir"

#-----------------------------------------------Generate New Configuration File

if [[ $NewConfig == True ]]; then
	if [[ -f $Config ]]; then
		while :; do
			read -p 'File exists -- overwrite? [Y/N] '
			case ${REPLY,,} in
				y|yes)
					if [[ -w $Config ]]; then
						break
					else
						Err 1 "File '${Config/$HOME/\~}' unwritable."
					fi ;;
				n|no)
					exit 0 ;;
				'')
					Err 0 'Response required -- try again.' ;;
				*)
					Err 0 'Invalid response -- try again.' ;;
			esac
		done
	fi

	read -d '' <<-EOF
		# $ProgrmFancy configurations for Linux Mint Cinnamon.

		# How often, in seconds, to enforce these settings.
		Interval=60

		# The 24-hour time to begin setting the light and dark themes. Do not
		# zero-pad the numbers. 6am is 600 not 0600 or 06:00. Do not include
		# the colon.
		LightTime=600
		DarkTime=2000

		# Dark and light themes, relative to \`cinnamon-settings startup\`.
		LightBorders='Mint-Y'
		LightIcons='Mint-Y-Blue'
		LightControls='Mint-Y'
		LightCursor='DMZ-White'
		LightDesktop='Mint-Y'
		DarkBorders='Mint-Y'
		DarkIcons='Mint-Y-Dark-Red'
		DarkControls='Mint-Y-Dark-Red'
		DarkCursor='DMZ-Black'
		DarkDesktop='Mint-Y-Dark-Red'

		# Absolute paths to the light and dark backgrounds.
		LightBG='/usr/share/backgrounds/linuxmint/sele_ring_green.jpg'
		DarkBG='/usr/share/backgrounds/linuxmint/default_background.jpg'
	EOF

	printf "File '%s' generated.\n" "${Config/$HOME/\~}"
	printf '%s' "$REPLY" > "$Config"
	exit 0
fi

#-------------------------------------------------Check for Linux Mint Cinnamon

if [[ $Force != True ]]; then
	OSRelease='/etc/os-release'
	if [[ -f $OSRelease && -r $OSRelease ]]; then
		while IFS='=' read Key Value; do
			if [[ $Key == NAME ]]; then
				if [[ $Value == '"Linux Mint"' ]]; then
					MintFound='True'
					break
				fi
			fi
		done < "$OSRelease"
	elif type -P lsb_release &> /dev/null; then
		[[ `lsb_release -is` == Linuxmint ]] && MintFound='True'
	else
		Err 1 'Unable to determine distribution.'
	fi

	SysErr=0

	# Only Linux Mint is officially supported.
	if [[ $MintFound != True ]]; then
		Err 0 'Unable to detect a running valid Linux Mint system.'
		(( SysErr++ ))
	fi

	# This program is strictly for the Cinnamon DE.
	if ! type -P cinnamon &> /dev/null; then
		Err 0 'Unable to detect the Cinnamon desktop environment.'
		(( SysErr++ ))
	fi

	(( SysErr > 0 )) && exit 1
fi

#----------------------------------------------------Kill Old Instance if Found

if [[ -f $Current ]]; then
	[[ -r $Current ]] || Err 1 "File '$Current' unreadable."

	PID=`< "$Current"`
	kill -HUP ${PID//[![:digit:]]/} 2>&-
fi

printf 'PID: %d\n' $$
printf '%d' $$ > "$Current"

#-------------------------------------------------Fetch the Current Theme Names

Get() {
	read <<< "$(gsettings get "$2" "$3")"
	if [[ $3 == picture-uri ]]; then
		REPLY="'${REPLY#\'file:\/\/}"
	fi

	printf '%s=%s\n' "$1" "$REPLY"
}

printf 'Current values...\n'
Get Borders org.cinnamon.desktop.wm.preferences theme
Get Icons org.cinnamon.desktop.interface icon-theme
Get Controls org.cinnamon.desktop.interface gtk-theme
Get Cursor org.cinnamon.desktop.interface cursor-theme
Get Desktop org.cinnamon.theme name
Get BG org.cinnamon.desktop.background picture-uri

#------------------------Process the Configuration File and Begin the Main Loop

Info() {
	printf "Setting %b ... " "$1"

	IFS="'" read _ Value _ <<< "$(gsettings get ${1/\// })"
	if [[ $2 == $Value ]]; then
		printf '[\e[92mOK\e[0m]\n'
	else
		printf '[\e[91mERR\e[0m]\n'
	fi
}

ChkTime() {
	[[ $1 == 0* ]] && return 1
	[[ $1 =~ ^[[:digit:]]{3,4}$ ]] || return 1
}

# Usage: Set DESKTOP CONTROLS ICONS CURSOR BORDERS BG
Set() {
	gsettings set org.cinnamon.theme name "$1"
	Info 'org.cinnamon.theme/name' "$1"

	gsettings set org.gnome.desktop.interface gtk-theme "$1"
	Info 'org.gnome.desktop.interface/gtk-theme' "$1"

	gsettings set org.cinnamon.desktop.interface gtk-theme "$2"
	Info 'org.cinnamon.desktop.interface/gtk-theme' "$2"

	gsettings set org.gnome.desktop.interface icon-theme "$3"
	Info 'org.gnome.desktop.interface/icon-theme' "$3"

	gsettings set org.cinnamon.desktop.interface icon-theme "$3"
	Info 'org.cinnamon.desktop.interface/icon-theme' "$3"

	gsettings set org.cinnamon.desktop.interface cursor-theme "$4"
	Info 'org.cinnamon.desktop.interface/cursor-theme' "$4"

	gsettings set org.gnome.desktop.interface cursor-theme "$4"
	Info 'org.gnome.desktop.interface/cursor-theme' "$4"

	gsettings set org.cinnamon.desktop.wm.preferences theme "$5"
	Info 'org.cinnamon.desktop.wm.preferences/theme' "$5"

	gsettings set org.gnome.desktop.wm.preferences theme "$5"
	Info 'org.gnome.desktop.wm.preferences/theme' "$5"

	if [[ $NoBG != True ]]; then
		gsettings set org.cinnamon.desktop.background picture-uri "file://$6"
		Info 'org.cinnamon.desktop.background/picture-uri' "file://$6"
	fi
}

#---------------------------Read Configuration File, Check Time, and Set Values

while :; do
	VErrs=0
	InvalidKeys=0
	if ! [[ -f $Config ]]; then
		Err 1 "File '${Config/$HOME/\~}' not found."
	elif ! [[ -r $Config ]]; then
		Err 1 "File '${Config/$HOME/\~}' unreadable."
	else
		VErr() {
			Err 0 "$1"
			(( VErrs++ ))
		}

		# Read the configuration file to acquire values.
		while IFS='=' read Key Value; do
			[[ $Key == \#* || -z $Key ]] && continue
			Value=${Value//[\"\']}

			Found='False'
			for Valid in "${ValidKeys[@]}"; {
				if [[ $Key == $Valid ]]; then
					Found='True'
					break
				fi
			}

			if [[ $Found == True ]]; then
				printf "Found key: %s\n" "$Key"

				# Need this or similar, else invalid syntax.
				declare $Key="$Value"
			else
				Err 0 "Key '$Key' invalid."
				(( InvalidKeys++ ))
			fi
		done < "$Config"

		if [[ ! $Interval =~ ^[[:digit:]]+$ || $Interval == 0 ]]; then
			VErr "Value for 'Interval' invalid."
		fi

		ChkTime "$LightTime" || VErr "Value for 'LightTime' invalid."
		ChkTime "$DarkTime" || VErr "Value for 'DarkTime' invalid."

		for Value in {Light,Dark}{Desktop,Controls,Icons,Cursor,Borders,Time,BG}; {
			[[ -z ${!Value} ]] && VErr "Value for '$Value' not set."
		}

		if ! [[ -f $LightBG ]]; then
			VErr "File for key 'LightBG' not found."
		elif ! [[ -r $LightBG ]]; then
			VErr "File for key 'LightBG' unreadable."
		fi

		if ! [[ -f $DarkBG ]]; then
			VErr "File for key 'DarkBG' not found."
		elif ! [[ -r $DarkBG ]]; then
			VErr "File for key 'DarkBG' unreadable."
		fi
	fi

	# Begin checking the time and setting the values.
	if (( VErrs == 0 && InvalidKeys == 0 )); then
		printf 'Loop #%d ...\n' $(( ++Iter ))

		printf -v Time '%(%k%M)T' -1
		if (( Time >= LightTime && Time < DarkTime )); then
			Set "$LightDesktop" "$LightControls" "$LightIcons"\
				"$LightCursor" "$LightBorders" "$LightBG"
		elif (( Time >= DarkTime || Time < LightTime )); then
			Set "$DarkDesktop" "$DarkControls" "$DarkIcons"\
				"$DarkCursor" "$DarkBorders" "$DarkBG"
		fi
	fi

	[[ $Once == True ]] && exit 0

	sleep ${Interval:-3}s
done
