#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/nwchk
#------------------------------------------------------------------------------
# Project Name      - Extra/source/nwchk/completions
# Started On        - Wed 12 Feb 18:58:13 GMT 2020
# Last Change       - Fri 21 Jan 23:54:12 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for NWCHK.
#------------------------------------------------------------------------------

_nwchk() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(nwchk -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	#elif [[ $3 == -L || $3 == --logfile ]]; then
		#TODO: Complete this properly... somehow.
		#COMPREPLY=(`compgen -W "$(compgen -o default)" -- "$2"`)
	fi
}

complete -F _nwchk nwchk
