#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/glkfu
#------------------------------------------------------------------------------
# Project Name      - Extra/source/glkfu/completions
# Started On        - Tue  8 Dec 16:34:46 GMT 2020
# Last Change       - Fri 21 Jan 23:51:32 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for GLKFU.
#------------------------------------------------------------------------------

_glkfu() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(glkfu -h)"

	case $3 in
		-C|--config|-o|--output|-D|--build-dir)
			COMPREPLY=(`compgen -o default -- "$2"`) ;;
		*)
			COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
	esac
}

complete -F _glkfu glkfu
