#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/glkfu
#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/glkfu/completions
# Started On        - Tue  8 Dec 16:34:46 GMT 2020
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for GLKFU.
#------------------------------------------------------------------------------

_glkfu() {
	local Option Arg Args

	while read; do
		[[ ${REPLY:0:2} == '  ' ]] || continue

		Option=${REPLY%% - *}
		for Arg in ${Option//,/}; {
			Args+="${Arg##[^-]*} "
		}
	done <<< "$(glkfu -h)"

	case $3 in
		-C|--config|-o|--output|-D|--build-dir)
			COMPREPLY=(`compgen -o default -- "$2"`) ;;
		*)
			COMPREPLY=(`compgen -W "$Args" -- "$2"`) ;;
	esac
}

complete -F _glkfu glkfu
