#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/glkfu
#------------------------------------------------------------------------------
# Project Name      - Extra/source/glkfu/completions
# Started On        - Tue  8 Dec 16:34:46 GMT 2020
# Last Change       - Tue  8 Dec 16:34:49 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for `glkfu`.
#------------------------------------------------------------------------------

_glkfu(){
	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(glkfu -h)"

	COMPREPLY=(`compgen -W "$Args" -- "$2"`)

	unset Option Arg Args
}

complete -F _glkfu glkfu
