#!/usr/bin/env bash
#cito M:644 O:0 G:0 T:/usr/share/bash-completion/completions/rmne
#------------------------------------------------------------------------------
# Project Name      - Extra/source/rmne/completions
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Fri 21 Jan 23:55:14 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is the bash completion script for RMNE.
#------------------------------------------------------------------------------

_rmne() {
	local Option Arg Args

	while read; do
		if [[ $REPLY =~ ^[[:space:]]{2} ]]; then
			Option=${REPLY%% - *}
			for Arg in ${Option//,/}; {
				Args+="${Arg##[^-]*} "
			}
		fi
	done <<< "$(rmne -h)"

	if [[ $2 == -* ]]; then
		COMPREPLY=(`compgen -W "$Args" -- "$2"`)
	fi
}

complete -F _rmne rmne
