#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

LibFChk(){ #: Check for function(s) $@ existing, after sourcing library.
	FuncNum=0
	for CurFunc in "$@"; do
		GetStr=`command -v "$CurFunc"`
		if ! [ "$GetStr" = "$CurFunc" ]; then
			printf "ERROR: Unavailable '$CurFunc()' in library." 1>&2
			FuncNum=$((FuncNum + 1))
		fi
	done

	[ $FuncNum -gt 0 ] && exit 2

	unset FuncNum CurFunc
}
