#!/bin/sh
#cito M:755 O:0 G:0 T:/etc/cron.hourly/notify-upgrade
#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/cron_tasks/notify-upgrade
# Started On        - Thu 19 Oct 19:02:44 BST 2017
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# The '/etc/cron.hourly' directory might not exist, so remember to create it, -
# especially if you're installing this cron job with cito(1).
#------------------------------------------------------------------------------

{
	apt-get update && apt-get -d dist-upgrade
} 1> /tmp/notify-upgrade.log 2>&1

exit 0
