#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - roks/completion
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Wed 31 Jan 12:56:47 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for roks.
#----------------------------------------------------------------------------------

_arg_list_roks(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case "${X[0]}" in
			OPTS:)
				IS_OPTS_LINE="true"
				printf  "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD="${X[0]/OPTS:}"
	done <<< "$(/usr/bin/roks -h)"
}

_option_roks(){
	COMPREPLY=($(compgen -W "$(_arg_list_roks)" -- "$2"))
}

complete -F _option_roks roks
