#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - simwea/completion
# Started On        - Mon 29 Jan 18:47:58 GMT 2018
# Last Change       - Sat  3 Feb 20:48:50 GMT 2018
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is the bash completion script for simwea.
#----------------------------------------------------------------------------------

_arg_list_simwea(){
	local X

	while read -a X; do
		if [ "$IS_OPTS_LINE" == "true" ]\
		&& [[ "$OLD" =~ ^[A-Z]+:$ ]]; then
			break
		fi

		case ${X[0]} in
			OPTS:)
				IS_OPTS_LINE="true"
				printf "%s " "${X[1]//|/ }" ;;
			-*)
				printf "%s " "${X[0]//|/ }" ;;
		esac

		local OLD="${X[0]/OPTS:}"
	done <<< "$(/usr/bin/simwea -h)"
}

_option_simwea(){
	COMPREPLY=($(compgen -W "$(_arg_list_simwea)" -- "$2"))
}

complete -F _option_simwea simwea
