#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Thu  5 Dec 22:16:33 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

CutStr(){ # Cut string $3 by $1 delimiter, displaying $2 field(s).
	IFS=$1; shift
	Fields=$1; shift

	set -- $1

	for CutField in $Fields; do
		Count=0
		for CurField in "$@"; do
			Count=$((Count + 1))
			if [ $Count -eq $CutField ]; then
				printf "%s" "$CurField"
				break 1
			fi
		done
	done

	unset IFS Field CurField Count CutField
}
