#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Fri 13 Dec 20:25:28 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

DirName(){ #: Output the directory name (like `dirname`) of $@.
	for CurDir in "$@"; do
		if [ -d "$CurDir" ]; then
			printf 'DirName(): Non-directory specified.\n' 1>&2
			exit 126
		else
			printf '%s\n' "${CurDir%/*}"
		fi
	done
}
