#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/FirstLook
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Tue 10 Dec 02:56:10 GMT 2019
# Last Change       - Sun 15 Dec 11:48:31 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

FirstLook(){ #: Check line one of file $2 for glob $1.
	if [ $# -lt 2 ]; then
		printf "FirstLook() \$1: Glob pattern missing.\n" 1>&2
		printf "FirstLook() \$2: No file specified.\n" 1>&2
		exit 126
	fi

	if [ -f "$2" ] && [ -r "$2" ]; then
		read Line < "$2"
		case $Line in
			$1) return 0 ;;
		esac

		unset Line
		return 1
	else
		printf "FirstLook() \$2: File missing or unreadable.\n" 1>&2
		exit 126
	fi
}
