#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/FNSanityChk
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Sun 15 Dec 11:33:21 GMT 2019
# Last Change       - Sun 15 Dec 18:01:16 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

FNSanityChk(){ # Usage: FNSanityChk [FILE]
	case $1 in
		'')
			return 2 ;;
		[[:space:]]*|-*|*[[:cntrl:]]*|*\\*)
			return 1 ;;
		*)
			return 0 ;;
	esac
}
