#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/FNSanityChk
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Sun 15 Dec 11:33:21 GMT 2019
# Last Change       - Sun 15 Dec 12:15:05 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

FNSanityChk(){ # Usage: FNSanityChk [FILE_1 [FILE_2] ...]
	Num=$#
	Count=0
	while [ "$1" ]; do
		case $1 in
			[[:space:]]*|-*|*[:cntrl:]*|*\\*)
				shift ;;
			*)
				Count=$((Count + 1)) ;;
		esac
		shift
	done

	[ $Count -eq $Num ] || return 1
}
