#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/LibFChk
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sun 15 Dec 11:49:08 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

LibFChk(){ #: Check for function(s) $@ existing, after sourcing library.
	FuncNum=0
	for CurFunc in "$@"; do
		GetStr=`command -v "$CurFunc"`
		if ! [ "$GetStr" = "$CurFunc" ]; then
			printf "ERROR: Unavailable '$CurFunc()' in library." 1>&2

			printf "LibFChk() \$@: Function '$CurFunc()' missing.\n" 1>&2
			exit 126

			FuncNum=$((FuncNum + 1))
		fi
	done

	[ $FuncNum -gt 0 ] && exit 2

	unset FuncNum CurFunc GetStr
}
