#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Fri 13 Dec 20:47:12 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

YNInput(){ #: An easy-to-script prompt for the user, asking yes or no.
	if [ -z "$1" ]; then
		printf 'YNInput() $1: Prompt string required.\n' 1>&2
		exit 126
	fi

	printf '%s [Y/N] ' "$1"
	read Answer

	case $Answer in
		[Yy]|[Yy][Ee][Ss])
			return 0 ;;
		[Nn]|[Nn][Oo])
			return 1 ;;
		*)
			printf 'ERROR: Invalid response -- quitting.\n'
			exit 1 ;;
	esac

	unset Answer
}
