#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/BaseName
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sat 28 Nov 19:23:26 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

BaseName(){ #: Output the base name (like `basename`) of $@.
	for CurFile in "$@"; do
		printf "%s\n" "${CurFile##*/}"
	done
}
