#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/BaseName
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sun 15 Dec 11:47:25 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

BaseName(){ #: Output the base name (like `basename`) of $@.
	for CurFile in "$@"; do
		[ -f "$CurFile" ] || return 1
		printf "%s\n" "${CurFile##*/}"
	done
}
