#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/ChkDep
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sat 28 Nov 18:52:45 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

ChkDep(){ #: Presentable check of PATH directories for dependency $@.
	DepCount=0
	for CurDep in "$@"; do
		if [ -f "$CurDep" ]; then
			[ -x "$CurDep" ] && DepCount=$((DepCount + 1))
		else
			if command -v "$CurDep" 1> /dev/null 2>&1; then
				DepCount=$((DepCount + 1))
			fi
		fi

		if [ $DepCount -eq $((DepCount + 1)) ]; then
			Err 0 "Dependency '$CurDep' not met."
		fi
	done

	[ $DepCount -eq $# ] || return 1
}
