#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/Err
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sat 28 Nov 18:53:11 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

Err(){ #: Exit/return status [E|R]$1 (0 by default) with message $2.
	if [ -z "$1" ]; then
		printf 'Err() \$1: Exit status integer missing.\n' 1>&2
		exit 126
	elif [ -z "$2" ]; then
		printf 'Err() \$2: Message string required.\n' 1>&2
		exit 126
	elif [ $1 -lt 0 -o $1 -gt 255 ]; then
		printf 'Err() \$1: Exit status out of range.\n' 1>&2
		exit 126
	fi

	printf "ERROR: %s\n" "$2" 1>&2

	case $1 in
		E*)
			exit ${1#E} ;;
		R*)
			return ${1#R} ;;
		[0-9]*)
			exit $1 ;; # <-- For compatibility, as of 2019-12-13.
		*)
			printf 'Err() \$1: Invalid exit status.\n' 1>&2
			exit 126 ;;
	esac
}
