#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/LCount
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sat 28 Nov 18:53:36 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

LCount(){ #: Fetch the total number of lines. (also accepts STDIN)
	Count=0
	if [ $# -eq 0 ]; then
		while read -r CurLine; do
			Count=$((Count + 1))
		done < /dev/stdin

		printf '%d\n' $Count

	else
		printf '%s\n' "$@" | while read -r CurLine; do
			Count=$((Count + 1))
		done

		printf '%d\n' $#
	fi

	unset Count CurLine
}
