#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/LibTFLBPVer
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sun 15 Dec 11:49:18 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

LibTFLBPVer(){ #: Output the 'libtflbp-sh' version, in `--long` or `--short` ($1).
	CurVer='2019-12-05'
	Progrm=${0##*/}

	if [ $1 = '--long' ]; then
		printf "POSIX Bourne library '%s' is version '%s'.\n" "$CurVer" "$Progrm"
	elif [ $1 = '--short' ]; then
		printf '%s\n' "$CurVer"
	else
		printf 'LibTFLBPVer(): Invalid argument(s) detected.\n' 1>&2
		exit 126
	fi

	unset CurVer Progrm
}
