#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/OneSearch
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Tue 10 Dec 02:09:33 GMT 2019
# Last Change       - Sat 28 Nov 18:54:01 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

OneSearch(){ #: Search for glob $1 in one or more ($2 ...) files.
	Glob=$1

	if [ -z "$1" ]; then
		printf 'OneSearch() $1: String required for glob matching.\n' 1>&2
		exit 126
	fi

	shift 1

	[ $# -eq 0 ] && return 4

	for CurFile in "$@"; do
		if [ -f "$CurFile" ] && [ -r "$CurFile" ]; then
			while read CurLine; do
				case $CurLine in
					$Glob) return 0 ;;
				esac
			done < "$CurFile"

			unset CurLine Glob CurFile
			return 1
		else
			printf "OneSearch(): File '%s' missing or unreadable.\n" "$CurFile" 1>&2
			exit 126
		fi
	done
}
