#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/Translate
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Sat 28 Nov 18:52:15 GMT 2020
# Last Change       - Sat 28 Nov 18:52:20 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

Translate(){ #: Replace character $1 with $2 for string $3.
    IFS=$1
    OFS=$2

    set -- $3

    for Field in "$@"; do
        printf '%s%b' "$Field" "$OFS"
    done

    unset IFS Field
}
