#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/WCount
#----------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Sun 15 Dec 11:49:44 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell functionality.
#
# NOTE: POSIX compliance has largely been determined through the guidance of YASH.
#----------------------------------------------------------------------------------

WCount(){ #: Fetch the total number of words. (also accepts STDIN)
	if [ $# -eq 0 ]; then
		read Input < /dev/stdin
		set -- $Input
		printf "%d\n" $#

		unset Input
	else
		set -- $*
		printf "%d\n" $#
	fi
}
