#!/bin/sh
#cito M:644 O:0 G:0 T:/usr/lib/tflbp-sh/YNInput
#------------------------------------------------------------------------------
# Project Name      - Extra/libtflbp-sh/* (Terminal for Life Bourne POSIX)
# Started On        - Mon  2 Dec 15:32:30 GMT 2019
# Last Change       - Thu 16 Dec 00:02:22 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# POSIX-adhering function library for extra, portable Bourne Shell
# functionality. POSIX compliance has largely been determined through the
# guidance of YASH in posixly-complaint mode.
#------------------------------------------------------------------------------

YNInput(){ #: An easy-to-script prompt for the user, asking yes or no.
	if [ -z "$1" ]; then
		printf 'YNInput() $1: Prompt string required.\n' 1>&2
		exit 126
	fi

	printf '%s [Y/N] ' "$1"
	read Answer

	case $Answer in
		[Yy]|[Yy][Ee][Ss])
			return 0 ;;
		[Nn]|[Nn][Oo])
			return 1 ;;
		*)
			printf 'Err: Invalid response -- quitting.\n'
			exit 1 ;;
	esac

	unset Answer
}
