#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/autosh
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/autosh
# Started On        - Thu 31 Oct 22:49:41 GMT 2019
# Last Change       - Thu  9 Jan 19:14:33 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

CurVer='2020-01-09'
Progrm=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

Usage(){
	while read; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${Progrm^^} ($CurVer)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Development tool for shell programmers needing live updates.

		SYNTAX:     $Progrm [OPTS] [SCRIPT] [ARGUMENTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --shell|-S NAME         - Use NAME instead of Bourne Again Shell.
		            --refresh|-r INT        - Adjust to fit your performance needs.

		NOTE:       This program also works with other languages, like Perl.

	EOF
}

SHELL='bash'

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		--shell|-S)
			shift

			if [ -z "$1" ]; then
				Err 1 $LINENO 'Name of shell not provided.'
			elif [ "$1" == 'bash' ]; then
				Err 1 $LINENO 'The Bourne Again Shell is the default.'
			elif ! type -fP "$1" > /dev/null 2>&1; then
				Err 1 $LINENO 'Provided shell not found in PATH.'
			else
				SHELL=$1
			fi ;;
		--refresh|-r)
			shift

			if [ -z "$1" ]; then
				Err 1 $LINENO 'Unspecified refresh rate.'
			elif ! [[ $1 =~ ^[0-9]+$ ]]; then
				Err 1 $LINENO 'Invalid refresh rate.'
			else
				Refresh=$1
			fi ;;
		-*)
			Err 1 $LINENO 'Incorrect argument(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

[ -z "$1" ] && Err 1 $LINENO 'Missing argument -- file name required.'

ExecFile=$1; shift

declare -i DEPCOUNT=0
for DEP in tput sleep stat ${SHELL##*/}; {
	if ! type -fP "$DEP" > /dev/null 2>&1; then
		Err 0 $LINENO "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ "$BEQUIET" == 'true' ] && exec > /dev/null
[ "$DebugMe" == 'true' ] && set -x

# SSE = Seconds Since Epoch. (used to figure if and when modified)

TRAP(){
	tput ed; tput rmcup
	exit 0
}

trap 'TRAP' SIGINT

tput smcup

while :; do
	if [ -f "$ExecFile" ] && [ -r "$ExecFile" ]; then
		SSE=`stat -c '%Y' "$1" 2> /dev/null`

		if [ 0${SSE_OLD//[!0-9]} -lt 0${SSE//[!0-9]} ]; then
			tput clear

			"$SHELL" $@
		fi

		SSE_OLD=${SSE//[!0-9]}
	else
		tput ed; tput rmcup
		Err 1 $LINENO 'File not found or inaccessible.'
	fi

	sleep 0.${Speed}s # Half-second to help compensate for misalignment.
done

tput ed; tput rmcup
