#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/bdl
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/bdl (Batch Downloader)
# Started On        - Sat 16 Sep 22:34:12 BST 2017
# Last Change       - Fri 13 Dec 02:56:43 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2019-12-13'
Progrm=${0##*/}

MainDir="$HOME/.config/$Progrm"
EdFile="$MainDir/editor"
BDLFile="$MainDir/queue"

Usage(){
	while read -r CurLine; do
		printf "%b\n" "$CurLine"
	done <<-EOF
		\r            BDL ($CurVer)
		\r            Written by terminalforlife <terminalforlife@yahoo.com>

		\r            Simple Bourne POSIX solution to downloading multiple files.

		\rSYNTAX:     $Progrm [OPTS]

		\rOPTS:       --help|-h|-?            - Displays this help information.
		\r            --version|-v            - Output only the version datestamp.
		\r            --insert|-I URL         - Quickly append a URL to the download queue.
		\r            --dest|-d PATH          - Where PATH is the location to download.
		\r            --editor|-E CMD         - Where CMD is the command for your editor.
		\r            --suspend|-s            - Immediately suspend machine when finished.
		\r            --shutdown|-S           - Like above, but a shutdown after 1 minute.
		\r            --notify|-N             - Use notify-send to inform of $Progrm completion.
		\r            --edit|-e               - Change URL queue with an available text editor.
		\r            --clear|-C              - Empty the $Progrm download queue entirely.

		\rFILE:       ~/.config/bdl/editor
		\r            ~/.config/bdl/queue
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"
			exit 0 ;;
		--insert|-I)
			shift

			if [ -z "$DoInsert" ]; then
				Err 1 "Option '--insert|-I' requires an argument."
			else
				DoInsert=$1
			fi ;;
		--dest|-d)
			shift

			if ! [ -d "$1" ]; then
				Err 1 "Destination directory unavailable."
			else
				DL_DIR=$1
			fi ;;
		--editor|-E)
			shift

			if [ -z "$1" ]; then
				Err 1 "Option '--editor|-E' requires an argument."
			else
				ChangeEd=$1
			fi ;;
		--edit|-e)
			EditFlag='true' ;;
		--clear|-C)
			Clear='true' ;;
		--notify|-N)
			DoNotify='true' ;;
		--suspend|-s)
			DoSuspend='true' ;;
		--shutdown|-S)
			DoShutdown='true' ;;
		-*)
			Err 1 'Incorrect argument(s) specified.' ;;
	esac
	shift
done

if ! [ -f "$EdFile" ] && ! [ -s "$EdFile" ]; then
	Err 1 "Please choose an editor -- see: bdl -h"
else
	read QueueEd < "$EdFile"
fi

if [ "$EditFlag" = 'true' ]; then
	if command -v "$QueueEd" 1> /dev/null 2>&1; then
		$QueueEd "$BDLFile" 2> /dev/null
		exit 0
	else
		Err 1 "Unable to execute '$QueueEd' editor."
	fi
fi

ChkDep mv systemctl sleep sync mkdir

if [ "$Clear" = 'true' ]; then
	if ! [ -f "$BDLFile" ]; then
		Err 1 "File '$BDLFile' not found."
	else
		mv "$BDLFile" "$BDLFile.old"
		exit 0
	fi
elif [ -n "$DoInsert" ]; then
	printf "%s\n" "$DoInsert" 1>> "$BDLFile"
	exit 0
elif [ -n "$ChangeEd" ]; then
	printf '%s\n' "$ChangeEd" > "$EdFile"
	exit 0
fi

if [ -d "$MainDir" ] || ! mkdir -p "$MainDir" 1> /dev/null 2>&1; then
	Err 1 "Unable to create '$MainDir' directory."
fi

if [ -f "$BDLFile" ]; then
	while read URL Dest; do
		Output=${Dest:-./${URL##*/}}

		if ChkDep wget; then
			wget -qc --show-progress -O "$Output" "$URL"
		elif ChkDep curl; then
			curl -sC - --progress-bar -o "$Output" "$URL"
		else
			Err 1 "Neither 'wget' nor 'curl' are available."
		fi

		sync "$Output" # <-- Avoid data loss.
	done < "$BDLFile"

	[ "$DoNotify" = 'true' ] && notify-send "Downloading with $Progrm is complete."
	[ "$DoShutdown" = 'true' ] && systemctl poweroff
	[ "$DoSuspend" = 'true' ] && systemctl suspend
else
	printf 'Nothing to do -- quitting.\n'
fi
