#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/bios-info
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/bios-info
# Started On        - Tue 20 Feb 07:47:12 GMT 2018
# Last Change       - Fri  6 Dec 22:46:17 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This may be expanded in the future.
#----------------------------------------------------------------------------------

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

_VERSION_="2019-12-06"
_PROJECT_=${0##*/}

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Simple tool to show basic BIOS keys and their values.

		SYNTAX:     $_PROJECT_ [OPT]

		OPT:        --help|-h|-?            - Displays this help information.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--debug|-D)
			DEBUGME='true' ;;
		*)
			Err 1 $LINENO "Incorrect argument(s) specified." ;;
	esac

	shift
done

MAIN='/sys/devices/virtual/dmi/id'
printf "%-13s %16s\n" "KEY" "VALUE"
for FILE in $MAIN/{sys_vendor,board_{name,version},bios_{date,version}}; {
	if [ -f "$FILE" -a -r "$FILE" ]; then
		printf "%-13s %16s\n" "${FILE//*\/}" "$(< $FILE)"
	fi
}

