#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/bios-info
#------------------------------------------------------------------------------
# Project Name      - Extra/source/bios-info
# Started On        - Tue 20 Feb 07:47:12 GMT 2018
# Last Change       - Sat 14 Mar 14:10:33 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   bash (>= 4.3-14)
#   coreutils (>= 8.25-2)
#   libtflbp-sh (>= 2019-12-10)
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
set +e

CurVer='2020-03-14'
Progrm=${0##*/}

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

IDFile='/sys/devices/virtual/dmi/id'
printf "%-13s %16s\n" "KEY" "VALUE"
for File in $IDFile/{sys_vendor,board_{name,version},bios_{date,version}}; {
	if [ -f "$File" ] && [ -r "$File" ]; then
		printf "%-13s %16s\n" "${File##*/}" "$(< $File)"
	fi
}
