#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/dl-tuxradar-podcasts
# Started On        - Mon  9 Oct 19:08:27 BST 2017
# Last Change       - Wed 15 Dec 23:39:08 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2021-12-15"
_PROJECT_=${0##*/}

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

DOM="http://www.tuxradar.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Small shell program to download the TuxRadar podcasts.

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       All files (OGG) will be downloaded into the current directory.

		SITE:       $DOM
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET='true' ;;
		--debug)
			DEBUGME='true' ;;
		*)
			Err 1 'Incorrect argument(s) specified.' ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in xargs uniq sort wget grep; {
	if ! type -P "$DEP" > /dev/null 2>&1; then
		Err 0 "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

[ "$BEQUIET" == 'true' ] && exec > /dev/null
[ "$DEBUGME" == 'true' ] && set -xeu

EPISODE_LIST(){
	wget -q "$DOM/podcast" -O -\
		| grep -o "podcast-season-[0-9]\+-episode-[0-9]\+"\
		| uniq | sort -t "-" -k 3 -k 5 -n
}

for EPISODE in `EPISODE_LIST`; {
	wget -q $DOM/content/"$EPISODE" -O -\
		| grep -o "/files/podcast/tuxradar_s[0-9]\+e[0-9]\+\.ogg"\
		| uniq | xargs -I{} wget -qc --show-progress ${DOM}"{}"
}

