#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - Extra/source/dlclecs
# Started On        - Tue 19 Sep 13:00:16 BST 2017
# Last Change       - Sat  5 Jun 19:42:03 BST 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Downloader for various C programming teaching files.
#------------------------------------------------------------------------------

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

DepCount=0
for CurDep in id basename grep wget; do
	if ! command -V "$CurDep" 1> /dev/null 2>&1; then
		Err 0 "Dependency '$CurDep' not met."
		DepCount=$((DepCount + 1))
	fi
done

[ $DepCount -eq 0 ] || exit 1

[ `id -u` -eq 0 ] && Err 1 "Root access isn't required."

Domain="https://ocw.mit.edu"
Category="electrical-engineering-and-computer-science"
Course="6-087-practical-programming-in-c-january-iap-2010"
URL1="/courses/$Category/$Course/lecture-notes/"
GrepRegex="${URL1}MIT6_087IAP10_lec"

DownloadLinks=`wget -qO - "$Domain/$URL1" | grep -o "${GrepRegex}[0-9]\+.pdf"`

for File in $DownloadLinks; do
	FileName=`basename $File`
	if wget -q "${Domain}${File}"; then
		printf 'File: %s\n' "$FileName"
	else
		#TODO: Use proper error message.
		Err 1 "$FileName"
	fi
done
