#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/dlfcmags
# Started On        - Tue 28 Nov 00:02:33 GMT 2017
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# Download the entire collection of the Full Circle magazine for Ubuntu Linux.
#----------------------------------------------------------------------------------

_VERSION_="2021-12-15"
_PROJECT_=${0##*/}

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

DOMAIN="https://dl.fullcirclemagazine.org"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Download issues of the Full Circle magazine PDFs.

		SYNTAX:     $_PROJECT_ [OPTS] ISSUE1 ISSUE2 ISSUE3 . . .

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.

		EXAMPLE:    $_PROJECT_ 7
		            $_PROJECT_ -q {20..76}
		            $_PROJECT_ 1 8 9 22 {24..27}

		SITE:       ${DOMAIN/\/dl.//}

		NOTE:       There are currently versions 1-127 available.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET='true' ;;
		-*)
			Err 1 "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

if ! type -P wget > /dev/null 2>&1; then
	Err 1 "Dependency '/usr/bin/wget' not met."
fi

if ! [ "$*" ]; then
	printf -v ISSUE_LIST " %d" {1..127}
else
	ISSUE_LIST="$@"
fi

[ "$BEQUIET" == 'true' ] && exec > /dev/null

DL="/issue127_en.pdf"

for ISSUE in $ISSUE_LIST; {
	printf -v PRETTY_ISSUE "%0.3d" "$ISSUE"
	wget -qc --show-progress "$DOMAIN/issue${ISSUE}_en.pdf"\
		-O "$PRETTY_ISSUE - Full Circle.pdf"
}
