#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/dlspwalls
# Started On        - Sun 15 Oct 20:48:22 BST 2017
# Last Change       - Wed 27 Nov 15:54:03 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-11-27"
_PROJECT_=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

URL="https://wallpapercave.com/download/steampunk-wallpaper"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Download a collection of steampunk wallpapers.

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.

		NOTE:       Files will be download to the current directory, as JPGs.

		SITE:       ${URL%/download/*}
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--quiet|-q)
			BEQUIET='true' ;;
		--debug|-D)
			DEBUGME='true' ;;
		*)
			Err 1 $LINENO "Incorrect argument(s) specified." ;;
	esac
	shift
done

if ! type -fP wget > /dev/null 2>&1; then
	Err 1 $LINENO "Dependency 'wget' not met."
fi

read -a WGET_VER_LINE <<< "$(wget --version)"
WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
	NOWARC="--no-warc-compression"
fi

[ "$BEQUIET" == 'true' ] && exec > /dev/null
[ "$DEBUGME" == 'true' ] && set -x

HTML=`wget -q $NOWARC "${URL%/down*}/steampunk-wallpaper-1920x1080" -O -`

GETID=()
while read -a Y; do
	for FIELD in ${Y[@]/src=\"\/wp}; {
		[ "$FIELD" == "$OLD" ] && continue
		if [[ $FIELD == /* ]]; then
			if [[ $FIELD =~ [0-9A-Za-z]+.jpg ]]; then
				GETID+=("${FIELD%.jpg\"}")
			fi
		else
			continue
		fi

		OLD=$FIELD
	}
done <<< "$HTML"

declare -i N=0
for ID in ${GETID[@]//\/}; {
	N+=1

	printf "%s\n" "DOWNLOADING: steampunk-wallpaper-1920x1080-${ID}.jpg"
	printf -v FNAME "./steampunk-wallpaper-1920x1080-%0.2d.jpg" "${N}"
	wget -qc $NOWARC "${URL}-1920x1080-${ID}" -O "$FNAME"
}

