#!/bin/bash

#------------------------------------------------------------------------------
# Project Name      - Extra/source/dlspwalls
# Started On        - Sun 15 Oct 20:48:22 BST 2017
# Last Change       - Fri 24 Dec 13:28:08 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Download a collection of steampunk wallpapers.
#
# 2021-12-24: As of 2021-12-24, it appears this script is broken, likely due to
#             the original site's data changing.
#------------------------------------------------------------------------------

CurVer="2021-12-15"
Progrm=${0##*/}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

Usage() {
	while read -r; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.

		Files will be download to the current directory, as JPGs.
	EOF
}

URL='https://wallpapercave.com/download/steampunk-wallpaper'

while [ -n "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect argument(s) specified.' ;;
	esac
	shift
done

if ! type -P wget > /dev/null 2>&1; then
	Err 1 "Dependency 'wget' not met."
fi

HTML=`wget -qO - "${URL%/down*}/steampunk-wallpaper-1920x1080"`

while read -a Line; do
	for Field in ${Line[@]/src=\"\/wp}; {
		[ "$Field" == "$Old" ] && continue

		if [[ $Field == /* ]] && [[ $Field =~ [0-9A-Za-z]+.jpg ]]; then
			GetID+=("${Field%.jpg\"}")
		else
			continue
		fi

		Old=$Field
	}
done <<< "$HTML"

for ID in ${GetID[@]//\/}; {
	(( Nr++ ))

	printf '%s\n' "DOWNLOADING: steampunk-wallpaper-1920x1080-$ID.jpg"
	printf -v Filename "./steampunk-wallpaper-1920x1080-%0.2d.jpg" $Nr
	wget -qcO "$Filename "${URL}-1920x1080-${ID}""
}

