#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/fbdriver
# Started On        - Thu 10 Dec 14:59:18 GMT 2020
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Written in response to this thread:
#
#   https://forums.linuxmint.com/viewtopic.php?f=213&t=337105
#------------------------------------------------------------------------------

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

UEventFile='/sys/class/graphics/fb0/device/uevent'
if [[ -f $UEventFile && -r $UEventFile ]]; then
	while IFS='=' read -a Line; do
		if [[ ${Line[0]} == DRIVER ]]; then
			Driver=${Line[1]}
			break
		fi
	done < "$UEventFile"
elif type -P lshw &> /dev/null; then
	while IFS=':' read -a Line; do
		if [[ ${Line[0]// /} == configuration ]]; then
			for Field in ${Line[1]}; {
				IFS='=' read -a KeyVal <<< "$Field"
				if [[ ${KeyVal[0]} == driver ]]; then
					Driver=${KeyVal[1]}
					break
				fi
			}

			break
		fi
	done <<< "$(lshw -c video 2> /dev/null)"
fi

if [[ -n $Driver ]]; then
	printf "Found: '%s'\n" "$Driver"
else
	Err 1 'Unable to identify framebuffer.'
fi
