#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - Extra/source/fbdriver
# Started On        - Thu 10 Dec 14:59:18 GMT 2020
# Last Change       - Thu 10 Dec 19:44:25 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Written in response to this thread:
#
#   https://forums.linuxmint.com/viewtopic.php?f=213&t=337105
#------------------------------------------------------------------------------

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

UEventFile='/sys/class/graphics/fb0/device/uevent'
if [ -f "$UEventFile" -a -r "$UEventFile" ]; then
	while IFS='=' read -a Line; do
		if [ "${Line[0]}" == 'DRIVER' ]; then
			Driver=${Line[1]}
			break
		fi
	done < "$UEventFile"
elif type -P lshw &> /dev/null; then
	while IFS=':' read -a Line; do
		if [ "${Line[0]// /}" == 'configuration' ]; then
			for Field in ${Line[1]}; {
				IFS='=' read -a KeyVal <<< "$Field"
				if [ "${KeyVal[0]}" == 'driver' ]; then
					Driver=${KeyVal[1]}
					break
				fi
			}

			break
		fi
	done <<< "$(lshw -c video 2> /dev/null)"
fi

case $Driver in
	nvidia|amd|nouveau)
		# I have no idea what all the possible values are, so add as needed.
		printf '%s\n' "$Driver" ;;
	'')
		Err 1 'Unable to determine display driver.' ;;
	*)
		# You could replace 'Unrecognised' with 'Unsupported' if that's your
		# goal from this functionality.
		Err 1 "Unrecognised '$Driver' display driver." ;;
esac
