#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/feh-slides
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/feh-slides
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Fri  6 Dec 22:49:20 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-12-06"
_PROJECT_=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            A super-simple desktop wallpaper slideshow.

		SYNTAX:     $_PROJECT_ [OPTS] [PATH]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
		            --interval|-i N         - Change wallpaper every N seconds.
		            --trap|-T               - Trap SIGUSR1 for a cleaner exit. This is more
		                                      of a placeholder for future expansion.

		NOTE:       Where PATH is the directory in which your chosen wallpapers are stored.

		            If no interval is specified, the default of 5 seconds is chosen.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--debug|-D)
			DEBUGME='true' ;;
		--interval|-i)
			shift; INTERVAL="$1" ;;
		--trap|-T)
			TRAP='true' ;;
		-*)
			Err 1 $LINENO "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in sleep feh; {
	if ! type -fP "$DEP" > /dev/null 2>&1; then
		Err 0 $LINENO "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

if [ $# -gt 1 ]; then
	Err 1 $LINENO "Only one wallpaper directory may be specified."
elif [ $# -eq 0 ]; then
	Err 1 $LINENO "A wallpaper directory must be specified."
fi

[ "$DEBUGME" == 'true' ] && set -x

# Room for easy expansion.
EXIT(){
	kill $$
	exit 0
}

if [ -d "$1" ]; then
	[ "$TRAP" == 'true' ] && trap 'EXIT' 10 # <-- SIGUSR1

	while :; do
		for FILE in "${1%\/}"/*; {
			if [ -f "$FILE" ]; then
				if ! feh --no-fehbg --bg-center "$FILE"; then
					Err 1 $LINENO "One or more errors detected while setting wallpaper with feh."
				elif ! sleep ${INTERVAL:-5}s > /dev/null 2>&1; then
					Err 1 $LINENO "Invalid interval time specified."
				fi
			fi
		}
	done
else
	Err 1 $LINENO "Directory '$1' not found."
fi

