#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/feh-slides
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/feh-slides
# Started On        - Sun  5 Nov 12:04:09 GMT 2017
# Last Change       - Fri 13 Dec 01:38:42 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2019-12-13'
Progrm=${0##*/}

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		            FEH-SLIDES ($CurVer)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            Super-simple Bourne POSIX desktop wallpaper slideshow.

		SYNTAX:     $Progrm [OPTS] [PATH]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --interval|-i N         - Change wallpaper every N seconds.

		NOTE:       Where PATH is the directory in which your chosen wallpapers are stored.

		            If no interval is specified, the default of 5 seconds is chosen.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--interval|-i)
			shift; Interval=$1 ;;
		-*)
			Err 1 'Incorrect argument(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

ChkDep sleep feh

if [ $# -gt 1 ]; then
	Err 1 "Only one wallpaper directory may be specified."
elif [ $# -eq 0 ]; then
	Err 1 "A wallpaper directory must be specified."
fi

if [ -d "$1" ]; then
	while :; do
		for CurFile in "${1%/}"/*; do
			if [ -f "$CurFile" ]; then
				if ! feh --no-fehbg --bg-center "$CurFile"; then
					Err 1 'One or more errors detected while setting a wallpaper.'
				elif ! sleep ${Interval:-5}s 1> /dev/null 2>&1; then
					Err 1 'Invalid interval time specified.'
				fi
			fi
		done
	done
else
	Err 1 "Directory '$1' not found."
fi

