#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/fix-ff-gtk
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/fix-ff-gtk
# Started On        - Fri 29 Mar 13:12:04 GMT 2019
# Last Change       - Fri 10 Jan 19:28:28 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
. /usr/lib/tflbp-sh/SplitStr
set +e

CurVer='2020-01-10'
Progrm=${0##*/}

FF="/usr/bin/firefox"

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\r            FIX-FF-GTK ($CurVer)
		\r            Written by terminalforlife <terminalforlife@yahoo.com>

		\r            Psuedo-Fix colors used in Firefox when using a dark GTK theme.

		\rSYNTAX:     $Progrm [OPTS]

		\rOPTS:       --help|-h|-?            - Displays this help information.
		\r            --version|-v            - Output only the version datestamp.
		\r            --theme|-t NAME         - Where NAME is the chosen GTK theme.

		\rNOTES:      The GTK theme Adwaita, which distributions often have pre-installed, is
		\r            needed, unless another is specified.

		\r            This script will work globally, meaning ALL users, regardless of their
		\r            chosen theme, will use the Adwaita GTK theme for their use of Firefox.

		\r            This script basically edits $FF which is what is used when
		\r            you execute the firefox command. If you use a different executable, -
		\r            then this will not work for you.

		\r            Although this fix has worked for me for over a year, newer or older
		\r            versions of Firefox may execute or be scripted (aforementioned file) in
		\r            a different way, thus nullifying this script.

		\r            This script will likely not work on all distributions of Linux. It was
		\r            written in Ubuntu 16.04.6, and should work on all forms and likely
		\r            versions of Debian- and Ubuntu-based distributions of Linux.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--theme|-t)
			Theme="$2" ;;
		*)
			Err 1 "Incorrect argument(s) specified." ;;
	esac
	shift
done

for I in `SplitStr ' ' "$(firefox -v)"`; do
	case $I in
		Mozilla|Firefox)
			continue ;;
		[0-9]*)
			if [ ${I//[!0-9]} -ge 7201 ]; then
				Err 1 "Your version of Firefox doesn't need this fix."
			fi

			break ;;
	esac
done

[ -z "$Theme" ] && Theme='Adwaita'

ChkDep sed id

[ `id -u` -eq 0 ] || Err 1 'Root access is required.'

if ! [ -f "$FF" ] && { [ -r "$FF" ] && [ -w "$FF" ]; }; then
	Err 1 "File "$FF" not found or inaccessible."
fi

declare -i LINE=0
String='exec\ \$MOZ_LIBDIR\/\$MOZ_APP_NAME\ \"\$\@\"'

printf '%s\n' "$FF" | while read; do
	LINE+=1

	if [[ $REPLY =~ ^\ +$String ]] && [ $LINE -eq 110 ]; then
		if echo sed -in 110s/'^\(\s\+\)'"$String"/'\1GTK_Theme=$Theme'" '"$String"/ "$FF"; then
			printf "File '%s' modified.\n" "$FF"
			exit 0
		else
			Err 1 "File '$FF' failed during editing."
		fi
	elif [[ $REPLY =~ ^\ +GTK_Theme\=\"$Theme\"\ $String ]]; then
		printf "File '%s' already modified.\n" "$FF"
		exit 1
	fi
done

Err 1 "File '$FF' contents unexpected."
