#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/forex
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/forex
# Started On        - Sun 15 Oct 16:25:38 BST 2017
# Last Change       - Thu  5 Dec 23:13:08 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

CurVer='2019-12-05'
Progrm=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

Domain='https://www.foreignexchange.org.uk'

Usage(){
	while read; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${Progrm^^} ($CurVer)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Easily convert various currency rates straight from the terminal.

		SYNTAX:     $Progrm [OPTS] SOURCE AMOUNT TARGET

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --debug|-D              - Enables the built-in bash debugging.
		            --rounded|-R            - Do not display as a floating point.

		EXAMPLE:    $ $Progrm USD 5 GBP
		            0.7254

		SITE:       $Domain
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		--debug|-D)
			DebugMe='true' ;;
		--rounded|-R)
			ROUNDED='true' ;;
		-*)
			Err 1 $LINENO "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

if ! type -P wget > /dev/null 2>&1; then
	Err 1 $LINENO "Dependency 'wget' not met."
fi

SOURCE=$1
AMOUNT=$2
TARGET=$3

read -a WGET_VER_LINE <<< "$(wget --version)"
WGET_VERSION=0${WGET_VER_LINE[2]//[!0-9]}
if [ $WGET_VERSION -ge 01192 -a $WGET_VERSION -lt 01194 ]; then
	NOWARC="--no-warc-compression"
fi

[ "$DebugMe" == 'true' ] && set -x

# Curent and historical currency abbreviations. Taken from: http://www.xe.com
declare -a VALID=(
	USD EUR GBP INR AUD CAD SGD CHF MYR JPY CNY NZD THB HUF AED HKD MXN ZAR PHP
	SEK IDR SAR BRL TRY KES KRW EGP IQD NOK KWD RUB DKK PKR ILS PLN QAR XAU OMR
	COP CLP TWD ARS CZK VND MAD JOD BHD XOF LKR UAH NGN TND UGX RON BDT PEN GEL
	XAF FJD VEF BYN HRK UZS BGN DZD IRR DOP ISK XAG CRC SYP LYD JMD MUR GHS AOA
	UYU AFN LBP XPF TTD TZS ALL XCD GTQ NPR BOB ZWD BBD CUC LAK BND BWP HNL PYG
	ETB NAD PGK SDG MOP NIO BMD KZT PAB BAM GYD YER MGA KYD MZN RSD SCR AMD SBD
	AZN SLL TOP BZD MWK GMD BIF SOS HTG GNF MVR MNT CDF STD TJS KPW MMK LSL LRD
	KGS GIP XPT MDL CUP KHR MKD VUV MRO ANG SZL CVE SRD XPD SVC BSD XDR RWF AWG
	DJF BTN KMF WST SPL ERN FKP SHP JEP TMT TVD IMP GGP ZMW
)

for TYPE in ${VALID[@]}; {
	[ "$TYPE" == "$SOURCE" ] && SOURCE_YES='true'
	[ "$TYPE" == "$TARGET" ] && TARGET_YES='true'
}

if ! [ "$SOURCE_YES" == 'true' ]; then
	Err 1 $LINENO "Currency SOURCE '${SOURCE:-?}' not recognised."
elif ! [ "$TARGET_YES" == 'true' ]; then
	Err 1 $LINENO "Currency TARGET '${TARGET:-?}' not recognised."
fi

SITE="$Domain/fx-rates/conversion/$AMOUNT/$SOURCE/$TARGET"
while read -a X; do
	if [[ ${X[*]} =~ name=\"answer\" ]]; then
		RESULT=${X[3]//[!0-9.]}
	fi
done <<< "$(wget -q -t 1 $NOWARC "$SITE" -O -)"

if [[ $RESULT =~ ^[0-9.]+$ ]]; then
	if [ "$ROUNDED" == 'true' ]; then
		printf "%s\n" "${RESULT%.*}"
	else
		printf "%.4f\n" "$RESULT"
	fi
else
	Err 1 $LINENO "Unable to determine the correct result."
fi

