#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/local/bin/fsit
#------------------------------------------------------------------------------
# Project Name      - Extra/source/fsit
# Started On        - Thu 28 Sep 23:58:07 BST 2017
# Last Change       - Sun 18 Jun 21:27:50 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Do nothing until the given file is touched.
#
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   bash (>= 3.2.48)
#------------------------------------------------------------------------------

CurVer='2023-06-18'
Progrm='fsit'

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS] FILE

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -i, --interval N         - Use a check interval of N seconds.

		  By default, the checking interval is 0.3 seconds.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

while [[ -n $1 ]]; do
	case $1 in
		--help|-h)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--interval|-i)
			shift

			if [[ $1 =~ ^([0-9]+|[0-9]+.[0-9]+)$ ]]; then
				Interval=$1
			else
				Err 1 "Invalid interval specified."
			fi ;;
		-*)
			Err 1 "Incorrect argument(s) specified." ;;
		*)
			break ;;
	esac
	shift
done

(( $# == 0 )) && Err 1 'File required.'

Interactive=
[[ -t 1 ]] && Interactive='sleep'

DepCount=0
for Dep in stat $Interactive; do
	if ! type -P "$Dep" &> /dev/null; then
		Err 0 "Dependency '$Dep' not met."
		(( DepCount++ ))
	fi
done

(( DepCount > 0 )) && exit 1

Original=`stat -c '%Y' "$1" 2> /dev/null`

while :; do
	[[ -f $1 ]] || continue

	(( Current > Original )) && break

	if [[ -z $Interactive ]]; then
		read -n 1 -st ${Interval:-0.3}
	else
		sleep ${Interval:-0.3}s
	fi

	Current=`stat -c '%Y' "$1" 2> /dev/null`
done
