#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/getcfc
#------------------------------------------------------------------------------
# Project Name      - Extra/source/getcfc
# Started On        - Thu 23 Nov 14:44:50 GMT 2017
# Last Change       - Sun 24 Jan 14:23:13 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Download many classic ISO images contained a bundle of PC games.
#------------------------------------------------------------------------------

CurVer='2021-01-24'
Progrm=${0##*/}

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.

		  Where DISC_NUMBER is a zero-padded number between 01 and 60. Sadly, -
		  discs 17 and 47 are missing.
	EOF
}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

Domain='https://archive.org'

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		-*)
			Err 1 'Incorrect argument(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

[ -x /usr/bin/wget ] || Err 1 "Dependency '/usr/bin/wget' not met."

[ "$*" ] || Err 1 'Specifiy at least one CD to download.'

URL='download/cdrom-classic-fond'

for CD in "$@"; {
	if ! [[ $CD == [0-9][0-9] ]]; then
		Err 0 "Specified ISO '$CD' is invalid."
		continue
	fi

	wget -qc --show-progress "$Domain/${URL}-${CD}/ClassicFond${CD}.iso"
}
