#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/lspkg-set
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/lspkg-set (List Packages Set)
# Started On        - Wed 24 Jan 17:31:41 GMT 2018
# Last Change       - Fri 10 Jan 00:53:01 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-01-10'
Progrm=${0##*/}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\r            LSPKG-SET ($CurVer)
		\r            Written by terminalforlife <terminalforlife@yahoo.com>

		\r            Add-on for lspkg to output sets of installed packages.

		\rSYNTAX:     $Progrm [OPT]

		\rOPTS:       --help|-h|-?            - Displays this help information.
		\r            --version|-v            - Output only the version datestamp.
		\r            --essential|-E          - Display the essential packages.
		\r            --extra|-e              - Display the extra packages.
		\r            --important|-I          - Display the important packages.
		\r            --optional|-o           - Display the optional packages.
		\r            --required|-R           - Display the required packages.

		\rNOTE:       Like lspkg, this POSIX-ly correct Bourne shell program is
		\r            only compatible with Debian or Ubuntu based systems, as it
		\r            parses dpkg-query's output.
	EOF
}

[ $# -eq 0 ] && Err 1 "One argument is required -- see: $Progrm -h"

case $* in
	--help|-h|-\?)
		Usage; exit 0 ;;
	--version|-v)
		printf '%s\n' "$CurVer"; exit 0 ;;
	--essential|-E)
		Type='Essential:yes' ;;
	--extra|-e)
		Type='Priority:extra' ;;
	--required|-R)
		Type='Priority:required' ;;
	--optional|-o)
		Type='Priority:optional' ;;
	--important|-I)
		Type='Priority:important' ;;
	*)
		Err 1 'Incorrect argument(s) specified.' ;;
esac

ChkDep dpkg-query

Format="\${db:Status-Abbrev} \${${Type%:*}} \${Package}\n"

dpkg-query -Wf "$Format" \* | while read F1 F2 F3 _; do
	if [ "$F1" = 'ii' -a "$F2" = "${Type#*:}" ]; then
		New=$F3

		[ "$New" = "$Old" ] && continue
		printf '%s\n' "$New"

		Old=$New
	fi
done
