#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/mif
#------------------------------------------------------------------------------
# Project Name      - Extra/source/mif (Movie Index Filter)
# Started On        - Fri 13 Oct 13:21:13 BST 2017
# Last Change       - Sat 17 Oct 03:30:09 BST 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-10-17'
Progrm=${0##*/}

Domain='https://github.com'

Usage(){
	while read; do
		printf '%s\n' "$REPLY"
	done <<-EOF
		            ${Progrm^^} ($CurVer)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Shell program to filter films by year and whether seen.

		SYNTAX:     $Progrm [OPTS] [YEAR]

		OPTS:       --help|-h|-?            - Display this help information.
		            --version|-v            - Output the version datestamp.
		            --debug|-D              - Enable built-in Bash debugging.
		            --file|-f FILE          - Override saved path with FILE.
		            --seen|-s               - Filter by movies marked as seen.
		            --unseen|-u             - Default. Works opposite to above.
		            --all|-a                - Display films; disregard filters.
		            --total|-t              - Output total number of matches.
		            --mark M                - Where M is - or + for whether
		                                      seen or not.
		            --organize|-O           - Organise files in CWD by year.
		                                      Has potential to be destructive!
		            --mklist|-M[:N]         - Output a $Progrm-usable movie list
		                                      from CWD. If :N is appended, then
		                                      omit [+] and [-].

		NOTE:       The file which $Progrm parses must be in a strict layout in
		            order for $Progrm to work correctly. An example of such a
		            file's contents:

		              # Comment lines will be ignored.
		              1972[+]: The Godfather
		              1974[+]: The Godfather - Part II
		              1974[+]: Dog Day Afternoon
		              1992[+]: Alien 3
		              1993[+]: Carlito's Way
		              1993[-]: The Fugitive
		              1994[+]: Clear and Present Danger
		              1994[+]: Jack Dee: Live at the London Palladium

		            Where + is unseen (new) and - is seen.

		FILE:       Default is ~/.$Progrm but use --file|-f FILE to override.

		SITE:       $Domain/terminalforlife/Extra
	EOF
}

if [ "${BASH_VERSINFO[0]}" -ge 4 ]; then
	shopt -s extglob globstar
else
	Err 1 "Bash version 4.0 or greater is required."
fi

INDEX="$HOME/.$Progrm"
SEEN='false'
TTL='false'

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		--debug|-D)
			DebugMe='true' ;;
		--mklist|-M)
			shift; MAKE_LIST_OPT=":[+]" ;;
		--mklist:N|-M:N)
			shift; MAKE_LIST_OPT=":" ;;
		--file|-f)
			shift; INDEX="$1" ;;
		--all|-a)
			SEEN="all" ;;
		--mark)
			shift; MARK="$1" ;;
		--organize|-O)
			ORGANIZE='true' ;;
		--total|-t)
			TTL='true' ;;
		--seen|-s)
			SEEN='true' ;;
		--unseen|-u)
			SEEN='false' ;;
		*)
			break ;;
	esac
	shift
done

ChkDep mkdir mv

if [[ $MAKE_LIST_OPT =~ (:|:\[+\]) ]]; then
	for FILE in **; {
		[ -f "$FILE" ] || continue
		IFS="/" read -a X <<< "${FILE% (*}"
		printf "%s%s: %s\n" "${X[0]}" "${MAKE_LIST_OPT#:}" "${X[1]}"
	}

	exit 0
fi

if ! [ "$ORGANIZE" == 'true' ]; then
	if [[ $1 =~ ^[0-9]+$ ]]; then
		YEAR="$1"; shift
	else
		if ! [ "$SEEN" == "all" ]; then
			Err 1 "Invalid year specified."
		fi
	fi
fi

[ "$*" ] && Err 1 "Incorrect argument(s) specified."

[ "$DebugMe" == 'true' ] && set -x

if [ "$ORGANIZE" == 'true' ]; then
	for X in *; {
		Y=${X//*\(}

	 [[ ${Y%\)*} =~ ^[0-9]+$ ]] || continue

		if mkdir "${Y%\)*}"; then
			printf "%s\n" "MAKE: ${Y%\)*}"
		else
			printf "%s\n" "Err: ${Y%\)*}"
		fi

		if mv "$X" ${Y%\)*}/; then
			printf "%s\n" "MOVE: ${Y%\)*}/${X//*\/}"
		else
			printf "%s\n" "Err: ${Y%\)*}/${X//*\/}"
		fi
	}

	exit 0
fi

[ -f "$INDEX" ] || Err 1 "Index file '$INDEX' not found."

declare -i LINE=0
while read -r; do
	{ [[ $REPLY == +(#)* ]] || [ -z "$REPLY" ]; } && continue
	if [ "$SEEN" == 'false'  ]; then
		if [[ $REPLY == $YEAR\[\+\]:\ * ]]; then
			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"
			LINE+=1
		fi
	elif [ "$SEEN" == 'true'  ]; then
		if [[ $REPLY == $YEAR\[\-\]:\ * ]]; then
			printf "%s\n" "${REPLY/+([0-9])\[?\]: }"
			LINE+=1
		fi
	elif [ "$SEEN" == "all"  ]; then
		printf "%s\n" "${REPLY/+([0-9])\[?\]: }"
		LINE+=1
	fi
done < "$INDEX"

[ $LINE -eq 0 ] && Err 1 "Unable to find year $YEAR."
[ "$TTL" == 'true' ] && printf "\nTotal: %d\n" "$LINE"
