#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/mplay
#------------------------------------------------------------------------------
# Project Name      - Extra/source/mplay
# Started On        - Sat 16 Sep 19:42:57 BST 2017
# Last Change       - Thu 16 Dec 00:03:56 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Abandoned in favor of the recent Python3.6 rewrite, which turned out to be a
# surprising replacement. Reported bugs may be addressed, but new features or
# effort to update or optimize the code will probably not be made.
#
# The Python3.6 rewrite of `mplay` can be found in the PythonProjects
# repository on the same GitHub store from which this file originated.
#------------------------------------------------------------------------------

_VERSION_="2021-12-16"
_PROJECT_=${0##*/}

DOM="https://github.com"

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

THEMEDIR="/usr/share/moc/themes"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            MOC Wrapper for a clean layout with a subtle transparent theme.

		SYNTAX:     $_PROJECT_ [OPTS] PATH

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --run-once|-o           - Exit the MOC server when closed.

		NOTE:       Where PATH is the location in which music is found.

		            The following directory is expected by default:

		              $THEMEDIR

		            The default theme used is the tfl_moc_theme, found at the above GitHub
		            address, in the Extra repository.

		            The latest version of $_PROJECT_ includes this theme, however.

		SITE:       $DOM/terminalforlife/Extra
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--once|-o)
			ONCE='true' ;;
		-*)
			Err 1 "Incorrect argument(s) specified." ;;
	esac
	shift
done

[ "$1" -a ! -d "$1" ] && Err 1 "Unable to find the given music directory."

[ -d $THEMEDIR ] || Err 1 "Theme directory not found."
[ -f "$THEMEDIR/tfl_moc_theme" ] || Err 1 "Theme file not found."

if ! type -P mocp > /dev/null 2>&1; then
	Err 1 "Dependency 'mocp' not met."
fi

/usr/bin/mocp -n -T "$THEMEDIR/tfl_moc_theme"     \
	-O ShowFormat=yes                         \
	-O ShowTime=no                            \
	-O Shuffle=no                             \
	-O HideFileExtension=yes                  \
	-O SavePlaylist=no                        \
	-O TagsCacheSize=3000                     \
	-O PlaylistNumbering=yes                  \
	-O Layout1="playlist(50%,50%,50%,50%)"    \
	-O FollowPlayedFile=yes                   \
	-O ModPlug_NoiseReduction=yes             \
	-O ModPlug_ResamplingMode=FIR             \
	-O CanStartInPlaylist=yes                 \
	-O ResampleMethod=SincMediumQuality       \
	-O UseMimeMagic=no                        \
	-O ShowHiddenFiles=no                     \
	-O InputBuffer=512                        \
	-O OutputBuffer=512                       \
	-O Prebuffering=256                       \
	-m "${1:-$HOME/Music}"                    \
|| Err 1 "Unable to start the MOC player."

if [ "$ONCE" == 'true' ]; then
	wait; mocp -x
fi
