#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/mplay
# Started On        - Sat 16 Sep 19:42:57 BST 2017
# Last Change       - Wed 27 Nov 15:56:22 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-11-27"
_PROJECT_=${0##*/}

DOM="https://github.com"

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

THEMEDIR="/usr/share/moc/themes"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife (terminalforlife@yahoo.com)

		            MOC Wrapper for a clean layout with a subtle transparent theme.

		SYNTAX:     $_PROJECT_ [OPTS] PATH

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --update|-U             - Check for updates to mplay.
		            --run-once|-o           - Exit the MOC server when closed.

		NOTE:       Where PATH is the location in which music is found.

		            The following directory is expected by default:

		              $THEMEDIR

		            The default theme used is the tfl_moc_theme, found at the above GitHub
		            address, in the Extra repository.

		            The latest version of $_PROJECT_ includes this theme, however.

		SITE:       $DOM/terminalforlife/Extra
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--update|-U)
			UPDATE='true' ;;
		--once|-o)
			ONCE='true' ;;
		-*)
			Err 1 $LINENO "Incorrect argument(s) specified." ;;
	esac
	shift
done

if [ "$UPDATE" == 'true' ]; then
	if ! type -fP wget > /dev/null 2>&1; then
		Err 1 $LINENO "Dependency 'wget' not met."
	fi

	VERSION_URL="$DOM/terminalforlife/Extra/raw/master/versions"
	while IFS='=' read -a LINE; do
		if  [ "${LINE[0]}" == 'mplay' ]; then
			LATEST=${LINE[1]}

			if [[ ${LATEST//-} =~ ^[0-9]{8}$ ]]; then
				if [ ${LATEST//-} -gt ${_VERSION_//-} ]; then
					while read -r; do
						printf "%s\n" "$REPLY"
					done <<-EOF
						New version available:    $LATEST
						Current version:          $_VERSION_
					EOF
				fi
			else
				Err 1 $LINENO "Failed to check for available updates."
			fi
		fi
	done <<< "$(wget -q "$VERSION_URL" -O -)"

	exit 0
fi

[ "$1" -a ! -d "$1" ] && Err 1 $LINENO "Unable to find the given music directory."

[ -d $THEMEDIR ] || Err 1 $LINENO "Theme directory not found."
[ -f "$THEMEDIR/tfl_moc_theme" ] || Err 1 $LINENO "Theme file not found."

if ! type -fP mocp > /dev/null 2>&1; then
	Err 1 $LINENO "Dependency 'mocp' not met."
fi

/usr/bin/mocp -n -T "$THEMEDIR/tfl_moc_theme"     \
	-O ShowFormat=yes                         \
	-O ShowTime=no                            \
	-O Shuffle=no                             \
	-O HideFileExtension=yes                  \
	-O SavePlaylist=no                        \
	-O TagsCacheSize=3000                     \
	-O PlaylistNumbering=yes                  \
	-O Layout1="playlist(50%,50%,50%,50%)"    \
	-O FollowPlayedFile=yes                   \
	-O ModPlug_NoiseReduction=yes             \
	-O ModPlug_ResamplingMode=FIR             \
	-O CanStartInPlaylist=yes                 \
	-O ResampleMethod=SincMediumQuality       \
	-O UseMimeMagic=no                        \
	-O ShowHiddenFiles=no                     \
	-O InputBuffer=512                        \
	-O OutputBuffer=512                       \
	-O Prebuffering=256                       \
	-m "${1:-$HOME/Music}"                    \
|| Err 1 $LINENO "Unable to start the MOC player."

if [ "$ONCE" == 'true' ]; then
	wait; mocp -x
fi

