#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/local/bin/mplay
#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/mplay
# Started On        - Sat 16 Sep 19:42:57 BST 2017
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------

CurVer='2022-02-17'
Progrm='mplay'
ProgrmFancy='MPlay'

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS] [PATH]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -o, --run-once           - Exit the MoC server when closed.

		  To exit $ProgrmFancy, send the SIGINT (130) signal using the Ctrl + C
		  shortcut (^C). Your previous terminal layout will be restored.

		  When forcing, unsupported mimetypes and executables will be allowed.

		  The use of '--' to ignore proceeding flags is supported.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

Domain='https://github.com'
ThemeDir='/usr/share/moc/themes'

while [[ -n $1 ]]; do
	case $1 in
		--)
			shift
			break ;;
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf "%s\n" "$CurVer"; exit 0 ;;
		--once|-o)
			Once='True' ;;
		-*)
			Err 1 'Incorrect argument(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

if [[ -z $1 ]]; then
	Err 1 'Path to music files not provided.'
elif ! [[ -d $1 ]]; then
	Err 1 'Unable to find the given music directory.'
fi

[[ -d $ThemeDir ]] || Err 1 'Theme directory not found.'
[[ -f $ThemeDir/tfl_moc_theme ]] || Err 1 'Theme file not found.'
type -P mocp &> /dev/null || Err 1 "Dependency 'mocp' not met."

mocp -n -T "$ThemeDir/tfl_moc_theme"          \
	-O ShowFormat=yes                         \
	-O ShowTime=no                            \
	-O Shuffle=no                             \
	-O HideFileExtension=yes                  \
	-O SavePlaylist=no                        \
	-O TagsCacheSize=3000                     \
	-O PlaylistNumbering=yes                  \
	-O Layout1="playlist(50%,50%,50%,50%)"    \
	-O FollowPlayedFile=yes                   \
	-O ModPlug_NoiseReduction=yes             \
	-O ModPlug_ResamplingMode=FIR             \
	-O CanStartInPlaylist=yes                 \
	-O ResampleMethod=SincMediumQuality       \
	-O UseMimeMagic=no                        \
	-O ShowHiddenFiles=no                     \
	-O InputBuffer=512                        \
	-O OutputBuffer=512                       \
	-O Prebuffering=256                       \
	-m "${1:-$HOME/Music}"                    \
|| Err 1 'Unable to start the MoC player.'

if [[ $Once == True ]]; then
	wait
	mocp -x
fi
