#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/noprtscr (No Print Screen)
# Started On        - Sun 21 Jan 18:30:36 GMT 2018
# Last Change       - Thu 16 Dec 00:04:22 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A small script to remedy this issue in Linux Mint 18.3 with Cinnamon:
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=152887
#
# Also enable the exra feature (launch the Menu with PrtSc) with:
#
# OPTS:       --version|-v            - Output only the version datestamp.
#             --prtsc-is-menu         - Use PrtSC to launch the Mint Menu.
#----------------------------------------------------------------------------------

_VERSION_="2021-12-16"
_PROJECT_=${0##*/}

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

if ! type -P gsettings > /dev/null 2>&1; then
	Err 1 "Dependency 'gsettings' not met."
fi

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			printf "USAGE: %s [[--help|-h|-?] | [--version|-v]] | [--prtsc-is-menu]\n" "$_PROJECT_" ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"; exit 0 ;;
		--prtsc-is-menu)
			# Feature the OP in the thread requested.
			SCHEMA="com.linuxmint.mintmenu"
			if ! gsettings set "$SCHEMA" hot-key "Print" 2> /dev/null; then
				Err 1 "Unable to set 'hot-key' to 'Print' in: $SCHEMA"
			fi ;;
		*)
			Err 1 "Incorrect argument(s) specified." ;;
	esac
	shift
done

SCHEMA="org.cinnamon.desktop.keybindings.media-keys"
for KEY in {area,window}-screenshot{,-clip} screenshot{,-clip}; {
	if ! gsettings set "$SCHEMA" "$KEY" "[]" 2> /dev/null; then
		Err 1 "Unable to clear: $KEY"
	fi
}

