#!/bin/sh

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/nosp (No Smart-Placement)
# Started On        - Sat 16 Sep 20:03:52 BST 2017
# Last Change       - Sat 11 Jan 22:13:39 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# A workaround for the issue in XFCE wherein Smart Placement refuses to go away.
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

[ $# -eq 0 ] || Err 1 "No arguments are required."

ChkDep xfconf-query sleep

LocalXMLFile="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
CurrentValue=`xfconf-query -c xfwm4 -p /general/placement_ratio -t int`

if [ -f "$LocalXMLFile" ] && [ -w "$LocalXMLFile" ]; then
	# This command group waits, sets value to 90, waits, then sets back to 100.
	{
		sleep 3s
		xfconf-query -c xfwm4 -p /general/placement_ratio -s 90 -t int
		sleep 0.3 # Removing wait time results in this fix not working.
		xfconf-query -c xfwm4 -p /general/placement_ratio -s 100 -t int
	} &
else
	Err 1 "Unable to fix Smart Placement."
fi

