#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - Extra/source/nosp (No Smart-Placement)
# Started On        - Sat 16 Sep 20:03:52 BST 2017
# Last Change       - Tue  8 Dec 00:20:49 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Workaround for the issue causing XFCE Smart Placement to refuses to go away.
#------------------------------------------------------------------------------

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

[ $# -eq 0 ] || Err 1 "No arguments are required."

DepCount=0
for Dep in xfconf-query sleep; do
	if ! command -V 1> /dev/null 2>&1; then
		Err 0 "Dependency '$Dep' not met."
		DepCount=$((DepCount + 1))
	fi
done

[ $DepCount -gt 0 ] && exit 1

LocalXMLFile="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
CurrentValue=`xfconf-query -c xfwm4 -p /general/placement_ratio -t int`

if [ -f "$LocalXMLFile" ] && [ -w "$LocalXMLFile" ]; then
	# This command group waits, sets value to 90, waits, then sets back to 100.
	{
		sleep 3s
		xfconf-query -c xfwm4 -p /general/placement_ratio -s 90 -t int
		sleep 0.3 # Removing wait time results in this fix not working.
		xfconf-query -c xfwm4 -p /general/placement_ratio -s 100 -t int
	} &
else
	Err 1 "Unable to fix Smart Placement."
fi
