#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/nxbt
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/nxbt (New XBT)
# Started On        - Fri  6 Oct 17:52:55 BST 2017
# Last Change       - Fri  6 Dec 22:53:19 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-12-06"
_PROJECT_=${0##*/}

declare -i SECONDS=0

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

DOM="https://github.com"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} - NEW XBT ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            A fork of and improvement over Joe Collins' XBT.

		SYNTAX:     $_PROJECT_ [OPTS] TARGET

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --quiet|-q              - Runs in quiet mode. Errors still output.
		            --debug|-D              - Enables the built-in bash debugging.
		            --log|-l PATH           - Choose a different location for the logfile.

		NOTE:       Where TARGET is the location to store the backed up files. The files
		            will be stored within a timestamped directory. An example TARGET:

		              $_PROJECT_ /media/\$USER/Backup_Drive/

		FILE:       By default, errors are redirected to: /tmp/${_PROJECT_}_*.log

		SITE:       $DOM/terminalforlife/$_PROJECT_
	EOF
}

#		            --source|-s PATH        - Choose a different location to back up.
#		            --and-source|-S PATH    - Custom source to back up, with the defaults.

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--quiet|-q)
			BEQUIET='true' ;;
		--debug|-D)
			DEBUGME='true' ;;
		--logfile|-l)
			shift
			if [ -d "${1%\/*}" ]; then
				LOGFILE=$1
			else
				Err 1 $LINENO "Logfile directory not found."
			fi ;;
#		--source|-s)
#			shift
#			if [ -d "${1%\/*}" ]; then
#				SOURCE+=" $1"
#			else
#				Err 1 $LINENO "Source directory not found."
#			fi ;;
#		--and-source|-S)
#			shift
#			if [ -d "${1%\/*}" ]; then
#				ANDSOURCE='true' SOURCE+=( "$1")
#			else
#				Err 1 $LINENO "Source directory not found."
#			fi ;;
		*)
			break ;;
	esac
	shift
done

declare -i DEPCOUNT=0
for DEP in wget rsync mkdir sync; {
	if ! type -fP "$DEP" > /dev/null 2>&1; then
		Err 0 $LINENO "Dependency '$DEP' not met."
		DEPCOUNT+=1
	fi
}

[ $DEPCOUNT -eq 0 ] || exit 1

#Err 1 $LINENO "Incorrect option(s) specified." ;;
[ "$BEQUIET" == 'true' ] && exec > /dev/null
[ "$DEBUGME" == 'true' ] && set -x

[ -d "$*" ] || Err 1 $LINENO "Unable to find or access the TARGET directory."

TARGET="$*"
[ -f "$TARGET" ] && Err 1 "Target is not a directory."
[[ "$TARGET" == */ ]] || TARGET+="/"

printf -v CURDATE "%(%F_%X)T" "-1"
#TODO - Make the logfile skip the whole /tmp part; redundant.
LOGFILE="/tmp/${_PROJECT_}_${USER}_${CURDATE}.log"
BACKNAME=${_PROJECT_^^}_${UID}_${CURDATE}
if ! [ -d "$BACKNAME" ]; then
	mkdir "${TARGET}${BACKNAME}" || exit $?
fi

printf "[+%0.7d] LOGGING: %s\n" "$SECONDS" "$LOGFILE"
printf "[%s]: TARGET='%s' FROM='%s' USER='%s' UID='%s'\n"\
	"${CURDATE:-???}" "${TARGET:-???}" "${HOSTNAME:-???}"\
	"${USER:-???}" "${UID:-???}" > "$LOGFILE"

DEFAULT_PATHS(){
	printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "$HOME"
	TARGETPATH="${TARGET}${BACKNAME}/$USER/"
	[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"

	rsync -a --delete --info=progress2 "$HOME" "$TARGETPATH" 2> "$LOGFILE"

	printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "/etc"
	TARGETPATH="${TARGET}${BACKNAME}/etc/"
	[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"

	rsync -a --delete --info=progress2 "/etc" "$TARGETPATH" 2> "$LOGFILE"
}

USER_PATH(){
	#TODO - Incorporate multiple optional sources, maybe using for loop.

	# Back up user-provided files.
	for I in $SOURCE; {
		printf "[+%0.7d] PROCESSING: %s\n" "$SECONDS" "$SOURCE"
		TARGETPATH=${TARGET}/${BACKNAME}/${SOURCE//*\/}
		[ -d "$TARGETPATH" ] || mkdir "$TARGETPATH"

		rsync -a --delete --info=progress2\
			"$SOURCE" "$TARGETPATH"/ 2> "$LOGFILE"
	}
}

# Use either custom path alone, or custom path plus defaults.
if ! [ "$SOURCE" ]; then
	DEFAULT_PATHS
else
	if [ "$ANDSOURCE" == 'true' ]; then
		DEFAULT_PATHS; USER_PATH
	else
		USER_PATH
	fi
fi

printf "[+%0.7d] SYNCHRONIZING...\n" "$SECONDS"
sync

if [ -f "$LOGFILE" ]; then
	readarray REPLY < "$LOGFILE"
	if [ "${REPLY[*]}" ]; then
		printf "[+%0.7d] SAVING: %s\n" "$SECONDS"\
			"${TARGET}${BACKNAME}/${LOGFILE//*\/}"

		READ="$(< $LOGFILE)"
		printf "%s\n" "$READ" > "${TARGET}${BACKNAME}/${LOGFILE//*\/}"
	else
		printf "[+%0.7d] CLEANING: %s\n" "$SECONDS" "$LOGFILE"
	fi
else
	Err 1 $LINENO "Logfile not found."
fi

if [ -f "$LOGFILE" ]; then
	readarray X < "$LOGFILE"
	declare -i ERRCOUNT=${#X[@]}
fi

while read -r; do
	printf "%s\n" "$REPLY"
done <<-EOF

	+————————————————+
	| All backed up! |
	+————————————————+

	TIME: ${SECONDS:-???}s
	LINE: ${ERRCOUNT:-???}
EOF

