#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - Extra/source/repack
# Started On        - Wed 19 Feb 01:35:16 GMT 2020
# Last Change       - Wed 19 Feb 01:47:29 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This is a personal script to automate part of Debian package building.
#------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-02-19'
Progrm=${0##*/}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\rUsage: $Progrm [OPTS]

		\r  -h, --help               - Display this help information.
		\r  -v, --version            - Output the version datestamp.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		#-*)
		#	Err 1 'Incorrect option(s) specified.' ;;
		#*)
		#	break ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

#ChkDep id

#[ `id -u` -eq 0 ] || Err 1 'Root access is required.'
