#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/seewttr
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/seewttr
# Started On        - Thu 21 Sep 18:53:42 BST 2017
# Last Change       - Sun 19 Jan 18:52:02 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

set -e
. /usr/lib/tflbp-sh/Err
. /usr/lib/tflbp-sh/ChkDep
set +e

CurVer='2020-01-19'
Progrm=${0##*/}

Domain='http://wttr.in'

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\r            SEEWTTR ($CurVer)
		\r            Written by terminalforlife <terminalforlife@yahoo.com>

		\r            Bourne POSIX shell script to fetch weather information.

		\rSYNTAX:     $Progrm [OPTS] [LOC]

		\rOPTS:       --help|-h|-?            - Displays this help information.
		\r            --version|-v            - Output only the version datestamp.
		\r            --current|-c            - Show only the current weather.

		\rNOTE:       Format for LOC is, for example: town,country

		\rSITE:       $Domain
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--current|-c)
			Current='true' ;;
		-*)
			Err 1 'Incorrect option(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

ChkDep wget

[ -z "$*" ] && Err 1 "No 'LOC' provided."

LineCount=0
wget -q -O - "http://wttr.in/$*" | while IFS="" read -r CurLine; do
	if [ "$Current" = 'true' ]; then
		if [ $LineCount -le 6 ]; then
			LineCount=$((LineCount + 1))
		else
			break
		fi
	fi

	case $CurLine in
		Weather*|New*|Follow*) ;;
		*) printf "%s\n" "$CurLine" ;;
	esac
done
