#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/local/bin/seewttr
#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/seewttr
# Started On        - Thu 21 Sep 18:53:42 BST 2017
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Fetch weather information, using the 'wttr.in' website.
#------------------------------------------------------------------------------

CurVer='2023-06-15'
Progrm='seewttr'

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS] TOWN,COUNTRY

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
		  -c, --current            - Show only the current weather.
	EOF

	printf '%s' "$REPLY"
}

Err(){
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

Domain='http://wttr.in'

while [[ -n $1 ]]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		--current|-c)
			Current='True' ;;
		-*)
			Err 1 'Incorrect option(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

(( $# == 0 )) && Err 1 "No location provided -- see: $Progrm --help"

if ! type -P wget &> /dev/null; then
	Err 1 "Dependency 'wget' not met."
fi

while read -r; do
	if [[ $Current == True ]]; then
		if (( LineNr <= 6 )); then
			(( LineNr++ ))
		else
			printf '\n'
			break
		fi
	fi

	case $REPLY in
		Weather*|New*|Follow*|Location:*)
			;;
		*)
			printf '%b\n' "$REPLY" ;;
	esac
done <<< "$(wget -qO - http://wttr.in/"$1")"
