#!/bin/bash
#cito M:755 O:0 G:0 T:/usr/bin/simwea
#----------------------------------------------------------------------------------
# Project Name      - Extra/source/simwea (Simple Weather)
# Started On        - Sun 17 Sep 22:16:30 BST 2017
# Last Change       - Fri  6 Dec 22:54:40 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------

_VERSION_="2019-12-06"
_PROJECT_=${0##*/}

Err(){
	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
	[ $1 -eq 1 ] && exit 1
}

DOM="https://darksky.net"

USAGE(){
	while read -r; do
		printf "%s\n" "$REPLY"
	done <<-EOF
		            ${_PROJECT_^^} ($_VERSION_)
		            Written by terminalforlife <terminalforlife@yahoo.com>

		            Display various weather statistics on a terminal.

		SYNTAX:     $_PROJECT_ [OPTS]

		OPTS:       --help|-h|-?            - Displays this help information.
		            --version|-v            - Output only the version datestamp.
		            --fahrenheit|-F         - Display temperature in Fahrenheit.
		            --celsius|-C            - Display temperature in Celsius.
		            --long|-l N             - Where N is the longitude coordinate.
		            --lat|-L N              - Where N is the latitude coordinate.

		NOTE:       Only British and American localizations are supported.

		EXAMPLE:    View the weather for London, United Kingdom:

		              $_PROJECT_ -C --lat 51.5085300 --long -0.1257400

		SITE:       $DOM
	EOF
}

[ $# -eq 0 ] && Err 1 $LINENO "Arguments are required."

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			USAGE; exit 0 ;;
		--version|-v)
			printf "%s\n" "$_VERSION_"
			exit 0 ;;
		--debug|-D)
			DEBUGME='true' ;;
		--fahrenheit|-F)
			UKUS="us"; SYM="°F" ;;
		--celsius|-C)
			UKUS="uk"; SYM="°C" ;;
		--long|-l)
			shift
			if [[ $1 =~ [-0-9.]+ ]]; then
				LONG=$1
			else
				Err 1 $LINENO "Invalid longitude."
			fi ;;
		--lat|-L)
			shift
			if [[ $1 =~ [-0-9.]+ ]]; then
				LAT=$1
			else
				Err 1 $LINENO "Invalid latitude."
			fi ;;
		*)
			break ;;
	esac
	shift
done

type -P wget > /dev/null 2>&1 || Err 1 $LINENO "Dependency 'wget' not met."

if ! [ "$#" ]; then
	Err 1 $LINENO "Incorrect argument(s) given."
elif [ -z "$UKUS" ] || [ -z "$SYM" ]; then
	Err 1 $LINENO "Missing Fahrenheit or Celsius arguments."
elif [ -z "$LONG" ] || [ -z "$LAT" ]; then
	Err 1 $LINENO "Missing longitude and latitude arguments."
fi

[ "$DEBUGME" == 'true' ] && set -x

PAGE="$DOM/forecast/${LAT},${LONG}/${UKUS}12/en"

while read LINE; do
	if [[ $LINE == *currently\ =* ]]; then
		RESULT="$(
			IFS="," read -a FIELD <<< "${LINE//['{}"=']}"
			if ! [ "${FIELD[0]}" == "currently" ]; then
				printf "%s\n" "${FIELD[@]// /%20}"
			fi
		)"

		while IFS=":" read -a LINE; do
			DONE=${LINE[1]//%20/ }
			case ${LINE[0]} in
				summary)
					printf "%-20s%s\n" "Summary:" "$DONE" ;;
				apparentTemperature)
					printf "%-20s%s%s\n" "ApparentTemp:" "$DONE" "${SYM}" ;;
				temperature)
					printf "%-20s%s%s\n" "ActualTemp:" "$DONE" "${SYM}" ;;
				precipIntensity)
					printf "%-20s%s\n" "PrecipIntensity:" "$DONE" ;;
				precipProbability)
					printf "%-20s%s\n" "PrecipChance:" "$DONE" ;;
				precipType)
					printf "%-20s%s\n" "PrecipType:" "$DONE" ;;
				windSpeed)
					printf "%-20s%smph\n" "WindSpeed:" "$DONE" ;;
				windGust)
					printf "%-20s%smph\n" "WindGust:" "$DONE" ;;
				windBearing)
					printf "%-20s%s\n" "WindBearing:" "$DONE" ;;
				pressure)
					printf "%-20s%shPa\n" "AirPressure:" "$DONE" ;;
				humidity)
					printf "%-20s%s%%\n" "Humidity:" "$DONE" ;;
				visibility)
					printf "%-20s%smi\n" "Visibility:" "$DONE" ;;
				uvIndex)
					printf "%-20s%s\n" "UVIndex:" "$DONE" ;;
				ozone)
					printf "%-20s%s\n" "Ozone:" "$DONE" ;;
				cloudCover)
					printf "%-20s%s\n" "CloudCover:" "$DONE" ;;
			esac
		done <<< "$RESULT"
		break
	fi
done <<< "$(wget $NOWARC -q "$PAGE" -O -)"
