#!/bin/bash

#----------------------------------------------------------------------------------
# Project Name      - Extra/source/syswatch
# Started On        - Thu  9 Nov 14:33:34 GMT 2017
# Last Change       - Wed 27 Nov 15:56:46 GMT 2019
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#----------------------------------------------------------------------------------
# This is a somewhat rudimentary script to watch for and notify when a device is
# connected, disconnected, or mounted. Sadly no unmount notifications, yet. Run
# this at startup. It works a bit like a daemon. Also notifies when the "link" is
# up or down, which can be useful for troubleshooting.
#
# Wrote this for use with dunst, but could work well with other daemons.
#----------------------------------------------------------------------------------

_VERSION_="2019-11-27"
_PROJECT_=${0##*/}

declare -i DEPCOUNT=0
for DEP in dmesg grep sleep tail notify-send; {
	type -fP "$DEP" > /dev/null 2>&1 || exit 1
}

#TODO - Ignore the entries already there on log-in.
while :; do
	LAST(){
		# Not using pure-shell approach here, due to performance issues.
		#TODO - The mount and unmount notifications aren't showing.
		ERE='(link (down|up)$|disconnect|detected)'
		dmesg -tl 6 | grep -E "$ERE" | tail -n 1
	}

	if ! [ "$(LAST)" == "$LAST_BUFFER" ]; then
		printf -v NS "[%(%F_%X)T]: %s" "-1" "$(LAST)"

		if ! [ "$BUF" == "$NS" ]; then
			notify-send --urgency=critical "$NS"
		fi
	fi

	LAST_BUFFER="$(LAST)"

	# Avoids excessive processing. This interval should probably be increased
	# on older and/or otherwise slower machines.
	sleep 0.1s
done

