#!/bin/sh

#------------------------------------------------------------------------------
# Project Name      - Extra/source/tfl-ubuntu-setup
# Started On        - Thu 14 Jun 23:36:44 BST 2018
# Last Change       - Thu 27 Feb 22:52:28 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This installation script is for use after installing via something like the
# `mini.iso` of Ubuntu 16.04, or after using rmne(8) and installing only the
# basics, like the kernel, UFW, etc.
#------------------------------------------------------------------------------

CurVer='2020-02-27'
Progrm=${0##*/}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\rUsage: $Progrm [OPTS]

		\r  -h, --help               - Display this help information.
		\r  -v, --version            - Output the version datestamp.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

DepCount=0
for CurDep in apt-get id; do
	if ! command -v "$CurDep" 1> /dev/null 2>&1; then
		DepCount=$((DepCount + 1))

		Err 0 "Dependency '$CurDep' not met."
	fi
done

[ $DepCount -eq 0 ] || exit 1

[ `id -u` -eq 0 ] || Err 1 'Root access is required.'

AptOpts='-q -o Dpkg::Progress=true -o Dpkg::Progress-Fancy=true'

# If either `update` or `dist-upgrade` fail, quit.
apt-get $AptOpts update && apt-get $AptOpts dist-upgrade || exit 1

for Pack in wget i3-wm feh i3lock scrot; do
	command -v $Pack 1> /dev/null 2>&1 && continue
	if ! apt-get $AptOpts install $Pack; then
		Err 0 "Package '$Pack' failed to install."
	fi
done
