#!/bin/sh
#cito M:755 O:0 G:0 T:/usr/bin/tfl-ubuntu-setup
#------------------------------------------------------------------------------
# Project Name      - Extra/source/tfl-ubuntu-setup
# Started On        - Thu 14 Jun 23:36:44 BST 2018
# Last Change       - Sat 29 Feb 01:54:34 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# This installation script is for use after installing via something like the
# `mini.iso` of Ubuntu 16.04, or after using rmne(8) and installing only the
# basics, like the kernel, UFW, etc. Would probably work on 18.04, however.
#
# Features:
#
#TODO: Fetch the user's real UID and GID, despite root access being required.
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   apt (>= 1.2.32)
#   coreutils (>= 8.25-2)
#   dpkg (>= 1.18.4)
#------------------------------------------------------------------------------

CurVer='2020-02-29'
Progrm=${0##*/}

Err(){
	printf 'ERROR: %s\n' "$2" 1>&2
	[ $1 -gt 0 ] && exit $1
}

Usage(){
	while read -r CurLine; do
		printf '%b\n' "$CurLine"
	done <<-EOF
		\rUsage: $Progrm [OPTS]

		\r  -h, --help               - Display this help information.
		\r  -v, --version            - Output the version datestamp.
	EOF
}

while [ "$1" ]; do
	case $1 in
		--help|-h|-\?)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect option(s) specified.' ;;
	esac
	shift
done

Count=0
for Dep in tr sh mktemp apt-get id dpkg; do
	if ! command -v "$Dep" 1> /dev/null 2>&1; then
		Count=$((Count + 1))
		Err 0 "Dependency '$Dep' not met."
	fi
done

[ $Count -eq 0 ] || exit 1

[ `id -u` -eq 0 ] || Err 1 'Root access is required.'

#--------------------------------------------------Gather Information from User

# Gather the user's UID and GID; don't want root's.
printf 'Enter your UID and GID, for example: 1000:1000\n: '
read Answer

[ -z "$Answer" ] && Err 1 'Invalid UID and/or GID provided.'

case $Answer in
	# I know -- IDs go higher than this, but for those using this script, it's
	# very unlikely they'll be using IDs greater than 9999, or less than 1000.
	[0-9][0-9][0-9][0-9]:[0-9][0-9][0-9][0-9])
		UID=${Answer%:*}
		GID=${Answer#*:}

		if [ $UID -lt 1000 ]; then
			Err 1 "Our-of-range UID provided."
		elif [ $GID -lt 1000 ]; then
			Err 1 "Our-of-range GID provided."
		fi ;;
	*)
		Err 1 'Invalid UID and/or GID provided.' ;;
esac

printf 'Enter a space-delimited list of extra Debian packages to install.\n: '
read ExtraPkgs
if [ -z "$ExtraPkgs" ]; then
	printf 'No additional packages provided.\n'
else
	case $ExtraPkgs in
		*[\!\"\'\£\$\%\^\&\*\(\)\=\+\~\#\}\]\{\[\?\/\>\\\<,\|\`\¬]*)
			Err 1 'One or more invalid packages selected.' ;;
		*)
			Count=0
			for Pkg in $ExtraPkgs; do
				Count=$((Count + 1))
			done

			printf 'A total of %d extra package(s) chosen.\n' $Count ;;
	esac
fi

printf 'Press any key to continue, or Ctrl + C to quit... '
read AnyKey

#-----------------------------------------------Actual Installation Starts Here

GHUser='terminalforlife'
GitHub="https://raw.githubusercontent.com/$GHUser"
Pkgs="$GitHub/DEB-Packages/master"
AptOpts='-q -o Dpkg::Progress=true -o Dpkg::Progress-Fancy=true'

# If either `update` or `dist-upgrade` fails, quit.
apt-get $AptOpts update 1> /dev/null &&
	apt-get $AptOpts dist-upgrade 1> /dev/null || exit 1

for Pack in\
\
	wget git redshift moc pulseaudio pavucontrol i3 feh i3lock scrot perl\
	manpages-posix man-db perl-doc vim newsbeuter $ExtraPkgs
do
	command -v $Pack 1> /dev/null 2>&1 && continue
	printf 'Installing package: %s\n' "$Pack"
	apt-get $AptOpts install $Pack 1> /dev/null
done

TempDir=`mktemp -d`

# Install all of the latest TFL packages.
for Pkg in\
\
	libtflbp-sh libtfl-perl ubuchk kernelchk lsbins lspkg autoexec backmeup\
	apt-undo-install apt-download-deps clean-locales cpufreq feh-slides\
	fix-ff-gtk getip gitsap redshifter purgerc previewer notify-upgrade mplay\
	rmne roks seewttr shlides simplify-ubuntu suptime tudu ubuchk wcdl
do
	printf 'Installing package: %s\n' "$Pkg"

	for Iter in 1 2; do
		case $Iter in
			1)
				Latest="$TempDir/latest"
				wget -qO "$Latest" "$Pkgs/$Pkg/latest" 1> /dev/null
				read Package < "$Latest" ;;
			2)
				PkgFile="$TempDir/$Package"
				wget -qO "$PkgFile" "$Pkgs/$Pkg/$Package" 1> /dev/null
				dpkg -i "$PkgFile" 1> /dev/null ;;
		esac
	done
done

# Get dependencies for the above.
printf 'Installing dependencies.\n'
apt-get $AptOpts install -f 1> /dev/null

printf 'Clearing temporary directory.\n'
rm -r "$TempDir"

printf 'Setting safer permissions for certain directories.\n'
for Dir in /boot /root /home/*; do
	if [ "$Dir" != '/home/lost+found' ]; then
		[ -d "$Dir" ] && chmod 700 "$Dir"
	fi
done

# Highly unlikely to be needed, but just in-case.
if ! [ `cito -v | tr -d '-'` -ge 20200229 ]; then
	Err 1 'TFL-Ubuntu-Setup requires Cito version 2020-02-29 or later.'
fi

# Install all of the TFL BashConfig stuff.
printf 'Installing: /usr/bin/lad\n'
cito -c -r "$GHUser" BashConfig master source/lad
for File in .bashrc .bash_aliases .bash_functions .profile; do
	printf 'Installing: %s\n' "$HOME/$File"
	cito -c -M 600 -O $UID -G $GID -T "$HOME/$File"\
		-r "$GHUser" BashConfig master "source/$File"
done

# Install all of the TFL VimConfig stuff.
mkdir -p --mode=700 "$HOME/.vim"
mkdir -p --mode=700 "$HOME/.vim/colors"
mkdir -p --mode=700 "$HOME/.vim/plugin"
mkdir -p --mode=700 "$HOME/.vim/snippet"
chmod -R u=rwX,g=,o= "$HOME/.vim"
chown -R $UID:$GID "$HOME/.vim"

cito -c -M 600 -O $UID -G $GID -T "$HOME/.vimrc"\
	-r "$GHUser" VimConfig master source/.vimrc

for File in\
\
	colors/tfl.vim plugin/sanekeys.vim plugin/noarrows.vim plugin/moredoc.vim\
	plugin/mouseon.vim plugin/virtedit.vim plugin/textwidth.vim\
	plugin/banger.vim plugin/psnips.vim plugin/headup.vim\
	plugin/autoscroll.vim plugin/tflsnips.vim plugin/giteditmsg.vim\
	plugin/altnums.vim plugin/mvline.vim plugin/tflstatus.vim\
	plugin/listmode.vim plugin/sudosave.vim plugin/comtog.vim\
	plugin/datepaste.vim plugin/exefile.vim plugin/togtrans.vim\
	plugin/simplyhard.vim snippet/psetup snippet/setup snippet/modeline\
	snippet/die snippet/wgetchk snippet/bsetup snippet/disclaimer\
	snippet/args snippet/updatechk
do
	printf 'Installing: %s\n' "$HOME/.vim/$File"
	cito -c -M 600 -O $UID -G $GID -T "$HOME/.vim/$File"\
		-r "$GHUser" VimConfig master "source/$File"
done

# Install all of the TFL i3Config stuff.
mkdir -p --mode=700 "$HOME/.config/i3"
mkdir -p --mode=700 "$HOME/.i3a"
chmod -R u=rwX,g=,o= "$HOME/.i3a" "$HOME/.config/i3"
chown -R $UID:$GID "$HOME/.vim" "$HOME/.config/i3"

cito -c -M 600 -O $UID -G $GID -T "$HOME/.config/i3/config"\
	-r "$GHUser" i3Config master source/config

for File in\
\
	dev_setup dmesg_overflow hush_the_mic initialize key_autorepeat\
	leave_session lockscreen partmount scrot_sel_take scrot_take\
	scrot_win_take sink_lower sink_mute sink_raise sink_switch source_lower\
	source_mute source_raise term_font_size terminal track_notify use_dmenu
do
	printf 'Installing: %s\n' "$HOME/.i3a/$File"
	cito -c -M 600 -O $UID -G $GID -T "$HOME/.vim/$File"\
		-r "$GHUser" i3Config master "source/.i3a/$File"
done

# Install some programs which don't have Debian packages.
for File in\
\
	barred bdl bios-info forex mif mkpass mplay simwea seewttr getline
do
	printf 'Installing program: %s\n' "$File"
	cito -c -r "$GHUser" Extra master source/"$File"
done

printf 'Synchronizing cached writes.\n'
sync


