#!/bin/sh -e

#------------------------------------------------------------------------------
# Project Name      - Extra/source/tfs
# Started On        - Fri  4 Dec 00:12:10 GMT 2020
# Last Change       - Thu 16 Dec 00:11:26 GMT 2021
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# [T]esseract [f]rom [S]creenshot.
#
# Written to help 'IonParticles' from the Linux Mint support forums, after they
# sadly had a chunk of data loss -- consolation prize?
#
#   https://forums.linuxmint.com/viewtopic.php?f=90&t=336520&p=1931060#p1931060
#
# Bug in the version of tesseract(1) available in Ubuntu 20.04's repositories
# now seems to be sorted, although I haven't a clue how; couldn't get any info
# anywhere online. See the above thread for more information on this.
#
# Dependencies:
#
#   coreutils (>= 8.28-1ubuntu1)
#   scrot (>= 0.8-18)
#   tesseract-ocr (>= 4.00~git2288-10f4998a-2)
#   xclip (>= 0.12+svn84-4build1)
#------------------------------------------------------------------------------

if [ $# -gt 0 ]; then
	printf 'Err: Arguments not required.\n' 1>&2
	exit 1
fi

TempFile=`mktemp --suffix='.png'`

SigHandler(){
	Sig=$?
	printf 'Clearing temporary file... '

	if rm "$TempFile"; then
		printf '[OK]\n'
	else
		printf '[ERR]\n'
	fi

	exit $Sig
}

trap 'SigHandler' EXIT || Err 1 "Failed to trap 'EXIT' signal."

{ gnome-screenshot -af "$TempFile" || scrot -sq 100 "$TempFile"; } || exit 1
tesseract "$@" "$TempFile" stdout | xclip -i -selection clipboard
