#!/usr/bin/env bash
#cito M:755 O:0 G:0 T:/usr/bin/tlptog
#------------------------------------------------------------------------------
# Project Name      - Extra/source/tlptog
# Started On        - Fri 18 May 14:19:48 BST 2018
# Last Change       - Fri  4 Mar 00:18:27 GMT 2022
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Quick shell program to toggle TLP to improve power management on portable
# setups.
#------------------------------------------------------------------------------

CurVer='2022-03-04'
Progrm='tlptog'

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS]

		  -h, --help               - Displays this help information.
		  -v, --version            - Output only the version datestamp.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

WorkFile='/etc/default/tlp'

while [[ -n $1 ]]; do
	case $1 in
		--help|-h)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		*)
			Err 1 'Incorrect argument(s) specified.' ;;
	esac
	shift
done

if ! type -P sed &> /dev/null; then
	Err 1 "Dependency 'sed' not met."
elif (( UID != 0 )); then
	Err 1 'Root access is required.'
fi

[[ -f $WorkFile ]] || Err 1 "Unable to find the '$WorkFile' file."

while IFS='=' read -a Line; do
	if [[ ${Line[0]} == \#* ]]; then
		continue
	elif [[ ${Line[0]} == TLP_ENABLE ]]; then
		if (( ${Line[1]} == 1 )); then
			if ! sed -i 's/\(TLP_ENABLE=\)1/\10/' "$WorkFile"; then
				Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '1'."
			fi
		elif (( ${Line[1]} == 0 )); then
			if ! sed -i 's/\(TLP_ENABLE=\)0/\11/' "$WorkFile"; then
				Err 1 "Parameter 'TLP_ENABLE' unsuccessfully set to '0'."
			fi
		else
			Err 1 "Invalid 'TLP_ENABLE' parameter assignment."
		fi

		break
	fi
done < "$WorkFile"
