#!/usr/bin/env bash

#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/trimit
# Started On        - Wed 24 May 11:38:31 BST 2023
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Very basic tool for removing leading and trailing spaces from filenames.
# Spaces consist of whitespaces, tabs, and newlines.
#
# Features:
#
# N/A
#
# Bugs:
#
# N/A
#
# Dependencies:
#
#   bash (>= 4.4.20)
#------------------------------------------------------------------------------

CurVer='2023-06-03'
Progrm=${0##*/}

Usage() {
	read -d '' <<-EOF
		Usage: $Progrm [OPTS] [FILE [FILE] ...]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
	EOF

	printf '%s' "$REPLY"
}

Err() {
	printf 'Err: %s\n' "$2" 1>&2
	(( $1 > 0 )) && exit $1
}

while [[ -n $1 ]]; do
	case $1 in
		--help|-h)
			Usage; exit 0 ;;
		--version|-v)
			printf '%s\n' "$CurVer"; exit 0 ;;
		-*)
			Err 1 'Incorrect option(s) specified.' ;;
		*)
			break ;;
	esac
	shift
done

for File in "$@"; {
	[[ -f $File ]] || continue

	Orig=$File
	Dirs=${File%/*}
	File=${File##*/}

	# From the left.
	Buffer=
	Len=${#File}
	for (( Index = 0; Index < Len; Index++ )); {
		Char=${File:Index:1}
		[[ $Char != [[:space:]] ]] && break
		Buffer+=$Char
	}

	File=${File#$Buffer}

	# From the right.
	Buffer=
	Len=${#File}
	for (( Index = Len - 1; Index >= 0; Index-- )); {
		Char=${File:Index:1}
		[[ $Char != [[:space:]] ]] && break
		Buffer+=$Char
	}

	New="$Dirs/${File%$Buffer}"
	if [[ $Orig != "$New" ]]; then
		if [[ -f $New ]]; then
			Err 0 "File '${New/$HOME/\~}' already exists."
		fi

		mv --no-clobber "$Orig" "$New"
	fi
}
