#!/usr/bin/env dash

#------------------------------------------------------------------------------
# Project Name      - ShellProjects/source/vl-audio
# Started On        - Fri 29 Apr 20:43:34 BST 2022
# Last Change       - Mon 19 Jun 23:34:57 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Simple, locale-friendly, and efficient DASH script to fetch the volume for
# the given sound device in Void Linux. Written for Discord user 'zargnut', -
# and anyone else who might find it useful. Depending on your device, you may
# need to tweak the code.
#
# Example:
#
#   $ vl-audio Headset
#   36% [on]
#------------------------------------------------------------------------------

amixer get "$1" | while read Mono _ _ Percent _ Status _; do
	if [ "$Mono" = 'Mono:' ]; then
		Percent=${Percent#\[}
		Percent=${Percent%\]}

		case $Percent in
			[[:digit:]][[:digit:]]\%|[[:digit:]][[:digit:]][[:digit:]]\%)
				: ;;
			''|*)
				Percent='?%' ;;
		esac

		case $Status in
			'[on]'|'[off]')
				: ;;
			''|*)
				Status='[?]' ;;
		esac

		printf '%s %s\n' "$Percent" "$Status"

		break
	fi
done
